export enum ActionEffectType {
  Nothing = 0,
  Miss = 1,
  FullResist = 2,
  Damage = 3,
  Heal = 4,
  BlockedDamage = 5,
  ParriedDamage = 6,
  Invulnerable = 7,
  NoEffectText = 8,
  Unknown_0 = 9,
  MpLoss = 10,
  MpGain = 11,
  TpLoss = 12,
  TpGain = 13,
  GpGain = 14,
  StartActionCombo = 28,
  Knockback = 33,
  Mount = 38,
  VFX = 59,
}
