packages:
  - packages/*

allowBuilds:
  esbuild: true

catalog:
  "@tsconfig/node20": ^20.1.4
  "@types/node": ^20.10.3
  reflect-metadata: ^0.2.2
  tsdown: ^0.22.2
  tsx: ^4.22.4
  typescript: ^6.0.3
