// Generated by src/sync/index.ts

// biome-ignore-all lint/complexity/useSimpleNumberKeys: opcode maps are easier to audit in hexadecimal
import { NormalizedOpcode } from './normalized-opcode.enum'
import type { OpcodeMap } from './opcode-map.type'

export const CN_5_21: OpcodeMap = {
  0x00a7: [{ type: NormalizedOpcode.PlayerStats }],
  0x00bb: [{ type: NormalizedOpcode.AoeEffect24 }],
  0x013c: [{ type: NormalizedOpcode.InitZone }],
  0x0146: [{ type: NormalizedOpcode.ActorCast }],
  0x0158: [{ type: NormalizedOpcode.ActorSetPos }],
  0x0165: [
    { type: NormalizedOpcode.BossStatusEffectList },
    { type: NormalizedOpcode.StatusEffectList },
  ],
  0x01b8: [{ type: NormalizedOpcode.UpdateClassInfo }],
  0x0202: [{ type: NormalizedOpcode.ActorMove }],
  0x0211: [{ type: NormalizedOpcode.NpcSpawn }],
  0x021f: [{ type: NormalizedOpcode.AoeEffect16 }],
  0x0229: [{ type: NormalizedOpcode.ActorControl }],
  0x0237: [{ type: NormalizedOpcode.UpdateHpMpTp }],
  0x025e: [{ type: NormalizedOpcode.ActorControlSelf }],
  0x029f: [{ type: NormalizedOpcode.AoeEffect32 }],
  0x02dd: [{ type: NormalizedOpcode.PlayerSetup }],
  0x034a: [{ type: NormalizedOpcode.AoeEffect8 }],
  0x035e: [{ type: NormalizedOpcode.Effect }],
  0x036a: [{ type: NormalizedOpcode.ActorGauge }],
  0x03a0: [{ type: NormalizedOpcode.PlayerSpawn }],
  0x03c9: [{ type: NormalizedOpcode.NpcSpawn2 }],
}
