// Generated by src/sync/index.ts

import { OpcodeMap } from './opcode-map.type'
import { NormalizedOpcode } from './normalized-opcode.enum'

export const CN_5_2: OpcodeMap = {
  0x00d5: [{ type: NormalizedOpcode.ActorSetPos, outgoing: false }],
  0x00eb: [{ type: NormalizedOpcode.Effect, outgoing: false }],
  0x00f7: [{ type: NormalizedOpcode.ActorGauge, outgoing: false }],
  0x0129: [
    { type: NormalizedOpcode.BossStatusEffectList, outgoing: false },
    { type: NormalizedOpcode.StatusEffectList, outgoing: false },
  ],
  0x0142: [{ type: NormalizedOpcode.ActorControlSelf, outgoing: false }],
  0x014a: [{ type: NormalizedOpcode.NpcSpawn2, outgoing: false }],
  0x0161: [{ type: NormalizedOpcode.AoeEffect8, outgoing: false }],
  0x016e: [{ type: NormalizedOpcode.AoeEffect16, outgoing: false }],
  0x024c: [{ type: NormalizedOpcode.AoeEffect32, outgoing: false }],
  0x0267: [{ type: NormalizedOpcode.AoeEffect24, outgoing: false }],
  0x0274: [{ type: NormalizedOpcode.PlayerSetup, outgoing: false }],
  0x0276: [{ type: NormalizedOpcode.PlayerStats, outgoing: false }],
  0x0282: [{ type: NormalizedOpcode.UpdateHpMpTp, outgoing: false }],
  0x029d: [{ type: NormalizedOpcode.ActorCast, outgoing: false }],
  0x033b: [{ type: NormalizedOpcode.InitZone, outgoing: false }],
  0x0356: [{ type: NormalizedOpcode.ActorMove, outgoing: false }],
  0x03aa: [{ type: NormalizedOpcode.UpdateClassInfo, outgoing: false }],
  0x03af: [{ type: NormalizedOpcode.ActorControl, outgoing: false }],
  0x03ba: [{ type: NormalizedOpcode.PlayerSpawn, outgoing: false }],
  0x03d2: [{ type: NormalizedOpcode.NpcSpawn, outgoing: false }],
}
