// Generated by src/sync/index.ts

import { OpcodeMap } from './opcode-map.type'
import { NormalizedOpcode } from './normalized-opcode.enum'

export const CN_5_1: OpcodeMap = {
  0x00de: [{ type: NormalizedOpcode.ActorControl, outgoing: false }],
  0x01c3: [{ type: NormalizedOpcode.ActorControlSelf, outgoing: false }],
  0x0382: [{ type: NormalizedOpcode.ActorGauge, outgoing: false }],
}
