// Generated by src/sync/index.ts

// biome-ignore-all lint/complexity/useSimpleNumberKeys: opcode maps are easier to audit in hexadecimal
import { NormalizedOpcode } from './normalized-opcode.enum'
import type { OpcodeMap } from './opcode-map.type'

export const CN_5_41: OpcodeMap = {
  0x0078: [{ type: NormalizedOpcode.ActorControlSelf }],
  0x008d: [{ type: NormalizedOpcode.AoeEffect8 }],
  0x00bd: [{ type: NormalizedOpcode.AoeEffect16 }],
  0x011c: [{ type: NormalizedOpcode.WardLandInfo }],
  0x018d: [{ type: NormalizedOpcode.Effect }],
  0x01ea: [{ type: NormalizedOpcode.ActorControl }],
  0x01f3: [{ type: NormalizedOpcode.PlayerStats }],
  0x022a: [{ type: NormalizedOpcode.AoeEffect32 }],
  0x023b: [{ type: NormalizedOpcode.ActorMove }],
  0x025b: [{ type: NormalizedOpcode.UpdateClassInfo }],
  0x0262: [{ type: NormalizedOpcode.UpdateHpMpTp }],
  0x026b: [{ type: NormalizedOpcode.ActorSetPos }],
  0x0286: [{ type: NormalizedOpcode.ActorFreeSpawn }],
  0x0296: [{ type: NormalizedOpcode.AoeEffect24 }],
  0x029a: [{ type: NormalizedOpcode.PlayerSpawn }],
  0x02a6: [{ type: NormalizedOpcode.InitZone }],
  0x0313: [{ type: NormalizedOpcode.NpcSpawn }],
  0x0317: [{ type: NormalizedOpcode.ActorCast }],
  0x0370: [{ type: NormalizedOpcode.PlayerSetup }],
  0x039a: [{ type: NormalizedOpcode.ActorGauge }],
  0x03c1: [{ type: NormalizedOpcode.StatusEffectList }],
}
