// Generated by src/sync/index.ts

// biome-ignore-all lint/complexity/useSimpleNumberKeys: opcode maps are easier to audit in hexadecimal
import { NormalizedOpcode } from './normalized-opcode.enum'
import type { OpcodeMap } from './opcode-map.type'

export const CN_5_15: OpcodeMap = {
  0x00b4: [
    { type: NormalizedOpcode.BossStatusEffectList },
    { type: NormalizedOpcode.StatusEffectList },
  ],
  0x00ff: [{ type: NormalizedOpcode.AoeEffect32 }],
  0x0128: [{ type: NormalizedOpcode.NpcSpawn2 }],
  0x0139: [{ type: NormalizedOpcode.AoeEffect16 }],
  0x0179: [{ type: NormalizedOpcode.ActorControlSelf }],
  0x0184: [{ type: NormalizedOpcode.NpcSpawn }],
  0x01b1: [{ type: NormalizedOpcode.AoeEffect8 }],
  0x023e: [{ type: NormalizedOpcode.Effect }],
  0x0261: [{ type: NormalizedOpcode.ActorSetPos }],
  0x029d: [{ type: NormalizedOpcode.PlayerSpawn }],
  0x032c: [{ type: NormalizedOpcode.ActorCast }],
  0x0345: [{ type: NormalizedOpcode.InitZone }],
  0x034a: [{ type: NormalizedOpcode.UpdateHpMpTp }],
  0x0350: [{ type: NormalizedOpcode.ActorGauge }],
  0x0366: [{ type: NormalizedOpcode.ActorControl }],
  0x0376: [{ type: NormalizedOpcode.PlayerSetup }],
  0x038b: [{ type: NormalizedOpcode.AoeEffect24 }],
  0x039e: [{ type: NormalizedOpcode.ActorMove }],
  0x03c5: [{ type: NormalizedOpcode.UpdateClassInfo }],
}
