// Generated by src/sync/index.ts

import { OpcodeMap } from './opcode-map.type'
import { NormalizedOpcode } from './normalized-opcode.enum'

export const CN_5_3: OpcodeMap = {
  0x00a5: [{ type: NormalizedOpcode.ActorCast, outgoing: false }],
  0x00b5: [{ type: NormalizedOpcode.PlayerSpawn, outgoing: false }],
  0x00d8: [{ type: NormalizedOpcode.UpdateHpMpTp, outgoing: false }],
  0x00f8: [{ type: NormalizedOpcode.ActorSetPos, outgoing: false }],
  0x0130: [{ type: NormalizedOpcode.WardLandInfo, outgoing: false }],
  0x0186: [{ type: NormalizedOpcode.PlayerStats, outgoing: false }],
  0x01a8: [{ type: NormalizedOpcode.AoeEffect8, outgoing: false }],
  0x01d3: [{ type: NormalizedOpcode.NpcSpawn, outgoing: false }],
  0x024a: [{ type: NormalizedOpcode.AoeEffect24, outgoing: false }],
  0x027b: [{ type: NormalizedOpcode.AoeEffect32, outgoing: false }],
  0x0294: [{ type: NormalizedOpcode.InitZone, outgoing: false }],
  0x02b0: [{ type: NormalizedOpcode.ActorControlSelf, outgoing: false }],
  0x02c3: [{ type: NormalizedOpcode.UpdateClassInfo, outgoing: false }],
  0x02dc: [{ type: NormalizedOpcode.ActorMove, outgoing: false }],
  0x02f2: [{ type: NormalizedOpcode.ActorGauge, outgoing: false }],
  0x02f5: [{ type: NormalizedOpcode.PlayerSetup, outgoing: false }],
  0x0300: [{ type: NormalizedOpcode.AoeEffect16, outgoing: false }],
  0x0312: [{ type: NormalizedOpcode.ActorControl, outgoing: false }],
  0x0360: [{ type: NormalizedOpcode.StatusEffectList, outgoing: false }],
  0x036e: [{ type: NormalizedOpcode.ActorFreeSpawn, outgoing: false }],
  0x03d2: [{ type: NormalizedOpcode.Effect, outgoing: false }],
}
