// Generated by src/sync/index.ts

// biome-ignore-all lint/complexity/useSimpleNumberKeys: opcode maps are easier to audit in hexadecimal
import { NormalizedOpcode } from './normalized-opcode.enum'
import type { OpcodeMap } from './opcode-map.type'

export const CN_6_45a: OpcodeMap = {
  0x00b4: [{ type: NormalizedOpcode.AoeEffect24 }],
  0x00f2: [{ type: NormalizedOpcode.PlayerStats }],
  0x00ff: [{ type: NormalizedOpcode.Effect }],
  0x0103: [{ type: NormalizedOpcode.ActorMove }],
  0x016b: [{ type: NormalizedOpcode.BossStatusEffectList }],
  0x017f: [{ type: NormalizedOpcode.ActorCast }],
  0x018d: [{ type: NormalizedOpcode.InitZone }],
  0x01c1: [{ type: NormalizedOpcode.NpcSpawn2 }],
  0x01ec: [{ type: NormalizedOpcode.UpdateClassInfo }],
  0x0208: [{ type: NormalizedOpcode.AoeEffect32 }],
  0x0283: [{ type: NormalizedOpcode.PlayerSetup }],
  0x028d: [{ type: NormalizedOpcode.WardLandInfo }],
  0x029f: [{ type: NormalizedOpcode.ActorSetPos }],
  0x02b1: [{ type: NormalizedOpcode.AoeEffect16 }],
  0x02c3: [{ type: NormalizedOpcode.ActorControl }],
  0x0302: [{ type: NormalizedOpcode.ActorControlSelf }],
  0x032b: [{ type: NormalizedOpcode.AoeEffect8 }],
  0x032e: [{ type: NormalizedOpcode.ActorGauge }],
  0x0393: [{ type: NormalizedOpcode.NpcSpawn }],
  0x039b: [{ type: NormalizedOpcode.PlayerSpawn }],
  0x03b6: [{ type: NormalizedOpcode.ActorFreeSpawn }],
  0x03d5: [{ type: NormalizedOpcode.UpdateHpMpTp }],
  0x03e0: [{ type: NormalizedOpcode.StatusEffectList }],
}
