// Generated by src/sync/index.ts

// biome-ignore-all lint/complexity/useSimpleNumberKeys: opcode maps are easier to audit in hexadecimal
import { NormalizedOpcode } from './normalized-opcode.enum'
import type { OpcodeMap } from './opcode-map.type'

export const CN_6_05: OpcodeMap = {
  0x0076: [{ type: NormalizedOpcode.AoeEffect32 }],
  0x007b: [{ type: NormalizedOpcode.NpcSpawn }],
  0x00ff: [{ type: NormalizedOpcode.ActorControl }],
  0x0100: [{ type: NormalizedOpcode.Effect }],
  0x0103: [{ type: NormalizedOpcode.AoeEffect24 }],
  0x0113: [{ type: NormalizedOpcode.ActorGauge }],
  0x012a: [{ type: NormalizedOpcode.ActorSetPos }],
  0x0155: [{ type: NormalizedOpcode.ActorCast }],
  0x0163: [{ type: NormalizedOpcode.InitZone }],
  0x01a7: [{ type: NormalizedOpcode.NpcSpawn2 }],
  0x01bb: [{ type: NormalizedOpcode.PlayerSetup }],
  0x01c7: [{ type: NormalizedOpcode.ActorMove }],
  0x0208: [{ type: NormalizedOpcode.PlayerSpawn }],
  0x0236: [{ type: NormalizedOpcode.UpdateHpMpTp }],
  0x0242: [{ type: NormalizedOpcode.AoeEffect16 }],
  0x0249: [{ type: NormalizedOpcode.WardLandInfo }],
  0x028f: [{ type: NormalizedOpcode.StatusEffectList }],
  0x02ce: [{ type: NormalizedOpcode.PlayerStats }],
  0x0314: [{ type: NormalizedOpcode.AoeEffect8 }],
  0x032f: [{ type: NormalizedOpcode.BossStatusEffectList }],
  0x034f: [{ type: NormalizedOpcode.UpdateClassInfo }],
  0x03b7: [{ type: NormalizedOpcode.ActorControlSelf }],
}
