// Generated by src/sync/index.ts

// biome-ignore-all lint/complexity/useSimpleNumberKeys: opcode maps are easier to audit in hexadecimal
import { NormalizedOpcode } from './normalized-opcode.enum'
import type { OpcodeMap } from './opcode-map.type'

export const CN_6_58: OpcodeMap = {
  0x009a: [{ type: NormalizedOpcode.Effect }],
  0x00b6: [{ type: NormalizedOpcode.PlayerSetup }],
  0x0108: [{ type: NormalizedOpcode.ActorControl }],
  0x0126: [{ type: NormalizedOpcode.ActorFreeSpawn }],
  0x013c: [{ type: NormalizedOpcode.ActorMove }],
  0x014e: [{ type: NormalizedOpcode.NpcSpawn2 }],
  0x0159: [{ type: NormalizedOpcode.AoeEffect32 }],
  0x01b2: [{ type: NormalizedOpcode.AoeEffect8 }],
  0x01c6: [{ type: NormalizedOpcode.BossStatusEffectList }],
  0x01ce: [{ type: NormalizedOpcode.ActorCast }],
  0x01db: [{ type: NormalizedOpcode.PlayerStats }],
  0x0248: [{ type: NormalizedOpcode.UpdateHpMpTp }],
  0x0265: [{ type: NormalizedOpcode.PlayerSpawn }],
  0x0276: [{ type: NormalizedOpcode.NpcSpawn }],
  0x0295: [{ type: NormalizedOpcode.ActorControlSelf }],
  0x02d0: [{ type: NormalizedOpcode.ActorGauge }],
  0x0315: [{ type: NormalizedOpcode.InitZone }],
  0x031b: [{ type: NormalizedOpcode.ActorSetPos }],
  0x032f: [{ type: NormalizedOpcode.WardLandInfo }],
  0x033b: [{ type: NormalizedOpcode.AoeEffect16 }],
  0x035d: [{ type: NormalizedOpcode.AoeEffect24 }],
  0x038b: [{ type: NormalizedOpcode.StatusEffectList }],
  0x03b2: [{ type: NormalizedOpcode.UpdateClassInfo }],
}
