// Generated by src/sync/index.ts

// biome-ignore-all lint/complexity/useSimpleNumberKeys: opcode maps are easier to audit in hexadecimal
import { NormalizedOpcode } from './normalized-opcode.enum'
import type { OpcodeMap } from './opcode-map.type'

export const CN_6_15: OpcodeMap = {
  0x0068: [{ type: NormalizedOpcode.PlayerSpawn }],
  0x00c3: [{ type: NormalizedOpcode.AoeEffect16 }],
  0x00e2: [{ type: NormalizedOpcode.BossStatusEffectList }],
  0x00ef: [{ type: NormalizedOpcode.AoeEffect8 }],
  0x011a: [{ type: NormalizedOpcode.ActorSetPos }],
  0x012c: [{ type: NormalizedOpcode.ActorControlSelf }],
  0x012e: [{ type: NormalizedOpcode.InitZone }],
  0x015d: [{ type: NormalizedOpcode.NpcSpawn }],
  0x0164: [{ type: NormalizedOpcode.PlayerStats }],
  0x01d4: [{ type: NormalizedOpcode.ActorControl }],
  0x01f8: [{ type: NormalizedOpcode.UpdateHpMpTp }],
  0x0205: [{ type: NormalizedOpcode.PlayerSetup }],
  0x020a: [{ type: NormalizedOpcode.NpcSpawn2 }],
  0x021e: [{ type: NormalizedOpcode.ActorMove }],
  0x0228: [{ type: NormalizedOpcode.Effect }],
  0x02b2: [{ type: NormalizedOpcode.AoeEffect32 }],
  0x02de: [{ type: NormalizedOpcode.StatusEffectList }],
  0x02e5: [{ type: NormalizedOpcode.ActorCast }],
  0x02fe: [{ type: NormalizedOpcode.WardLandInfo }],
  0x03bf: [{ type: NormalizedOpcode.AoeEffect24 }],
  0x03c6: [{ type: NormalizedOpcode.ActorGauge }],
  0x03d6: [{ type: NormalizedOpcode.UpdateClassInfo }],
}
