// Generated by src/sync/index.ts

import { OpcodeMap } from './opcode-map.type'
import { NormalizedOpcode } from './normalized-opcode.enum'

export const CN_6_45a: OpcodeMap = {
  0x00b4: [{ type: NormalizedOpcode.AoeEffect24, outgoing: false }],
  0x00f2: [{ type: NormalizedOpcode.PlayerStats, outgoing: false }],
  0x00ff: [{ type: NormalizedOpcode.Effect, outgoing: false }],
  0x0103: [{ type: NormalizedOpcode.ActorMove, outgoing: false }],
  0x016b: [{ type: NormalizedOpcode.BossStatusEffectList, outgoing: false }],
  0x017f: [{ type: NormalizedOpcode.ActorCast, outgoing: false }],
  0x018d: [{ type: NormalizedOpcode.InitZone, outgoing: false }],
  0x01c1: [{ type: NormalizedOpcode.NpcSpawn2, outgoing: false }],
  0x01ec: [{ type: NormalizedOpcode.UpdateClassInfo, outgoing: false }],
  0x0208: [{ type: NormalizedOpcode.AoeEffect32, outgoing: false }],
  0x0283: [{ type: NormalizedOpcode.PlayerSetup, outgoing: false }],
  0x028d: [{ type: NormalizedOpcode.WardLandInfo, outgoing: false }],
  0x029f: [{ type: NormalizedOpcode.ActorSetPos, outgoing: false }],
  0x02b1: [{ type: NormalizedOpcode.AoeEffect16, outgoing: false }],
  0x02c3: [{ type: NormalizedOpcode.ActorControl, outgoing: false }],
  0x0302: [{ type: NormalizedOpcode.ActorControlSelf, outgoing: false }],
  0x032b: [{ type: NormalizedOpcode.AoeEffect8, outgoing: false }],
  0x032e: [{ type: NormalizedOpcode.ActorGauge, outgoing: false }],
  0x0393: [{ type: NormalizedOpcode.NpcSpawn, outgoing: false }],
  0x039b: [{ type: NormalizedOpcode.PlayerSpawn, outgoing: false }],
  0x03b6: [{ type: NormalizedOpcode.ActorFreeSpawn, outgoing: false }],
  0x03d5: [{ type: NormalizedOpcode.UpdateHpMpTp, outgoing: false }],
  0x03e0: [{ type: NormalizedOpcode.StatusEffectList, outgoing: false }],
}
