// Generated by src/sync/index.ts

import { OpcodeMap } from './opcode-map.type'
import { NormalizedOpcode } from './normalized-opcode.enum'

export const CN_6_35: OpcodeMap = {
  0x00b1: [{ type: NormalizedOpcode.BossStatusEffectList, outgoing: false }],
  0x00c8: [{ type: NormalizedOpcode.PlayerSpawn, outgoing: false }],
  0x00c9: [{ type: NormalizedOpcode.ActorGauge, outgoing: false }],
  0x00cd: [{ type: NormalizedOpcode.Effect, outgoing: false }],
  0x013e: [{ type: NormalizedOpcode.NpcSpawn2, outgoing: false }],
  0x0149: [{ type: NormalizedOpcode.StatusEffectList, outgoing: false }],
  0x017d: [{ type: NormalizedOpcode.PlayerStats, outgoing: false }],
  0x0184: [{ type: NormalizedOpcode.ActorCast, outgoing: false }],
  0x018c: [{ type: NormalizedOpcode.AoeEffect32, outgoing: false }],
  0x01a3: [{ type: NormalizedOpcode.ActorControlSelf, outgoing: false }],
  0x01e3: [{ type: NormalizedOpcode.InitZone, outgoing: false }],
  0x0215: [{ type: NormalizedOpcode.AoeEffect8, outgoing: false }],
  0x0247: [{ type: NormalizedOpcode.UpdateHpMpTp, outgoing: false }],
  0x024e: [{ type: NormalizedOpcode.ActorSetPos, outgoing: false }],
  0x0252: [{ type: NormalizedOpcode.AoeEffect16, outgoing: false }],
  0x0271: [{ type: NormalizedOpcode.AoeEffect24, outgoing: false }],
  0x028c: [{ type: NormalizedOpcode.UpdateClassInfo, outgoing: false }],
  0x029f: [{ type: NormalizedOpcode.WardLandInfo, outgoing: false }],
  0x02a5: [{ type: NormalizedOpcode.ActorControl, outgoing: false }],
  0x0366: [{ type: NormalizedOpcode.NpcSpawn, outgoing: false }],
  0x038e: [{ type: NormalizedOpcode.ActorMove, outgoing: false }],
  0x03a8: [{ type: NormalizedOpcode.PlayerSetup, outgoing: false }],
  0x03df: [{ type: NormalizedOpcode.ActorFreeSpawn, outgoing: false }],
}
