// Generated by src/sync/index.ts

// biome-ignore-all lint/complexity/useSimpleNumberKeys: opcode maps are easier to audit in hexadecimal
import { NormalizedOpcode } from './normalized-opcode.enum'
import type { OpcodeMap } from './opcode-map.type'

export const CN_6_5: OpcodeMap = {
  0x0065: [{ type: NormalizedOpcode.PlayerSpawn }],
  0x00a2: [{ type: NormalizedOpcode.InitZone }],
  0x00db: [{ type: NormalizedOpcode.ActorControlSelf }],
  0x00ef: [{ type: NormalizedOpcode.AoeEffect8 }],
  0x00f0: [{ type: NormalizedOpcode.ActorCast }],
  0x010f: [{ type: NormalizedOpcode.UpdateClassInfo }],
  0x0160: [{ type: NormalizedOpcode.AoeEffect32 }],
  0x0172: [{ type: NormalizedOpcode.WardLandInfo }],
  0x0173: [{ type: NormalizedOpcode.NpcSpawn2 }],
  0x0181: [{ type: NormalizedOpcode.ActorControl }],
  0x01dc: [{ type: NormalizedOpcode.ActorFreeSpawn }],
  0x01e3: [{ type: NormalizedOpcode.AoeEffect16 }],
  0x0220: [{ type: NormalizedOpcode.BossStatusEffectList }],
  0x0223: [{ type: NormalizedOpcode.ActorMove }],
  0x02aa: [{ type: NormalizedOpcode.PlayerStats }],
  0x02ae: [{ type: NormalizedOpcode.NpcSpawn }],
  0x02c0: [{ type: NormalizedOpcode.UpdateHpMpTp }],
  0x030d: [{ type: NormalizedOpcode.PlayerSetup }],
  0x0318: [{ type: NormalizedOpcode.ActorSetPos }],
  0x0323: [{ type: NormalizedOpcode.AoeEffect24 }],
  0x0329: [{ type: NormalizedOpcode.Effect }],
  0x0356: [{ type: NormalizedOpcode.StatusEffectList }],
  0x03c1: [{ type: NormalizedOpcode.ActorGauge }],
}
