// Generated by src/sync/index.ts

// biome-ignore-all lint/complexity/useSimpleNumberKeys: opcode maps are easier to audit in hexadecimal
import { NormalizedOpcode } from './normalized-opcode.enum'
import type { OpcodeMap } from './opcode-map.type'

export const CN_6_1: OpcodeMap = {
  0x0084: [{ type: NormalizedOpcode.PlayerStats }],
  0x00c0: [{ type: NormalizedOpcode.Effect }],
  0x00df: [{ type: NormalizedOpcode.ActorGauge }],
  0x0106: [{ type: NormalizedOpcode.PlayerSpawn }],
  0x010c: [{ type: NormalizedOpcode.ActorControlSelf }],
  0x0114: [{ type: NormalizedOpcode.AoeEffect24 }],
  0x013e: [{ type: NormalizedOpcode.NpcSpawn2 }],
  0x0142: [{ type: NormalizedOpcode.PlayerSetup }],
  0x0154: [{ type: NormalizedOpcode.ActorCast }],
  0x0169: [{ type: NormalizedOpcode.ActorSetPos }],
  0x017a: [{ type: NormalizedOpcode.BossStatusEffectList }],
  0x0211: [{ type: NormalizedOpcode.UpdateClassInfo }],
  0x0218: [{ type: NormalizedOpcode.AoeEffect32 }],
  0x022c: [{ type: NormalizedOpcode.ActorControl }],
  0x028b: [{ type: NormalizedOpcode.UpdateHpMpTp }],
  0x02b9: [{ type: NormalizedOpcode.AoeEffect16 }],
  0x02c2: [{ type: NormalizedOpcode.AoeEffect8 }],
  0x02dc: [{ type: NormalizedOpcode.ActorMove }],
  0x035e: [{ type: NormalizedOpcode.WardLandInfo }],
  0x0370: [{ type: NormalizedOpcode.StatusEffectList }],
  0x03a7: [{ type: NormalizedOpcode.NpcSpawn }],
  0x03cc: [{ type: NormalizedOpcode.InitZone }],
}
