// Generated by src/sync/index.ts

import { OpcodeMap } from './opcode-map.type'
import { NormalizedOpcode } from './normalized-opcode.enum'

export const CN_6_2: OpcodeMap = {
  0x009b: [{ type: NormalizedOpcode.PlayerStats, outgoing: false }],
  0x0113: [{ type: NormalizedOpcode.NpcSpawn2, outgoing: false }],
  0x011d: [{ type: NormalizedOpcode.NpcSpawn, outgoing: false }],
  0x0121: [{ type: NormalizedOpcode.UpdateHpMpTp, outgoing: false }],
  0x0186: [{ type: NormalizedOpcode.ActorCast, outgoing: false }],
  0x0199: [{ type: NormalizedOpcode.AoeEffect8, outgoing: false }],
  0x01c4: [{ type: NormalizedOpcode.ActorSetPos, outgoing: false }],
  0x01e2: [{ type: NormalizedOpcode.AoeEffect16, outgoing: false }],
  0x01fe: [{ type: NormalizedOpcode.StatusEffectList, outgoing: false }],
  0x0217: [{ type: NormalizedOpcode.PlayerSetup, outgoing: false }],
  0x0245: [{ type: NormalizedOpcode.ActorControlSelf, outgoing: false }],
  0x02b6: [{ type: NormalizedOpcode.PlayerSpawn, outgoing: false }],
  0x02ca: [{ type: NormalizedOpcode.BossStatusEffectList, outgoing: false }],
  0x02f8: [{ type: NormalizedOpcode.WardLandInfo, outgoing: false }],
  0x030f: [{ type: NormalizedOpcode.Effect, outgoing: false }],
  0x034b: [{ type: NormalizedOpcode.ActorGauge, outgoing: false }],
  0x0356: [{ type: NormalizedOpcode.InitZone, outgoing: false }],
  0x0365: [{ type: NormalizedOpcode.ActorControl, outgoing: false }],
  0x037e: [{ type: NormalizedOpcode.AoeEffect32, outgoing: false }],
  0x0386: [{ type: NormalizedOpcode.UpdateClassInfo, outgoing: false }],
  0x03b1: [{ type: NormalizedOpcode.ActorMove, outgoing: false }],
  0x03b6: [{ type: NormalizedOpcode.AoeEffect24, outgoing: false }],
}
