// Generated by src/sync/index.ts

// biome-ignore-all lint/complexity/useSimpleNumberKeys: opcode maps are easier to audit in hexadecimal
import { NormalizedOpcode } from './normalized-opcode.enum'
import type { OpcodeMap } from './opcode-map.type'

export const CN_7_0: OpcodeMap = {
  0x0065: [{ type: NormalizedOpcode.ActorControl }],
  0x008b: [{ type: NormalizedOpcode.UpdateClassInfo }],
  0x0093: [{ type: NormalizedOpcode.InitZone }],
  0x009b: [{ type: NormalizedOpcode.ActorCast }],
  0x00a1: [{ type: NormalizedOpcode.PlayerSpawn }],
  0x010a: [{ type: NormalizedOpcode.ActorGauge }],
  0x011d: [{ type: NormalizedOpcode.AoeEffect16 }],
  0x0127: [{ type: NormalizedOpcode.ActorControlSelf }],
  0x0164: [{ type: NormalizedOpcode.WardLandInfo }],
  0x016e: [{ type: NormalizedOpcode.NpcSpawn2 }],
  0x01b1: [{ type: NormalizedOpcode.PlayerSetup }],
  0x01d1: [{ type: NormalizedOpcode.ActorSetPos }],
  0x01d9: [{ type: NormalizedOpcode.StatusEffectList }],
  0x01eb: [{ type: NormalizedOpcode.BossStatusEffectList }],
  0x0260: [{ type: NormalizedOpcode.AoeEffect8 }],
  0x027f: [{ type: NormalizedOpcode.UpdateHpMpTp }],
  0x02a0: [{ type: NormalizedOpcode.ActorMove }],
  0x02f4: [{ type: NormalizedOpcode.Effect }],
  0x032f: [{ type: NormalizedOpcode.NpcSpawn }],
  0x0351: [{ type: NormalizedOpcode.ActorFreeSpawn }],
  0x0377: [{ type: NormalizedOpcode.PlayerStats }],
  0x03a0: [{ type: NormalizedOpcode.AoeEffect24 }],
  0x03b0: [{ type: NormalizedOpcode.AoeEffect32 }],
}
