// Generated by src/sync/index.ts

// biome-ignore-all lint/complexity/useSimpleNumberKeys: opcode maps are easier to audit in hexadecimal
import { NormalizedOpcode } from './normalized-opcode.enum'
import type { OpcodeMap } from './opcode-map.type'

export const CN_7_51: OpcodeMap = {
  0x007d: [{ type: NormalizedOpcode.UpdateClassInfo }],
  0x0096: [{ type: NormalizedOpcode.InitZone }],
  0x00a7: [{ type: NormalizedOpcode.AoeEffect16 }],
  0x00d3: [{ type: NormalizedOpcode.AoeEffect8 }],
  0x00de: [{ type: NormalizedOpcode.UpdateHpMpTp }],
  0x0147: [{ type: NormalizedOpcode.AoeEffect24 }],
  0x0153: [{ type: NormalizedOpcode.WardLandInfo }],
  0x01c9: [{ type: NormalizedOpcode.ActorControlSelf }],
  0x01e8: [{ type: NormalizedOpcode.ActorControl }],
  0x0204: [{ type: NormalizedOpcode.ActorGauge }],
  0x023f: [{ type: NormalizedOpcode.PlayerSetup }],
  0x0242: [{ type: NormalizedOpcode.NpcSpawn2 }],
  0x0255: [{ type: NormalizedOpcode.PlayerSpawn }],
  0x026b: [{ type: NormalizedOpcode.NpcSpawn }],
  0x028f: [{ type: NormalizedOpcode.ActorSetPos }],
  0x0295: [{ type: NormalizedOpcode.StatusEffectList }],
  0x02db: [{ type: NormalizedOpcode.PlayerStats }],
  0x02dd: [{ type: NormalizedOpcode.ActorFreeSpawn }],
  0x02f6: [{ type: NormalizedOpcode.ActorCast }],
  0x0346: [{ type: NormalizedOpcode.BossStatusEffectList }],
  0x0393: [{ type: NormalizedOpcode.Effect }],
  0x03b6: [{ type: NormalizedOpcode.ActorMove }],
  0x03d1: [{ type: NormalizedOpcode.AoeEffect32 }],
}
