// Generated by src/sync/index.ts

// biome-ignore-all lint/complexity/useSimpleNumberKeys: opcode maps are easier to audit in hexadecimal
import { NormalizedOpcode } from './normalized-opcode.enum'
import type { OpcodeMap } from './opcode-map.type'

export const CN_7_4b: OpcodeMap = {
  0x009c: [{ type: NormalizedOpcode.ActorGauge }],
  0x00a0: [{ type: NormalizedOpcode.UpdateClassInfo }],
  0x00ca: [{ type: NormalizedOpcode.PlayerSpawn }],
  0x014f: [{ type: NormalizedOpcode.WardLandInfo }],
  0x0168: [{ type: NormalizedOpcode.BossStatusEffectList }],
  0x0195: [{ type: NormalizedOpcode.ActorFreeSpawn }],
  0x019b: [{ type: NormalizedOpcode.ActorControl }],
  0x01cc: [{ type: NormalizedOpcode.ActorSetPos }],
  0x01d0: [{ type: NormalizedOpcode.NpcSpawn2 }],
  0x01e1: [{ type: NormalizedOpcode.PlayerStats }],
  0x020d: [{ type: NormalizedOpcode.AoeEffect8 }],
  0x022f: [{ type: NormalizedOpcode.AoeEffect32 }],
  0x0231: [{ type: NormalizedOpcode.AoeEffect16 }],
  0x0242: [{ type: NormalizedOpcode.InitZone }],
  0x0253: [{ type: NormalizedOpcode.StatusEffectList }],
  0x0256: [{ type: NormalizedOpcode.PlayerSetup }],
  0x0261: [{ type: NormalizedOpcode.AoeEffect24 }],
  0x02d4: [{ type: NormalizedOpcode.ActorMove }],
  0x02f2: [{ type: NormalizedOpcode.ActorCast }],
  0x0347: [{ type: NormalizedOpcode.ActorControlSelf }],
  0x0363: [{ type: NormalizedOpcode.UpdateHpMpTp }],
  0x039b: [{ type: NormalizedOpcode.NpcSpawn }],
  0x03d8: [{ type: NormalizedOpcode.Effect }],
}
