// Generated by src/sync/index.ts

// biome-ignore-all lint/complexity/useSimpleNumberKeys: opcode maps are easier to audit in hexadecimal
import { NormalizedOpcode } from './normalized-opcode.enum'
import type { OpcodeMap } from './opcode-map.type'

export const CN_7_51a: OpcodeMap = {
  0x0084: [{ type: NormalizedOpcode.WardLandInfo }],
  0x008b: [{ type: NormalizedOpcode.InitZone }],
  0x00b8: [{ type: NormalizedOpcode.NpcSpawn2 }],
  0x00bd: [{ type: NormalizedOpcode.ActorGauge }],
  0x0113: [{ type: NormalizedOpcode.NpcSpawn }],
  0x0117: [{ type: NormalizedOpcode.PlayerStats }],
  0x012b: [{ type: NormalizedOpcode.StatusEffectList }],
  0x0131: [{ type: NormalizedOpcode.ActorSetPos }],
  0x0141: [{ type: NormalizedOpcode.AoeEffect8 }],
  0x0191: [{ type: NormalizedOpcode.AoeEffect16 }],
  0x01d9: [{ type: NormalizedOpcode.Effect }],
  0x027f: [{ type: NormalizedOpcode.ActorControl }],
  0x02f8: [{ type: NormalizedOpcode.ActorCast }],
  0x0362: [{ type: NormalizedOpcode.ActorControlSelf }],
  0x0366: [{ type: NormalizedOpcode.ActorMove }],
  0x037d: [{ type: NormalizedOpcode.ActorFreeSpawn }],
  0x038b: [{ type: NormalizedOpcode.AoeEffect32 }],
  0x0394: [{ type: NormalizedOpcode.UpdateHpMpTp }],
  0x03a8: [{ type: NormalizedOpcode.PlayerSetup }],
  0x03ac: [{ type: NormalizedOpcode.UpdateClassInfo }],
  0x03b4: [{ type: NormalizedOpcode.PlayerSpawn }],
  0x03e5: [{ type: NormalizedOpcode.BossStatusEffectList }],
  0x231a: [{ type: NormalizedOpcode.AoeEffect24 }],
}
