// Generated by src/sync/index.ts

// biome-ignore-all lint/complexity/useSimpleNumberKeys: opcode maps are easier to audit in hexadecimal
import { NormalizedOpcode } from './normalized-opcode.enum'
import type { OpcodeMap } from './opcode-map.type'

export const CN_7_4: OpcodeMap = {
  0x0074: [{ type: NormalizedOpcode.ActorGauge }],
  0x00c1: [{ type: NormalizedOpcode.Effect }],
  0x00d8: [{ type: NormalizedOpcode.ActorControl }],
  0x011e: [{ type: NormalizedOpcode.NpcSpawn }],
  0x0120: [{ type: NormalizedOpcode.AoeEffect32 }],
  0x012e: [{ type: NormalizedOpcode.InitZone }],
  0x0167: [{ type: NormalizedOpcode.UpdateHpMpTp }],
  0x018b: [{ type: NormalizedOpcode.PlayerSpawn }],
  0x01f8: [{ type: NormalizedOpcode.ActorSetPos }],
  0x0243: [{ type: NormalizedOpcode.AoeEffect24 }],
  0x025c: [{ type: NormalizedOpcode.ActorFreeSpawn }],
  0x0266: [{ type: NormalizedOpcode.ActorMove }],
  0x02bd: [{ type: NormalizedOpcode.NpcSpawn2 }],
  0x02bf: [{ type: NormalizedOpcode.PlayerStats }],
  0x0318: [{ type: NormalizedOpcode.WardLandInfo }],
  0x0324: [{ type: NormalizedOpcode.AoeEffect16 }],
  0x0331: [{ type: NormalizedOpcode.BossStatusEffectList }],
  0x036f: [{ type: NormalizedOpcode.PlayerSetup }],
  0x0379: [{ type: NormalizedOpcode.UpdateClassInfo }],
  0x0385: [{ type: NormalizedOpcode.ActorCast }],
  0x038a: [{ type: NormalizedOpcode.ActorControlSelf }],
  0x03d6: [{ type: NormalizedOpcode.AoeEffect8 }],
  0x03d7: [{ type: NormalizedOpcode.StatusEffectList }],
}
