// Names in cn-opcodes.csv take precedence over community aliases.
// Additional names follow existing local definitions, then Sapphire/Dalamud.
export const packetAliases: Record<string, string> = {
  MapUpdate: 'MapMarker2',
  MapUpdate4: 'MapMarker4',
  MapUpdate8: 'MapMarker8',
  MapUpdate16: 'MapMarker16',
  MapUpdate32: 'MapMarker32',
  MapUpdate64: 'MapMarker64',
  MapUpdate128: 'MapMarker128',

  AirshipTimers: 'CompanyAirshipStatus',
  SubmarineTimers: 'CompanySubmersibleStatus',
  CFNotify: 'ContentFinderNotifyPop',
  DesynthResult: 'ResumeEventScene16',
  ResultDialog: 'ResumeEventScene8',
  MiniCactpotInit: 'ResumeEventScene32',
  HousingWardInfo: 'WardLandInfo',
  BossSpawn: 'NpcSpawn2',
  DespawnCharacter: 'ActorFreeSpawn',
  Countdown: 'CountdownInitiate',
  EnvironmentControl4: 'MapEffect4',
  EnvironmentControl8: 'MapEffect8',
  EnvironmentControl12: 'MapEffect12',
  StatusEffectListBozja: 'StatusEffectList2',
  StatusEffectListDouble: 'BossStatusEffectList',
  StatusEffectListEureka: 'EurekaStatusEffectList',
  StatusEffectListOccult: 'StatusEffectListForay3',
  StatusEffectListPlayer: 'StatusEffectList3',
  RSVData: 'RSV',
  RSFData: 'RSF',
  SystemLogMessage2: 'SystemLogMessage32',
  SystemLogMessage4: 'SystemLogMessage48',
  SystemLogMessage8: 'SystemLogMessage80',
  SystemLogMessage16: 'SystemLogMessage144',
  CFDutyInfo: 'ContentFinderDutyInfo',
  UpdateRecastTimes: 'RecastGroup',
  UpdateHate: 'HateList',
  UpdateHater: 'HaterList',
  ObjectDespawn: 'DeleteObject',
  PlayerClassInfo: 'ChangeClass',
  BlackList: 'GetBlacklistResult',
  PlayerTitleList: 'TitleList',
}

export function canonicalPacketName(name: string): string {
  if (name === 'InventoryHandlerOffset') return 'InventoryModifyHandler'
  return packetAliases[name] ?? name
}

export function normalizeOpcodeTable(table: Record<string, string>) {
  const normalized: Record<string, string> = {}
  for (const [name, opcode] of Object.entries(table)) {
    const canonical = canonicalPacketName(name)
    const previous = normalized[canonical]
    if (previous && Number(previous) !== Number(opcode)) {
      throw new Error(
        `Conflicting opcodes for ${canonical}: ${previous} and ${opcode}`,
      )
    }
    normalized[canonical] = opcode
  }
  return normalized
}

// Direction from cn-opcodes.csv Scope; omitted where the source is unspecified.
export const packetDirections: Record<string, boolean> = {
  ActorCast: false,
  ActorControl: false,
  ActorControlSelf: false,
  ActorControlTarget: false,
  ActorFreeSpawn: false,
  ActorGauge: false,
  ActorMove: false,
  ActorSetPos: false,
  AirshipExplorationResult: false,
  AirshipStatus: false,
  AirshipStatusList: false,
  AoeEffect16: false,
  AoeEffect24: false,
  AoeEffect32: false,
  AoeEffect8: false,
  BattleTalk2: false,
  BossStatusEffectList: false,
  CEDirector: false,
  CFPreferredRole: false,
  ChatHandler: true,
  ClientTrigger: true,
  CompanyAirshipStatus: false,
  CompanySubmersibleStatus: false,
  ContainerInfo: false,
  ContentFinderNotifyPop: false,
  CountdownInitiate: false,
  CountdownCancel: false,
  CurrencyCrystalInfo: false,
  Effect: false,
  EffectResult: false,
  EnvironmentControl: false,
  EventFinish: false,
  EventPlay: false,
  EventPlay32: false,
  EventPlay64: false,
  EventPlay4: false,
  EventStart: false,
  Examine: false,
  ExamineSearchInfo: false,
  FateInfo: false,
  FreeCompanyDialog: false,
  FreeCompanyInfo: false,
  InitZone: false,
  InventoryActionAck: false,
  InventoryHandlerOffset: true,
  InventoryModifyHandler: true,
  InventoryTransaction: false,
  InventoryTransactionFinish: false,
  IslandWorkshopSupplyDemand: false,
  ItemInfo: false,
  ItemMarketBoardInfo: false,
  Logout: false,
  MarketBoardItemListing: false,
  MarketBoardItemListingCount: false,
  MarketBoardItemListingHistory: false,
  MarketBoardPurchase: false,
  MarketBoardPurchaseHandler: true,
  MarketBoardRequestItemListingInfo: true,
  MarketBoardSearchResult: false,
  NpcSpawn: false,
  NpcSpawn2: false,
  NpcYell: false,
  ObjectSpawn: false,
  PlaceFieldMarker: false,
  PlaceFieldMarkerPreset: false,
  PlayerSetup: false,
  PlayerSpawn: false,
  PlayerStats: false,
  Playtime: false,
  PrepareZoning: false,
  ResumeEventScene16: false,
  ResumeEventScene32: false,
  ResumeEventScene8: false,
  RetainerInformation: false,
  RSV: false,
  SetSearchInfoHandler: true,
  StatusEffectList: false,
  StatusEffectList2: false,
  StatusEffectList3: false,
  SubmarineExplorationResult: false,
  SubmarineProgressionStatus: false,
  SubmarineStatusList: false,
  SystemLogMessage: false,
  UpdateClassInfo: false,
  UpdateHpMpTp: false,
  UpdateInventorySlot: false,
  UpdatePositionHandler: true,
  UpdatePositionInstance: true,
  UpdateSearchInfo: false,
  WardLandInfo: false,
  WeatherChange: false,
  WorldVisitQueue: false,
  MapEffect4: false,
  MapEffect8: false,
  MapEffect12: false,
  StatusEffectListForay3: false,
  ActionRequest: true,
  ActionRequestGroundTargeted: true,
  ClientCountdownInitiate: true,
  LogoutHandler: true,
  ClientVersionInfo: true,
  ReqCharCreate: true,
  ReqCharDelete: true,
  ReqCharList: true,
  ReqEnterWorld: true,
}
