import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

export const codePath = join(__dirname, '..')

const biomeFormatCommand =
  process.platform === 'win32'
    ? ['cmd.exe', '/c', 'pnpm', 'exec', 'biome', 'check', '--write']
    : ['pnpm', 'exec', 'biome', 'check', '--write']

export function formatCode(path: string) {
  console.log('[format]', path)
  const [command, ...args] = biomeFormatCommand
  return execFileSync(command, [...args, join(codePath, path)], {
    encoding: 'utf-8',
  })
}

export async function writeCode(path: string, content: string) {
  const contentWithBanner = `// Generated by src/sync/index.ts\n\n${content}`
  writeFileSync(join(codePath, path), contentWithBanner)
}
