import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { camelCase, kebabCase, snakeCase } from 'change-case'
import { format, type Options, resolveConfig } from 'prettier'

export const root = join(__dirname, '../../../..')
export const networkSrc = join(__dirname, '..')

export { snakeCase, kebabCase, camelCase }

let prettierOptions: Options | null = null
export async function writeCode(path: string, content: string) {
  if (prettierOptions === null) {
    prettierOptions = (await resolveConfig(__dirname)) || {}
    prettierOptions.parser = 'babel-ts'
  }

  const contentWithBanner = '// Generated by network:generate\n\n' + content
  writeFileSync(
    join(networkSrc, path),
    await format(contentWithBanner, prettierOptions),
  )
}
