-- This file is generated by network:generate

local ffxiv_ipc_gathering_log = Proto("ffxiv_ipc_gathering_log", "FFXIV-IPC GatheringLog")

local gathering_log_fields = {
  gathered_item_flags = ProtoField.bytes("ffxiv_ipc_gathering_log.gathered_item_flags", "gatheredItemFlags", base.NONE),
}

ffxiv_ipc_gathering_log.fields = gathering_log_fields

function ffxiv_ipc_gathering_log.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_gathering_log, tvbuf)
  local len = tvbuf:len()
  if len < 104 then
    tree:add_expert_info(PI_MALFORMED, PI_ERROR, "Truncated GatheringLog payload")
    return len
  end

  -- dissect the gathered_item_flags field
  local gathered_item_flags_tvbr = tvbuf:range(0, 104)
  local gathered_item_flags_val  = gathered_item_flags_tvbr:raw()
  tree:add(gathering_log_fields.gathered_item_flags, gathered_item_flags_tvbr, gathered_item_flags_val)

  return len
end
