-- This file is generated by network:generate

local ffxiv_ipc_market_board_item_listing_count = Proto("ffxiv_ipc_market_board_item_listing_count", "FFXIV-IPC MarketBoardItemListingCount")

local market_board_item_listing_count_fields = {
  status   = ProtoField.uint32("ffxiv_ipc_market_board_item_listing_count.status", "status", base.DEC),
  quantity = ProtoField.uint32("ffxiv_ipc_market_board_item_listing_count.quantity", "quantity", base.DEC),
}

ffxiv_ipc_market_board_item_listing_count.fields = market_board_item_listing_count_fields

function ffxiv_ipc_market_board_item_listing_count.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_market_board_item_listing_count, tvbuf)
  local len = tvbuf:len()

  -- dissect the status field
  local status_tvbr = tvbuf:range(0, 4)
  local status_val  = status_tvbr:le_uint()
  tree:add_le(market_board_item_listing_count_fields.status, status_tvbr, status_val)

  -- dissect the quantity field
  local quantity_tvbr = tvbuf:range(4, 4)
  local quantity_val  = quantity_tvbr:le_uint()
  tree:add_le(market_board_item_listing_count_fields.quantity, quantity_tvbr, quantity_val)

  return len
end
