-- This file is generated by tools/json2lua.js

local M = {}
M.types = {
  ActorControl143 = 0x0143,
  ActorMove = 0x0182,
  Character = 0x0180,
  CompanyBoard = 0x0150,
  CompanyInfo = 0x0151,
  ContentFinderNotify = 0x0078,
  FishEvent = 0x01b5,
  GroupMessage = 0x0065,
  InventoryActionAck = 0x01A7,
  InventoryTransaction = 0x01A4,
  InventoryTransactionFinish = 0x01A3,
  MatchEvent = 0x0078,
  PublicMessage = 0x0104,
  UpdateHpMpTp = 0x0145,
  UpdateInventorySlot = 0x01A8,
  ItemInfo = 0x01A1,
}

function M.getDissector(type)
  if type == M.types.ActorControl143 then
    return Dissector.get('ffxiv_ipc_actor_control143')
  elseif type == M.types.ActorMove then
    return Dissector.get('ffxiv_ipc_actor_move')
  elseif type == M.types.Character then
    return Dissector.get('ffxiv_ipc_character')
  elseif type == M.types.CompanyBoard then
    return Dissector.get('ffxiv_ipc_company_board')
  elseif type == M.types.CompanyInfo then
    return Dissector.get('ffxiv_ipc_company_info')
  elseif type == M.types.ContentFinderNotify then
    return Dissector.get('ffxiv_ipc_content_finder_notify')
  elseif type == M.types.FishEvent then
    return Dissector.get('ffxiv_ipc_fish_event')
  elseif type == M.types.GroupMessage then
    return Dissector.get('ffxiv_ipc_group_message')
  elseif type == M.types.InventoryActionAck then
    return Dissector.get('ffxiv_ipc_inventory_action_ack')
  elseif type == M.types.InventoryTransaction then
    return Dissector.get('ffxiv_ipc_inventory_transaction')
  elseif type == M.types.InventoryTransactionFinish then
    return Dissector.get('ffxiv_ipc_inventory_transaction_finish')
  elseif type == M.types.MatchEvent then
    return Dissector.get('ffxiv_ipc_match_event')
  elseif type == M.types.PublicMessage then
    return Dissector.get('ffxiv_ipc_public_message')
  elseif type == M.types.UpdateHpMpTp then
    return Dissector.get('ffxiv_ipc_update_hp_mp_tp')
  elseif type == M.types.UpdateInventorySlot then
    return Dissector.get('ffxiv_ipc_update_inventory_slot')
  elseif type == M.types.ItemInfo then
    return Dissector.get('ffxiv_ipc_item_info')
  else
    return nil
  end
end

return M
