-- This file is generated by network:generate

local M = {}
M.types = {
  [0x009a] = {
    [0] = {
      name = "ffxiv_ipc_inventory_action_ack",
      length = 16,
    },
  },
  [0x00a7] = {
    [0] = {
      name = "ffxiv_ipc_player_stats",
      length = 120,
    },
  },
  [0x00bb] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect24",
      length = 1784,
    },
  },
  [0x011e] = {
    [0] = {
      name = "ffxiv_ipc_inventory_transaction",
      length = 36,
    },
  },
  [0x013c] = {
    [0] = {
      name = "ffxiv_ipc_init_zone",
      length = 96,
    },
  },
  [0x0146] = {
    [0] = {
      name = "ffxiv_ipc_actor_cast",
      length = 30,
    },
  },
  [0x0158] = {
    [0] = {
      name = "ffxiv_ipc_actor_set_pos",
      length = 20,
    },
  },
  [0x0165] = {
    [0] = {
      name = "ffxiv_ipc_boss_status_effect_list",
      length = 740,
    },
    [1] = {
      name = "ffxiv_ipc_status_effect_list",
      length = 380,
    },
  },
  [0x0168] = {
    [0] = {
      name = "ffxiv_ipc_company_airship_status",
      length = 0,
    },
  },
  [0x0174] = {
    [0] = {
      name = "ffxiv_ipc_examine",
      length = 656,
    },
  },
  [0x0179] = {
    [0] = {
      name = "ffxiv_ipc_retainer_information",
      length = 73,
    },
  },
  [0x01b8] = {
    [0] = {
      name = "ffxiv_ipc_update_class_info",
      length = 16,
    },
  },
  [0x01f0] = {
    [0] = {
      name = "ffxiv_ipc_inventory_transaction_finish",
      length = 16,
    },
  },
  [0x0202] = {
    [0] = {
      name = "ffxiv_ipc_actor_move",
      length = 12,
    },
  },
  [0x0204] = {
    [0] = {
      name = "ffxiv_ipc_client_trigger",
      length = 32,
    },
  },
  [0x0211] = {
    [0] = {
      name = "ffxiv_ipc_npc_spawn",
      length = 624,
    },
  },
  [0x021f] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect16",
      length = 1208,
    },
  },
  [0x0229] = {
    [0] = {
      name = "ffxiv_ipc_actor_control",
      length = 24,
    },
  },
  [0x0237] = {
    [0] = {
      name = "ffxiv_ipc_update_hp_mp_tp",
      length = 8,
    },
  },
  [0x025e] = {
    [0] = {
      name = "ffxiv_ipc_actor_control_self",
      length = 32,
    },
  },
  [0x029f] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect32",
      length = 2360,
    },
  },
  [0x02d0] = {
    [0] = {
      name = "ffxiv_ipc_effect_result",
      length = 26,
    },
  },
  [0x02dd] = {
    [0] = {
      name = "ffxiv_ipc_player_setup",
      length = 1938,
    },
  },
  [0x02eb] = {
    [0] = {
      name = "ffxiv_ipc_container_info",
      length = 16,
    },
  },
  [0x02f0] = {
    [0] = {
      name = "ffxiv_ipc_item_info",
      length = 64,
    },
  },
  [0x0306] = {
    [0] = {
      name = "ffxiv_ipc_company_submersible_status",
      length = 0,
    },
  },
  [0x034a] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect8",
      length = 632,
    },
  },
  [0x034f] = {
    [0] = {
      name = "ffxiv_ipc_content_finder_notify_pop",
      length = 32,
    },
  },
  [0x035e] = {
    [0] = {
      name = "ffxiv_ipc_effect",
      length = 120,
    },
  },
  [0x036a] = {
    [0] = {
      name = "ffxiv_ipc_actor_gauge",
      length = 16,
    },
  },
  [0x0375] = {
    [0] = {
      name = "ffxiv_ipc_currency_crystal_info",
      length = 32,
    },
  },
  [0x03a0] = {
    [0] = {
      name = "ffxiv_ipc_player_spawn",
      length = 624,
    },
  },
  [0x03c8] = {
    [0] = {
      name = "ffxiv_ipc_update_inventory_slot",
      length = 64,
    },
  },
  [0x03c9] = {
    [0] = {
      name = "ffxiv_ipc_npc_spawn2",
      length = 624,
    },
  },
}

function M.getDissector(typeNum, length)
  local types = M.types[typeNum]
  if type(types) ~= "table" then
    return nil
  end

  for k, v in pairs(types) do
    if v.length == length then
      return Dissector.get(v.name)
    end
  end

  for k, v in pairs(types) do
    if v.length < length then
      return Dissector.get(v.name)
    end
  end

  return nil
end

return M
