-- This file is generated by network:generate

local ffxiv_ipc_fellowship_note_item = Proto("ffxiv_ipc_fellowship_note_item", "FFXIV-IPC FellowshipNoteItem")

local fellowship_note_item_fields = {
  content = ProtoField.string("ffxiv_ipc_fellowship_note_item.content", "Content", base.UNICODE),
}

ffxiv_ipc_fellowship_note_item.fields = fellowship_note_item_fields

function ffxiv_ipc_fellowship_note_item.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_fellowship_note_item, tvbuf)
  local len = tvbuf:len()

  -- dissect the content field
  local content_tvbr = tvbuf:range(0, 97)
  local content_val  = content_tvbr:string(ENC_UTF_8)
  tree:add(fellowship_note_item_fields.content, content_tvbr, content_val)

  return len
end
