-- This file is generated by network:generate

local resolver = require("ffxiv_ipc_resolver")
local M = {}
M.types = {
  [0x006b] = {
    [0] = {
      type = "WeatherChange",
    },
  },
  [0x0080] = {
    [0] = {
      type = "Logout",
    },
  },
  [0x0085] = {
    [0] = {
      type = "CountdownInitiate",
    },
  },
  [0x008d] = {
    [0] = {
      type = "SetSearchInfoHandler",
    },
  },
  [0x00b1] = {
    [0] = {
      type = "ClientTrigger",
    },
  },
  [0x00b5] = {
    [0] = {
      type = "EventPlay32",
    },
  },
  [0x00bb] = {
    [0] = {
      type = "AirshipStatusList",
    },
  },
  [0x00c1] = {
    [0] = {
      type = "CurrencyCrystalInfo",
    },
  },
  [0x00c4] = {
    [0] = {
      type = "ItemInfo",
    },
  },
  [0x00cf] = {
    [0] = {
      type = "RSV",
    },
  },
  [0x00d3] = {
    [0] = {
      type = "EventFinish",
    },
  },
  [0x00de] = {
    [0] = {
      type = "RetainerInformation",
    },
  },
  [0x00e1] = {
    [0] = {
      type = "Effect",
    },
  },
  [0x00f0] = {
    [0] = {
      type = "CFPreferredRole",
    },
  },
  [0x0104] = {
    [0] = {
      type = "ItemMarketBoardInfo",
    },
  },
  [0x010f] = {
    [0] = {
      type = "InitZone",
    },
  },
  [0x0112] = {
    [0] = {
      type = "ExamineSearchInfo",
    },
  },
  [0x0114] = {
    [0] = {
      type = "ContentFinderNotifyPop",
    },
  },
  [0x011a] = {
    [0] = {
      type = "UpdateSearchInfo",
    },
  },
  [0x011b] = {
    [0] = {
      type = "MarketBoardItemListingCount",
    },
  },
  [0x0121] = {
    [0] = {
      type = "AirshipExplorationResult",
    },
  },
  [0x0128] = {
    [0] = {
      type = "ActorControlTarget",
    },
  },
  [0x0134] = {
    [0] = {
      type = "PlaceFieldMarkerPreset",
    },
  },
  [0x0138] = {
    [0] = {
      type = "PlayerStats",
    },
  },
  [0x013e] = {
    [0] = {
      type = "EventPlay",
    },
  },
  [0x013f] = {
    [0] = {
      type = "ResumeEventScene16",
    },
  },
  [0x0159] = {
    [0] = {
      type = "PlaceFieldMarker",
    },
  },
  [0x015c] = {
    [0] = {
      type = "StatusEffectList3",
    },
  },
  [0x016a] = {
    [0] = {
      type = "MarketBoardItemListingHistory",
    },
  },
  [0x0176] = {
    [0] = {
      type = "CEDirector",
    },
  },
  [0x0180] = {
    [0] = {
      type = "MarketBoardPurchase",
    },
  },
  [0x0186] = {
    [0] = {
      type = "ActorCast",
    },
  },
  [0x0189] = {
    [0] = {
      type = "FreeCompanyDialog",
    },
  },
  [0x018e] = {
    [0] = {
      type = "ActorControl",
    },
  },
  [0x0194] = {
    [0] = {
      type = "NpcSpawn2",
    },
  },
  [0x0195] = {
    [0] = {
      type = "AoeEffect8",
    },
  },
  [0x0197] = {
    [0] = {
      type = "NpcSpawn",
    },
  },
  [0x01ae] = {
    [0] = {
      type = "NpcYell",
    },
  },
  [0x01af] = {
    [0] = {
      type = "ActorSetPos",
    },
  },
  [0x01bd] = {
    [0] = {
      type = "AirshipStatus",
    },
  },
  [0x01c3] = {
    [0] = {
      type = "InventoryTransaction",
    },
  },
  [0x01c5] = {
    [0] = {
      type = "CompanySubmersibleStatus",
    },
  },
  [0x01e8] = {
    [0] = {
      type = "WardLandInfo",
    },
  },
  [0x01e9] = {
    [0] = {
      type = "EffectResult",
    },
  },
  [0x01ef] = {
    [0] = {
      type = "BattleTalk2",
    },
  },
  [0x01ff] = {
    [0] = {
      type = "MarketBoardRequestItemListingInfo",
    },
  },
  [0x0204] = {
    [0] = {
      type = "MarketBoardSearchResult",
    },
  },
  [0x021b] = {
    [0] = {
      type = "SubmarineStatusList",
    },
  },
  [0x022a] = {
    [0] = {
      type = "ActorMove",
    },
  },
  [0x022c] = {
    [0] = {
      type = "InventoryHandlerOffset",
    },
    [1] = {
      type = "InventoryModifyHandler",
    },
  },
  [0x0234] = {
    [0] = {
      type = "SubmarineExplorationResult",
    },
  },
  [0x0240] = {
    [0] = {
      type = "CompanyAirshipStatus",
    },
  },
  [0x024e] = {
    [0] = {
      type = "ActorFreeSpawn",
    },
  },
  [0x0254] = {
    [0] = {
      type = "InventoryTransactionFinish",
    },
  },
  [0x0259] = {
    [0] = {
      type = "Examine",
    },
  },
  [0x0266] = {
    [0] = {
      type = "StatusEffectList2",
    },
  },
  [0x0268] = {
    [0] = {
      type = "EventStart",
    },
  },
  [0x0277] = {
    [0] = {
      type = "UpdateHpMpTp",
    },
  },
  [0x028d] = {
    [0] = {
      type = "AoeEffect32",
    },
  },
  [0x02a0] = {
    [0] = {
      type = "EffectResultBasic",
    },
  },
  [0x02a2] = {
    [0] = {
      type = "UpdateInventorySlot",
    },
  },
  [0x02a5] = {
    [0] = {
      type = "UpdatePositionInstance",
    },
  },
  [0x02a7] = {
    [0] = {
      type = "PrepareZoning",
    },
  },
  [0x02ae] = {
    [0] = {
      type = "ChatHandler",
    },
  },
  [0x02c1] = {
    [0] = {
      type = "FateInfo",
    },
  },
  [0x02c6] = {
    [0] = {
      type = "PlayerSpawn",
    },
  },
  [0x02ce] = {
    [0] = {
      type = "UpdatePositionHandler",
    },
  },
  [0x02d9] = {
    [0] = {
      type = "Playtime",
    },
  },
  [0x02df] = {
    [0] = {
      type = "ActorControlSelf",
    },
  },
  [0x02e8] = {
    [0] = {
      type = "AoeEffect24",
    },
  },
  [0x02e9] = {
    [0] = {
      type = "IslandWorkshopSupplyDemand",
    },
  },
  [0x02ea] = {
    [0] = {
      type = "ContainerInfo",
    },
  },
  [0x02f4] = {
    [0] = {
      type = "EnvironmentControl",
    },
  },
  [0x02f5] = {
    [0] = {
      type = "ObjectSpawn",
    },
  },
  [0x02f9] = {
    [0] = {
      type = "AoeEffect16",
    },
  },
  [0x0303] = {
    [0] = {
      type = "SystemLogMessage",
    },
  },
  [0x0313] = {
    [0] = {
      type = "MarketBoardItemListing",
    },
  },
  [0x0317] = {
    [0] = {
      type = "FreeCompanyInfo",
    },
  },
  [0x0332] = {
    [0] = {
      type = "MarketBoardPurchaseHandler",
    },
  },
  [0x033b] = {
    [0] = {
      type = "PlayerSetup",
    },
  },
  [0x0356] = {
    [0] = {
      type = "InventoryActionAck",
    },
  },
  [0x035d] = {
    [0] = {
      type = "EventPlay4",
    },
  },
  [0x0368] = {
    [0] = {
      type = "SubmarineProgressionStatus",
    },
  },
  [0x0391] = {
    [0] = {
      type = "WorldVisitQueue",
    },
  },
  [0x0398] = {
    [0] = {
      type = "CountdownCancel",
    },
  },
  [0x039d] = {
    [0] = {
      type = "BossStatusEffectList",
    },
  },
  [0x03a2] = {
    [0] = {
      type = "UpdateClassInfo",
    },
  },
  [0x03b1] = {
    [0] = {
      type = "StatusEffectList",
    },
  },
  [0x03b7] = {
    [0] = {
      type = "ActorGauge",
    },
  },
  [0x03e1] = {
    [0] = {
      type = "ResumeEventScene32",
    },
  },
}

function M.getDissector(typeNum, length, direction)
  return resolver.getDissector(M.types[typeNum], length, direction)
end

return M
