-- This file is generated by network:generate

local M = {}
M.types = {
  [0x006f] = {
    [0] = {
      name = "ffxiv_ipc_update_hp_mp_tp",
      length = 8,
    },
  },
  [0x007a] = {
    [0] = {
      name = "ffxiv_ipc_fate_info",
      length = 24,
    },
  },
  [0x0083] = {
    [0] = {
      name = "ffxiv_ipc_object_spawn",
      length = 64,
    },
  },
  [0x00b1] = {
    [0] = {
      name = "ffxiv_ipc_client_trigger",
      length = 32,
    },
  },
  [0x00c6] = {
    [0] = {
      name = "ffxiv_ipc_ward_land_info",
      length = 2408,
    },
  },
  [0x00d5] = {
    [0] = {
      name = "ffxiv_ipc_update_position_instance",
      length = 40,
    },
  },
  [0x00e4] = {
    [0] = {
      name = "ffxiv_ipc_actor_control",
      length = 24,
    },
  },
  [0x0104] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect24",
      length = 1784,
    },
  },
  [0x0112] = {
    [0] = {
      name = "ffxiv_ipc_company_submersible_status",
      length = 0,
    },
  },
  [0x0125] = {
    [0] = {
      name = "ffxiv_ipc_actor_control_self",
      length = 32,
    },
  },
  [0x0139] = {
    [0] = {
      name = "ffxiv_ipc_boss_status_effect_list",
      length = 740,
    },
  },
  [0x0152] = {
    [0] = {
      name = "ffxiv_ipc_currency_crystal_info",
      length = 32,
    },
  },
  [0x0166] = {
    [0] = {
      name = "ffxiv_ipc_actor_cast",
      length = 30,
    },
  },
  [0x0185] = {
    [0] = {
      name = "ffxiv_ipc_actor_set_pos",
      length = 20,
    },
  },
  [0x0192] = {
    [0] = {
      name = "ffxiv_ipc_npc_spawn2",
      length = 624,
    },
  },
  [0x0195] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect16",
      length = 1208,
    },
  },
  [0x0199] = {
    [0] = {
      name = "ffxiv_ipc_inventory_transaction_finish",
      length = 16,
    },
  },
  [0x019a] = {
    [0] = {
      name = "ffxiv_ipc_ce_director",
      length = 16,
    },
  },
  [0x01a5] = {
    [0] = {
      name = "ffxiv_ipc_company_airship_status",
      length = 0,
    },
  },
  [0x01b9] = {
    [0] = {
      name = "ffxiv_ipc_inventory_transaction",
      length = 36,
    },
  },
  [0x01c6] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect8",
      length = 632,
    },
  },
  [0x01ce] = {
    [0] = {
      name = "ffxiv_ipc_update_inventory_slot",
      length = 64,
    },
  },
  [0x01e4] = {
    [0] = {
      name = "ffxiv_ipc_retainer_information",
      length = 73,
    },
  },
  [0x01f4] = {
    [0] = {
      name = "ffxiv_ipc_submarine_status_list",
      length = 240,
    },
  },
  [0x021b] = {
    [0] = {
      name = "ffxiv_ipc_content_finder_notify_pop",
      length = 32,
    },
  },
  [0x0220] = {
    [0] = {
      name = "ffxiv_ipc_player_spawn",
      length = 624,
    },
  },
  [0x0251] = {
    [0] = {
      name = "ffxiv_ipc_container_info",
      length = 16,
    },
  },
  [0x0255] = {
    [0] = {
      name = "ffxiv_ipc_item_info",
      length = 64,
    },
  },
  [0x026f] = {
    [0] = {
      name = "ffxiv_ipc_init_zone",
      length = 96,
    },
  },
  [0x0292] = {
    [0] = {
      name = "ffxiv_ipc_actor_control_target",
      length = 32,
    },
  },
  [0x0295] = {
    [0] = {
      name = "ffxiv_ipc_effect_result",
      length = 26,
    },
  },
  [0x02ad] = {
    [0] = {
      name = "ffxiv_ipc_effect",
      length = 120,
    },
  },
  [0x02b6] = {
    [0] = {
      name = "ffxiv_ipc_update_class_info",
      length = 16,
    },
  },
  [0x02fd] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect32",
      length = 2360,
    },
  },
  [0x031e] = {
    [0] = {
      name = "ffxiv_ipc_player_stats",
      length = 120,
    },
  },
  [0x0348] = {
    [0] = {
      name = "ffxiv_ipc_status_effect_list",
      length = 380,
    },
  },
  [0x0349] = {
    [0] = {
      name = "ffxiv_ipc_npc_spawn",
      length = 624,
    },
  },
  [0x0369] = {
    [0] = {
      name = "ffxiv_ipc_actor_move",
      length = 12,
    },
  },
  [0x036d] = {
    [0] = {
      name = "ffxiv_ipc_player_setup",
      length = 1938,
    },
  },
  [0x0382] = {
    [0] = {
      name = "ffxiv_ipc_examine",
      length = 656,
    },
  },
  [0x0388] = {
    [0] = {
      name = "ffxiv_ipc_actor_gauge",
      length = 16,
    },
  },
  [0x03ba] = {
    [0] = {
      name = "ffxiv_ipc_inventory_action_ack",
      length = 16,
    },
  },
}

function M.getDissector(typeNum, length)
  local types = M.types[typeNum]
  if type(types) ~= "table" then
    return nil
  end

  for k, v in pairs(types) do
    if v.length == length then
      return Dissector.get(v.name)
    end
  end

  for k, v in pairs(types) do
    if v.length < length then
      return Dissector.get(v.name)
    end
  end

  return nil
end

return M
