-- This file is generated by network:generate

local M = {}
M.types = {
  [0x00a4] = {
    [0] = {
      title = "CFPreferredRole",
    },
  },
  [0x00b4] = {
    [0] = {
      title = "BossStatusEffectList",
      name = "ffxiv_ipc_boss_status_effect_list",
      length = 740,
    },
    [1] = {
      title = "StatusEffectList",
      name = "ffxiv_ipc_status_effect_list",
      length = 380,
    },
  },
  [0x00bd] = {
    [0] = {
      title = "Examine",
      name = "ffxiv_ipc_examine",
      length = 656,
    },
  },
  [0x00be] = {
    [0] = {
      title = "MarketBoardItemListingCount",
      name = "ffxiv_ipc_market_board_item_listing_count",
      length = 8,
    },
  },
  [0x00ff] = {
    [0] = {
      title = "AoeEffect32",
      name = "ffxiv_ipc_aoe_effect32",
      length = 2360,
    },
  },
  [0x0105] = {
    [0] = {
      title = "Playtime",
      name = "ffxiv_ipc_playtime",
      length = 4,
    },
  },
  [0x010e] = {
    [0] = {
      title = "EventStart",
      name = "ffxiv_ipc_event_start",
      length = 12,
    },
  },
  [0x011e] = {
    [0] = {
      title = "RetainerInformation",
      name = "ffxiv_ipc_retainer_information",
      length = 73,
    },
  },
  [0x0128] = {
    [0] = {
      title = "NpcSpawn2",
      name = "ffxiv_ipc_npc_spawn2",
      length = 624,
    },
  },
  [0x0131] = {
    [0] = {
      title = "CurrencyCrystalInfo",
      name = "ffxiv_ipc_currency_crystal_info",
      length = 32,
    },
  },
  [0x0139] = {
    [0] = {
      title = "AoeEffect16",
      name = "ffxiv_ipc_aoe_effect16",
      length = 1208,
    },
  },
  [0x013c] = {
    [0] = {
      title = "UpdateInventorySlot",
      name = "ffxiv_ipc_update_inventory_slot",
      length = 64,
    },
  },
  [0x016d] = {
    [0] = {
      title = "ContentFinderNotifyPop",
      name = "ffxiv_ipc_content_finder_notify_pop",
      length = 32,
    },
  },
  [0x0179] = {
    [0] = {
      title = "ActorControlSelf",
      name = "ffxiv_ipc_actor_control_self",
      length = 32,
    },
  },
  [0x0184] = {
    [0] = {
      title = "NpcSpawn",
      name = "ffxiv_ipc_npc_spawn",
      length = 624,
    },
  },
  [0x01b1] = {
    [0] = {
      title = "AoeEffect8",
      name = "ffxiv_ipc_aoe_effect8",
      length = 632,
    },
  },
  [0x01b9] = {
    [0] = {
      title = "EventFinish",
      name = "ffxiv_ipc_event_finish",
      length = 4,
    },
  },
  [0x0202] = {
    [0] = {
      title = "InventoryTransaction",
      name = "ffxiv_ipc_inventory_transaction",
      length = 36,
    },
  },
  [0x0214] = {
    [0] = {
      title = "EventPlay4",
      name = "ffxiv_ipc_event_play4",
      length = 44,
    },
  },
  [0x0216] = {
    [0] = {
      title = "EventPlay",
      name = "ffxiv_ipc_event_play",
      length = 32,
    },
  },
  [0x021b] = {
    [0] = {
      title = "ResumeEventScene32",
    },
  },
  [0x0236] = {
    [0] = {
      title = "ExamineSearchInfo",
    },
  },
  [0x0237] = {
    [0] = {
      title = "EffectResult",
      name = "ffxiv_ipc_effect_result",
      length = 42,
    },
  },
  [0x023b] = {
    [0] = {
      title = "SetSearchInfoHandler",
    },
  },
  [0x023e] = {
    [0] = {
      title = "Effect",
      name = "ffxiv_ipc_effect",
      length = 120,
    },
  },
  [0x0251] = {
    [0] = {
      title = "MarketBoardSearchResult",
      name = "ffxiv_ipc_market_board_search_result",
      length = 176,
    },
  },
  [0x025f] = {
    [0] = {
      title = "ClientTrigger",
      name = "ffxiv_ipc_client_trigger",
      length = 32,
    },
  },
  [0x0261] = {
    [0] = {
      title = "ActorSetPos",
      name = "ffxiv_ipc_actor_set_pos",
      length = 20,
    },
  },
  [0x0268] = {
    [0] = {
      title = "ItemInfo",
      name = "ffxiv_ipc_item_info",
      length = 64,
    },
  },
  [0x028a] = {
    [0] = {
      title = "ContainerInfo",
      name = "ffxiv_ipc_container_info",
      length = 16,
    },
  },
  [0x029d] = {
    [0] = {
      title = "PlayerSpawn",
      name = "ffxiv_ipc_player_spawn",
      length = 624,
    },
  },
  [0x02b4] = {
    [0] = {
      title = "MarketBoardItemListingHistory",
      name = "ffxiv_ipc_market_board_item_listing_history",
      length = 964,
    },
  },
  [0x02be] = {
    [0] = {
      title = "SystemLogMessage",
      name = "ffxiv_ipc_system_log_message",
      length = 24,
    },
  },
  [0x02c5] = {
    [0] = {
      title = "ChatHandler",
    },
  },
  [0x0311] = {
    [0] = {
      title = "UpdateSearchInfo",
    },
  },
  [0x032c] = {
    [0] = {
      title = "ActorCast",
      name = "ffxiv_ipc_actor_cast",
      length = 30,
    },
  },
  [0x0345] = {
    [0] = {
      title = "InitZone",
      name = "ffxiv_ipc_init_zone",
      length = 96,
    },
  },
  [0x034a] = {
    [0] = {
      title = "UpdateHpMpTp",
      name = "ffxiv_ipc_update_hp_mp_tp",
      length = 8,
    },
  },
  [0x0350] = {
    [0] = {
      title = "ActorGauge",
      name = "ffxiv_ipc_actor_gauge",
      length = 16,
    },
  },
  [0x0366] = {
    [0] = {
      title = "ActorControl",
      name = "ffxiv_ipc_actor_control",
      length = 24,
    },
  },
  [0x0376] = {
    [0] = {
      title = "PlayerSetup",
      name = "ffxiv_ipc_player_setup",
      length = 1938,
    },
  },
  [0x0378] = {
    [0] = {
      title = "InventoryTransactionFinish",
      name = "ffxiv_ipc_inventory_transaction_finish",
      length = 16,
    },
  },
  [0x038b] = {
    [0] = {
      title = "AoeEffect24",
      name = "ffxiv_ipc_aoe_effect24",
      length = 1784,
    },
  },
  [0x038f] = {
    [0] = {
      title = "InventoryModifyHandler",
      name = "ffxiv_ipc_inventory_modify_handler",
      length = 44,
    },
  },
  [0x0399] = {
    [0] = {
      title = "StatusEffectList2",
    },
  },
  [0x039e] = {
    [0] = {
      title = "ActorMove",
      name = "ffxiv_ipc_actor_move",
      length = 12,
    },
  },
  [0x03c5] = {
    [0] = {
      title = "UpdateClassInfo",
      name = "ffxiv_ipc_update_class_info",
      length = 16,
    },
  },
  [0x03cb] = {
    [0] = {
      title = "MarketBoardItemListing",
      name = "ffxiv_ipc_market_board_item_listing",
      length = 1444,
    },
  },
}

function M.getDissector(typeNum, length)
  local types = M.types[typeNum]
  if type(types) ~= "table" then
    return nil
  end

  local title = nil
  if types[0] ~= nil then
    title = types[0].title
  end

  for k, v in pairs(types) do
    if v.name ~= nil and v.length ~= nil and v.length == length then
      return Dissector.get(v.name), v.title
    end
  end

  for k, v in pairs(types) do
    if v.name ~= nil and v.length ~= nil and v.length < length then
      return Dissector.get(v.name), v.title
    end
  end

  return nil, title
end

return M
