-- This file is generated by network:generate

local M = {}
M.types = {
  [0x0066] = {
    [0] = {
      title = "ActorMove",
      name = "ffxiv_ipc_actor_move",
      length = 12,
    },
  },
  [0x006b] = {
    [0] = {
      title = "AirshipExplorationResult",
      name = "ffxiv_ipc_airship_exploration_result",
      length = 284,
    },
  },
  [0x0070] = {
    [0] = {
      title = "ChatHandler",
    },
  },
  [0x0077] = {
    [0] = {
      title = "ActorControlSelf",
      name = "ffxiv_ipc_actor_control_self",
      length = 32,
    },
  },
  [0x007b] = {
    [0] = {
      title = "Playtime",
      name = "ffxiv_ipc_playtime",
      length = 4,
    },
  },
  [0x007d] = {
    [0] = {
      title = "ClientTrigger",
      name = "ffxiv_ipc_client_trigger",
      length = 32,
    },
  },
  [0x007f] = {
    [0] = {
      title = "ActorControlTarget",
      name = "ffxiv_ipc_actor_control_target",
      length = 32,
    },
  },
  [0x0082] = {
    [0] = {
      title = "PlayerSpawn",
      name = "ffxiv_ipc_player_spawn",
      length = 624,
    },
  },
  [0x0097] = {
    [0] = {
      title = "MarketBoardPurchaseHandler",
      name = "ffxiv_ipc_market_board_purchase_handler",
      length = 28,
    },
  },
  [0x009b] = {
    [0] = {
      title = "ActorSetPos",
      name = "ffxiv_ipc_actor_set_pos",
      length = 20,
    },
  },
  [0x009e] = {
    [0] = {
      title = "CEDirector",
      name = "ffxiv_ipc_ce_director",
      length = 16,
    },
  },
  [0x00bb] = {
    [0] = {
      title = "UpdateInventorySlot",
      name = "ffxiv_ipc_update_inventory_slot",
      length = 64,
    },
  },
  [0x00d7] = {
    [0] = {
      title = "UpdatePositionInstance",
      name = "ffxiv_ipc_update_position_instance",
      length = 40,
    },
  },
  [0x00d8] = {
    [0] = {
      title = "SubmarineExplorationResult",
      name = "ffxiv_ipc_submarine_exploration_result",
      length = 288,
    },
  },
  [0x00d9] = {
    [0] = {
      title = "InventoryModifyHandler",
      name = "ffxiv_ipc_inventory_modify_handler",
      length = 44,
    },
  },
  [0x00dd] = {
    [0] = {
      title = "NpcSpawn",
      name = "ffxiv_ipc_npc_spawn",
      length = 624,
    },
  },
  [0x0117] = {
    [0] = {
      title = "CurrencyCrystalInfo",
      name = "ffxiv_ipc_currency_crystal_info",
      length = 32,
    },
  },
  [0x011c] = {
    [0] = {
      title = "MarketBoardPurchase",
      name = "ffxiv_ipc_market_board_purchase",
      length = 12,
    },
  },
  [0x0131] = {
    [0] = {
      title = "ActorFreeSpawn",
      name = "ffxiv_ipc_actor_free_spawn",
      length = 8,
    },
  },
  [0x0136] = {
    [0] = {
      title = "ActorGauge",
      name = "ffxiv_ipc_actor_gauge",
      length = 16,
    },
  },
  [0x0138] = {
    [0] = {
      title = "UpdateSearchInfo",
    },
  },
  [0x015b] = {
    [0] = {
      title = "RetainerInformation",
      name = "ffxiv_ipc_retainer_information",
      length = 73,
    },
  },
  [0x016a] = {
    [0] = {
      title = "AirshipStatusList",
      name = "ffxiv_ipc_airship_status_list",
      length = 158,
    },
  },
  [0x016c] = {
    [0] = {
      title = "ContainerInfo",
      name = "ffxiv_ipc_container_info",
      length = 16,
    },
  },
  [0x0177] = {
    [0] = {
      title = "StatusEffectList",
      name = "ffxiv_ipc_status_effect_list",
      length = 380,
    },
  },
  [0x0180] = {
    [0] = {
      title = "PrepareZoning",
      name = "ffxiv_ipc_prepare_zoning",
      length = 16,
    },
  },
  [0x01a5] = {
    [0] = {
      title = "InventoryTransaction",
      name = "ffxiv_ipc_inventory_transaction",
      length = 36,
    },
  },
  [0x01b4] = {
    [0] = {
      title = "Examine",
      name = "ffxiv_ipc_examine",
      length = 656,
    },
  },
  [0x01c3] = {
    [0] = {
      title = "MarketBoardItemListingCount",
      name = "ffxiv_ipc_market_board_item_listing_count",
      length = 8,
    },
  },
  [0x01c4] = {
    [0] = {
      title = "EventPlay4",
      name = "ffxiv_ipc_event_play4",
      length = 44,
    },
  },
  [0x01ca] = {
    [0] = {
      title = "SubmarineStatusList",
      name = "ffxiv_ipc_submarine_status_list",
      length = 240,
    },
  },
  [0x0203] = {
    [0] = {
      title = "ResumeEventScene32",
    },
  },
  [0x020b] = {
    [0] = {
      title = "AoeEffect24",
      name = "ffxiv_ipc_aoe_effect24",
      length = 1784,
    },
  },
  [0x0212] = {
    [0] = {
      title = "EffectResult",
      name = "ffxiv_ipc_effect_result",
      length = 42,
    },
  },
  [0x021b] = {
    [0] = {
      title = "PlayerStats",
      name = "ffxiv_ipc_player_stats",
      length = 120,
    },
  },
  [0x0231] = {
    [0] = {
      title = "ContentFinderNotifyPop",
      name = "ffxiv_ipc_content_finder_notify_pop",
      length = 32,
    },
  },
  [0x023a] = {
    [0] = {
      title = "InventoryTransactionFinish",
      name = "ffxiv_ipc_inventory_transaction_finish",
      length = 16,
    },
  },
  [0x0240] = {
    [0] = {
      title = "Effect",
      name = "ffxiv_ipc_effect",
      length = 120,
    },
  },
  [0x0257] = {
    [0] = {
      title = "SystemLogMessage",
      name = "ffxiv_ipc_system_log_message",
      length = 16,
    },
  },
  [0x0262] = {
    [0] = {
      title = "ObjectSpawn",
      name = "ffxiv_ipc_object_spawn",
      length = 64,
    },
    [1] = {
      title = "UpdateHpMpTp",
      name = "ffxiv_ipc_update_hp_mp_tp",
      length = 8,
    },
  },
  [0x0272] = {
    [0] = {
      title = "MarketBoardItemListing",
      name = "ffxiv_ipc_market_board_item_listing",
      length = 1444,
    },
  },
  [0x027b] = {
    [0] = {
      title = "CompanyAirshipStatus",
      name = "ffxiv_ipc_company_airship_status",
      length = 144,
    },
  },
  [0x0293] = {
    [0] = {
      title = "ExamineSearchInfo",
    },
  },
  [0x029a] = {
    [0] = {
      title = "CFPreferredRole",
    },
  },
  [0x02c1] = {
    [0] = {
      title = "PlayerSetup",
      name = "ffxiv_ipc_player_setup",
      length = 1938,
    },
  },
  [0x02d2] = {
    [0] = {
      title = "Logout",
      name = "ffxiv_ipc_logout",
      length = 8,
    },
  },
  [0x02de] = {
    [0] = {
      title = "SubmarineProgressionStatus",
      name = "ffxiv_ipc_submarine_progression_status",
      length = 31,
    },
  },
  [0x02f3] = {
    [0] = {
      title = "SetSearchInfoHandler",
    },
  },
  [0x0307] = {
    [0] = {
      title = "InitZone",
      name = "ffxiv_ipc_init_zone",
      length = 96,
    },
  },
  [0x0308] = {
    [0] = {
      title = "AirshipStatus",
      name = "ffxiv_ipc_airship_status",
      length = 72,
    },
  },
  [0x0322] = {
    [0] = {
      title = "ItemInfo",
      name = "ffxiv_ipc_item_info",
      length = 64,
    },
  },
  [0x0325] = {
    [0] = {
      title = "MarketBoardItemListingHistory",
      name = "ffxiv_ipc_market_board_item_listing_history",
      length = 964,
    },
  },
  [0x0326] = {
    [0] = {
      title = "UpdatePositionHandler",
      name = "ffxiv_ipc_update_position_handler",
      length = 20,
    },
  },
  [0x034c] = {
    [0] = {
      title = "EventStart",
      name = "ffxiv_ipc_event_start",
      length = 12,
    },
  },
  [0x0353] = {
    [0] = {
      title = "AoeEffect32",
      name = "ffxiv_ipc_aoe_effect32",
      length = 2360,
    },
  },
  [0x035a] = {
    [0] = {
      title = "EventPlay",
      name = "ffxiv_ipc_event_play",
      length = 32,
    },
  },
  [0x035b] = {
    [0] = {
      title = "AoeEffect16",
      name = "ffxiv_ipc_aoe_effect16",
      length = 1208,
    },
  },
  [0x0360] = {
    [0] = {
      title = "ResumeEventScene16",
    },
  },
  [0x036c] = {
    [0] = {
      title = "UpdateClassInfo",
      name = "ffxiv_ipc_update_class_info",
      length = 16,
    },
  },
  [0x036f] = {
    [0] = {
      title = "InventoryActionAck",
      name = "ffxiv_ipc_inventory_action_ack",
      length = 16,
    },
  },
  [0x0376] = {
    [0] = {
      title = "AoeEffect8",
      name = "ffxiv_ipc_aoe_effect8",
      length = 632,
    },
  },
  [0x037e] = {
    [0] = {
      title = "WardLandInfo",
      name = "ffxiv_ipc_ward_land_info",
      length = 2408,
    },
  },
  [0x0392] = {
    [0] = {
      title = "ActorCast",
      name = "ffxiv_ipc_actor_cast",
      length = 30,
    },
  },
  [0x0398] = {
    [0] = {
      title = "MarketBoardSearchResult",
      name = "ffxiv_ipc_market_board_search_result",
      length = 176,
    },
  },
  [0x0399] = {
    [0] = {
      title = "CompanySubmersibleStatus",
      name = "ffxiv_ipc_company_submersible_status",
      length = 144,
    },
  },
  [0x03a5] = {
    [0] = {
      title = "FreeCompanyDialog",
      name = "ffxiv_ipc_free_company_dialog",
      length = 79,
    },
  },
  [0x03a8] = {
    [0] = {
      title = "PlaceFieldMarker",
      name = "ffxiv_ipc_place_field_marker",
      length = 16,
    },
  },
  [0x03c3] = {
    [0] = {
      title = "ActorControl",
      name = "ffxiv_ipc_actor_control",
      length = 24,
    },
    [1] = {
      title = "EventFinish",
      name = "ffxiv_ipc_event_finish",
      length = 4,
    },
  },
  [0x03d4] = {
    [0] = {
      title = "FreeCompanyInfo",
      name = "ffxiv_ipc_free_company_info",
      length = 80,
    },
  },
  [0x03d5] = {
    [0] = {
      title = "PlaceFieldMarkerPreset",
    },
  },
}

function M.getDissector(typeNum, length)
  local types = M.types[typeNum]
  if type(types) ~= "table" then
    return nil
  end

  local title = nil
  if types[0] ~= nil then
    title = types[0].title
  end

  for k, v in pairs(types) do
    if v.name ~= nil and v.length ~= nil and v.length == length then
      return Dissector.get(v.name), v.title
    end
  end

  for k, v in pairs(types) do
    if v.name ~= nil and v.length ~= nil and v.length < length then
      return Dissector.get(v.name), v.title
    end
  end

  return nil, title
end

return M
