-- This file is generated by network:generate

local ffxiv_ipc_logout = Proto("ffxiv_ipc_logout", "FFXIV-IPC Logout")

local logout_fields = {
  flags1 = ProtoField.uint32("ffxiv_ipc_logout.flags1", "flags1", base.DEC),
  flags2 = ProtoField.uint32("ffxiv_ipc_logout.flags2", "flags2", base.DEC),
}

ffxiv_ipc_logout.fields = logout_fields

function ffxiv_ipc_logout.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_logout, tvbuf)
  local len = tvbuf:len()

  -- dissect the flags1 field
  local flags1_tvbr = tvbuf:range(0, 4)
  local flags1_val  = flags1_tvbr:le_uint()
  tree:add_le(logout_fields.flags1, flags1_tvbr, flags1_val)

  -- dissect the flags2 field
  local flags2_tvbr = tvbuf:range(4, 4)
  local flags2_val  = flags2_tvbr:le_uint()
  tree:add_le(logout_fields.flags2, flags2_tvbr, flags2_val)

  return len
end
