-- This file is generated by network:generate

local resolver = require("ffxiv_ipc_resolver")
local M = {}
M.types = {
  [0x006f] = {
    [0] = {
      type = "UpdateClassInfo",
    },
  },
  [0x0085] = {
    [0] = {
      type = "Effect",
    },
  },
  [0x0086] = {
    [0] = {
      type = "FreeCompanyDialog",
    },
  },
  [0x008b] = {
    [0] = {
      type = "ActorControl",
    },
  },
  [0x009e] = {
    [0] = {
      type = "SubmarineProgressionStatus",
    },
  },
  [0x00a5] = {
    [0] = {
      type = "AirshipExplorationResult",
    },
  },
  [0x00be] = {
    [0] = {
      type = "SystemLogMessage",
    },
  },
  [0x00c9] = {
    [0] = {
      type = "InventoryTransactionFinish",
    },
  },
  [0x00d8] = {
    [0] = {
      type = "MarketBoardItemListingCount",
    },
  },
  [0x00e9] = {
    [0] = {
      type = "UpdateSearchInfo",
    },
  },
  [0x00ee] = {
    [0] = {
      type = "ContentFinderNotifyPop",
    },
  },
  [0x00f0] = {
    [0] = {
      type = "NpcSpawn",
    },
  },
  [0x00f1] = {
    [0] = {
      type = "EventPlay4",
    },
  },
  [0x00f2] = {
    [0] = {
      type = "SubmarineStatusList",
    },
  },
  [0x00ff] = {
    [0] = {
      type = "AoeEffect8",
    },
  },
  [0x0106] = {
    [0] = {
      type = "AirshipStatusList",
    },
  },
  [0x0110] = {
    [0] = {
      type = "AoeEffect16",
    },
    [1] = {
      type = "EventFinish",
    },
  },
  [0x0113] = {
    [0] = {
      type = "PlaceFieldMarker",
    },
  },
  [0x0141] = {
    [0] = {
      type = "WardLandInfo",
    },
  },
  [0x0149] = {
    [0] = {
      type = "ContainerInfo",
    },
  },
  [0x014d] = {
    [0] = {
      type = "EventPlay",
    },
  },
  [0x0171] = {
    [0] = {
      type = "CompanyAirshipStatus",
    },
  },
  [0x018a] = {
    [0] = {
      type = "MarketBoardSearchResult",
    },
  },
  [0x0190] = {
    [0] = {
      type = "ActorControlSelf",
    },
  },
  [0x019c] = {
    [0] = {
      type = "RetainerInformation",
    },
  },
  [0x01ac] = {
    [0] = {
      type = "UpdateHpMpTp",
    },
  },
  [0x01b1] = {
    [0] = {
      type = "InventoryModifyHandler",
    },
  },
  [0x01bf] = {
    [0] = {
      type = "PlayerSetup",
    },
  },
  [0x01cb] = {
    [0] = {
      type = "ActorMove",
    },
    [1] = {
      type = "UpdatePositionInstance",
    },
  },
  [0x01e5] = {
    [0] = {
      type = "PlayerStats",
    },
  },
  [0x01e6] = {
    [0] = {
      type = "ActorCast",
    },
  },
  [0x01e8] = {
    [0] = {
      type = "FreeCompanyInfo",
    },
  },
  [0x01e9] = {
    [0] = {
      type = "Playtime",
    },
  },
  [0x01f6] = {
    [0] = {
      type = "ActorGauge",
    },
  },
  [0x0221] = {
    [0] = {
      type = "SetSearchInfoHandler",
    },
  },
  [0x0236] = {
    [0] = {
      type = "ItemMarketBoardInfo",
    },
  },
  [0x0238] = {
    [0] = {
      type = "CurrencyCrystalInfo",
    },
  },
  [0x0287] = {
    [0] = {
      type = "StatusEffectList",
    },
  },
  [0x0298] = {
    [0] = {
      type = "PlaceFieldMarkerPreset",
    },
  },
  [0x02ac] = {
    [0] = {
      type = "MarketBoardPurchaseHandler",
    },
  },
  [0x02ba] = {
    [0] = {
      type = "CompanySubmersibleStatus",
    },
  },
  [0x02bf] = {
    [0] = {
      type = "ExamineSearchInfo",
    },
  },
  [0x02d5] = {
    [0] = {
      type = "EffectResult",
    },
    [1] = {
      type = "EventStart",
    },
  },
  [0x02da] = {
    [0] = {
      type = "ResumeEventScene32",
    },
  },
  [0x0308] = {
    [0] = {
      type = "CEDirector",
    },
  },
  [0x0315] = {
    [0] = {
      type = "MarketBoardItemListing",
    },
  },
  [0x0318] = {
    [0] = {
      type = "PrepareZoning",
    },
  },
  [0x0322] = {
    [0] = {
      type = "ItemInfo",
    },
  },
  [0x0323] = {
    [0] = {
      type = "PlayerSpawn",
    },
  },
  [0x032e] = {
    [0] = {
      type = "ActorControlTarget",
    },
  },
  [0x0334] = {
    [0] = {
      type = "Examine",
    },
  },
  [0x0335] = {
    [0] = {
      type = "ResumeEventScene16",
    },
  },
  [0x033d] = {
    [0] = {
      type = "CFPreferredRole",
    },
  },
  [0x033e] = {
    [0] = {
      type = "MarketBoardPurchase",
    },
  },
  [0x035d] = {
    [0] = {
      type = "StatusEffectList2",
    },
  },
  [0x036e] = {
    [0] = {
      type = "InitZone",
    },
  },
  [0x0376] = {
    [0] = {
      type = "InventoryTransaction",
    },
  },
  [0x0386] = {
    [0] = {
      type = "UpdateInventorySlot",
    },
  },
  [0x038e] = {
    [0] = {
      type = "InventoryActionAck",
    },
  },
  [0x039c] = {
    [0] = {
      type = "Logout",
    },
  },
  [0x03b2] = {
    [0] = {
      type = "UpdatePositionHandler",
    },
  },
  [0x03b5] = {
    [0] = {
      type = "ObjectSpawn",
    },
  },
  [0x03c1] = {
    [0] = {
      type = "ClientTrigger",
    },
  },
  [0x03c9] = {
    [0] = {
      type = "AirshipStatus",
    },
  },
  [0x03ca] = {
    [0] = {
      type = "ChatHandler",
    },
  },
  [0x03d1] = {
    [0] = {
      type = "ActorSetPos",
    },
  },
  [0x03d3] = {
    [0] = {
      type = "SubmarineExplorationResult",
    },
  },
  [0x03d5] = {
    [0] = {
      type = "AoeEffect32",
    },
  },
  [0x03dc] = {
    [0] = {
      type = "AoeEffect24",
    },
  },
  [0x03e0] = {
    [0] = {
      type = "MarketBoardItemListingHistory",
    },
  },
}

function M.getDissector(typeNum, length, direction)
  return resolver.getDissector(M.types[typeNum], length, direction)
end

return M
