-- This file is generated by network:generate

local resolver = require("ffxiv_ipc_resolver")
local M = {}
M.types = {
  [0x0067] = {
    [0] = {
      type = "ActorSetPos",
    },
  },
  [0x008c] = {
    [0] = {
      type = "ActorCast",
    },
  },
  [0x008f] = {
    [0] = {
      type = "InventoryTransactionFinish",
    },
  },
  [0x0096] = {
    [0] = {
      type = "UpdateClassInfo",
    },
  },
  [0x00b2] = {
    [0] = {
      type = "UpdateSearchInfo",
    },
  },
  [0x00b5] = {
    [0] = {
      type = "RetainerInformation",
    },
  },
  [0x00cf] = {
    [0] = {
      type = "EventStart",
    },
  },
  [0x00d5] = {
    [0] = {
      type = "Effect",
    },
  },
  [0x00df] = {
    [0] = {
      type = "MarketBoardItemListingHistory",
    },
  },
  [0x0116] = {
    [0] = {
      type = "PlayerSpawn",
    },
  },
  [0x0177] = {
    [0] = {
      type = "InventoryActionAck",
    },
  },
  [0x01a7] = {
    [0] = {
      type = "UpdateInventorySlot",
    },
  },
  [0x01b2] = {
    [0] = {
      type = "AoeEffect32",
    },
  },
  [0x01c5] = {
    [0] = {
      type = "MarketBoardSearchResult",
    },
  },
  [0x01db] = {
    [0] = {
      type = "EventPlay",
    },
  },
  [0x01e5] = {
    [0] = {
      type = "AoeEffect24",
    },
  },
  [0x01f6] = {
    [0] = {
      type = "UpdateHpMpTp",
    },
  },
  [0x0217] = {
    [0] = {
      type = "CurrencyCrystalInfo",
    },
  },
  [0x0219] = {
    [0] = {
      type = "AoeEffect8",
    },
  },
  [0x021c] = {
    [0] = {
      type = "ContentFinderNotifyPop",
    },
  },
  [0x021f] = {
    [0] = {
      type = "StatusEffectList2",
    },
  },
  [0x022a] = {
    [0] = {
      type = "ExamineSearchInfo",
    },
  },
  [0x0231] = {
    [0] = {
      type = "MarketBoardItemListingCount",
    },
  },
  [0x0233] = {
    [0] = {
      type = "ClientTrigger",
    },
  },
  [0x023b] = {
    [0] = {
      type = "BossStatusEffectList",
    },
    [1] = {
      type = "StatusEffectList",
    },
  },
  [0x0245] = {
    [0] = {
      type = "AoeEffect16",
    },
  },
  [0x0251] = {
    [0] = {
      type = "EffectResult",
    },
  },
  [0x0256] = {
    [0] = {
      type = "CFPreferredRole",
    },
  },
  [0x0264] = {
    [0] = {
      type = "InitZone",
    },
  },
  [0x026f] = {
    [0] = {
      type = "ContainerInfo",
    },
  },
  [0x0280] = {
    [0] = {
      type = "NpcSpawn",
    },
  },
  [0x028b] = {
    [0] = {
      type = "InventoryTransaction",
    },
  },
  [0x0291] = {
    [0] = {
      type = "InventoryModifyHandler",
    },
  },
  [0x02bf] = {
    [0] = {
      type = "SetSearchInfoHandler",
    },
  },
  [0x02c1] = {
    [0] = {
      type = "EventPlay4",
    },
  },
  [0x02c6] = {
    [0] = {
      type = "PlayerSetup",
    },
  },
  [0x02d7] = {
    [0] = {
      type = "MarketBoardItemListing",
    },
  },
  [0x02d8] = {
    [0] = {
      type = "ActorMove",
    },
  },
  [0x02e0] = {
    [0] = {
      type = "NpcSpawn2",
    },
  },
  [0x0320] = {
    [0] = {
      type = "EventFinish",
    },
  },
  [0x0346] = {
    [0] = {
      type = "PlayerStats",
    },
  },
  [0x0387] = {
    [0] = {
      type = "ItemInfo",
    },
  },
  [0x038d] = {
    [0] = {
      type = "Examine",
    },
  },
  [0x0398] = {
    [0] = {
      type = "ActorControlSelf",
    },
  },
  [0x0399] = {
    [0] = {
      type = "ResumeEventScene32",
    },
  },
  [0x03a8] = {
    [0] = {
      type = "ChatHandler",
    },
  },
  [0x03bd] = {
    [0] = {
      type = "Playtime",
    },
  },
  [0x03cc] = {
    [0] = {
      type = "ActorControl",
    },
  },
  [0x03db] = {
    [0] = {
      type = "ActorGauge",
    },
  },
  [0x03e7] = {
    [0] = {
      type = "SystemLogMessage",
    },
  },
}

function M.getDissector(typeNum, length, direction)
  return resolver.getDissector(M.types[typeNum], length, direction)
end

return M
