-- This file is generated by network:generate

local ffxiv_ipc_free_company_dialog = Proto("ffxiv_ipc_free_company_dialog", "FFXIV-IPC FreeCompanyDialog")

local free_company_dialog_fields = {
  free_company_id = ProtoField.uint64("ffxiv_ipc_free_company_dialog.free_company_id", "freeCompanyId", base.DEC),
  fc_icon         = ProtoField.uint32("ffxiv_ipc_free_company_dialog.fc_icon", "fcIcon", base.DEC),
  unknown2        = ProtoField.uint32("ffxiv_ipc_free_company_dialog.unknown2", "unknown2", base.DEC),
  unknown3        = ProtoField.uint64("ffxiv_ipc_free_company_dialog.unknown3", "unknown3", base.DEC),
  fc_credits      = ProtoField.uint64("ffxiv_ipc_free_company_dialog.fc_credits", "fcCredits", base.DEC),
  unknown4        = ProtoField.uint64("ffxiv_ipc_free_company_dialog.unknown4", "unknown4", base.DEC),
  unknown5        = ProtoField.uint32("ffxiv_ipc_free_company_dialog.unknown5", "unknown5", base.DEC),
  unknown6        = ProtoField.uint32("ffxiv_ipc_free_company_dialog.unknown6", "unknown6", base.DEC),
  unknown7        = ProtoField.uint8("ffxiv_ipc_free_company_dialog.unknown7", "unknown7", base.DEC),
  fc_rank         = ProtoField.uint8("ffxiv_ipc_free_company_dialog.fc_rank", "fcRank", base.DEC),
  fc_name         = ProtoField.string("ffxiv_ipc_free_company_dialog.fc_name", "fcName", base.UNICODE),
  padding1        = ProtoField.uint8("ffxiv_ipc_free_company_dialog.padding1", "padding1", base.DEC),
  fc_tag          = ProtoField.string("ffxiv_ipc_free_company_dialog.fc_tag", "fcTag", base.UNICODE),
  padding2        = ProtoField.uint8("ffxiv_ipc_free_company_dialog.padding2", "padding2", base.DEC),
}

ffxiv_ipc_free_company_dialog.fields = free_company_dialog_fields

function ffxiv_ipc_free_company_dialog.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_free_company_dialog, tvbuf)
  local len = tvbuf:len()

  -- dissect the free_company_id field
  local free_company_id_tvbr = tvbuf:range(0, 8)
  local free_company_id_val  = free_company_id_tvbr:le_uint64()
  tree:add_le(free_company_dialog_fields.free_company_id, free_company_id_tvbr, free_company_id_val)

  -- dissect the fc_icon field
  local fc_icon_tvbr = tvbuf:range(8, 4)
  local fc_icon_val  = fc_icon_tvbr:le_uint()
  tree:add_le(free_company_dialog_fields.fc_icon, fc_icon_tvbr, fc_icon_val)

  -- dissect the unknown2 field
  local unknown2_tvbr = tvbuf:range(12, 4)
  local unknown2_val  = unknown2_tvbr:le_uint()
  tree:add_le(free_company_dialog_fields.unknown2, unknown2_tvbr, unknown2_val)

  -- dissect the unknown3 field
  local unknown3_tvbr = tvbuf:range(16, 8)
  local unknown3_val  = unknown3_tvbr:le_uint64()
  tree:add_le(free_company_dialog_fields.unknown3, unknown3_tvbr, unknown3_val)

  -- dissect the fc_credits field
  local fc_credits_tvbr = tvbuf:range(24, 8)
  local fc_credits_val  = fc_credits_tvbr:le_uint64()
  tree:add_le(free_company_dialog_fields.fc_credits, fc_credits_tvbr, fc_credits_val)

  -- dissect the unknown4 field
  local unknown4_tvbr = tvbuf:range(32, 8)
  local unknown4_val  = unknown4_tvbr:le_uint64()
  tree:add_le(free_company_dialog_fields.unknown4, unknown4_tvbr, unknown4_val)

  -- dissect the unknown5 field
  local unknown5_tvbr = tvbuf:range(40, 4)
  local unknown5_val  = unknown5_tvbr:le_uint()
  tree:add_le(free_company_dialog_fields.unknown5, unknown5_tvbr, unknown5_val)

  -- dissect the unknown6 field
  local unknown6_tvbr = tvbuf:range(44, 4)
  local unknown6_val  = unknown6_tvbr:le_uint()
  tree:add_le(free_company_dialog_fields.unknown6, unknown6_tvbr, unknown6_val)

  -- dissect the unknown7 field
  local unknown7_tvbr = tvbuf:range(48, 1)
  local unknown7_val  = unknown7_tvbr:le_uint()
  tree:add_le(free_company_dialog_fields.unknown7, unknown7_tvbr, unknown7_val)

  -- dissect the fc_rank field
  local fc_rank_tvbr = tvbuf:range(49, 1)
  local fc_rank_val  = fc_rank_tvbr:le_uint()
  tree:add_le(free_company_dialog_fields.fc_rank, fc_rank_tvbr, fc_rank_val)

  -- dissect the fc_name field
  local fc_name_tvbr = tvbuf:range(50, 21)
  local fc_name_val  = fc_name_tvbr:string(ENC_UTF_8)
  tree:add(free_company_dialog_fields.fc_name, fc_name_tvbr, fc_name_val)

  local fc_name_display = ", fcName: " .. fc_name_val
  pktinfo.cols.info:append(fc_name_display)
  tree:append_text(fc_name_display)

  -- dissect the padding1 field
  local padding1_tvbr = tvbuf:range(71, 1)
  local padding1_val  = padding1_tvbr:le_uint()
  tree:add_le(free_company_dialog_fields.padding1, padding1_tvbr, padding1_val)

  -- dissect the fc_tag field
  local fc_tag_tvbr = tvbuf:range(72, 6)
  local fc_tag_val  = fc_tag_tvbr:string(ENC_UTF_8)
  tree:add(free_company_dialog_fields.fc_tag, fc_tag_tvbr, fc_tag_val)

  local fc_tag_display = ", fcTag: " .. fc_tag_val
  pktinfo.cols.info:append(fc_tag_display)
  tree:append_text(fc_tag_display)

  -- dissect the padding2 field
  local padding2_tvbr = tvbuf:range(78, 1)
  local padding2_val  = padding2_tvbr:le_uint()
  tree:add_le(free_company_dialog_fields.padding2, padding2_tvbr, padding2_val)

  return len
end
