-- This file is generated by network:generate

local ffxiv_ipc_market_board_history_listing = Proto("ffxiv_ipc_market_board_history_listing", "FFXIV-IPC MarketBoardHistoryListing")

local market_board_history_listing_fields = {
  sale_price    = ProtoField.uint32("ffxiv_ipc_market_board_history_listing.sale_price", "salePrice", base.DEC),
  purchase_time = ProtoField.uint32("ffxiv_ipc_market_board_history_listing.purchase_time", "purchaseTime", base.DEC),
  quantity      = ProtoField.uint32("ffxiv_ipc_market_board_history_listing.quantity", "quantity", base.DEC),
  is_hq         = ProtoField.uint8("ffxiv_ipc_market_board_history_listing.is_hq", "isHq", base.DEC),
  on_mannequin  = ProtoField.uint8("ffxiv_ipc_market_board_history_listing.on_mannequin", "onMannequin", base.DEC),
  buyer_name    = ProtoField.string("ffxiv_ipc_market_board_history_listing.buyer_name", "buyerName", base.UNICODE),
  padding       = ProtoField.uint16("ffxiv_ipc_market_board_history_listing.padding", "padding", base.DEC),
}

ffxiv_ipc_market_board_history_listing.fields = market_board_history_listing_fields

function ffxiv_ipc_market_board_history_listing.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_market_board_history_listing, tvbuf)
  local len = tvbuf:len()

  -- dissect the sale_price field
  local sale_price_tvbr = tvbuf:range(0, 4)
  local sale_price_val  = sale_price_tvbr:le_uint()
  tree:add_le(market_board_history_listing_fields.sale_price, sale_price_tvbr, sale_price_val)

  -- dissect the purchase_time field
  local purchase_time_tvbr = tvbuf:range(4, 4)
  local purchase_time_val  = purchase_time_tvbr:le_uint()
  tree:add_le(market_board_history_listing_fields.purchase_time, purchase_time_tvbr, purchase_time_val)

  -- dissect the quantity field
  local quantity_tvbr = tvbuf:range(8, 4)
  local quantity_val  = quantity_tvbr:le_uint()
  tree:add_le(market_board_history_listing_fields.quantity, quantity_tvbr, quantity_val)

  -- dissect the is_hq field
  local is_hq_tvbr = tvbuf:range(12, 1)
  local is_hq_val  = is_hq_tvbr:le_uint()
  tree:add_le(market_board_history_listing_fields.is_hq, is_hq_tvbr, is_hq_val)

  -- dissect the on_mannequin field
  local on_mannequin_tvbr = tvbuf:range(13, 1)
  local on_mannequin_val  = on_mannequin_tvbr:le_uint()
  tree:add_le(market_board_history_listing_fields.on_mannequin, on_mannequin_tvbr, on_mannequin_val)

  -- dissect the buyer_name field
  local buyer_name_tvbr = tvbuf:range(14, 32)
  local buyer_name_val  = buyer_name_tvbr:string(ENC_UTF_8)
  tree:add(market_board_history_listing_fields.buyer_name, buyer_name_tvbr, buyer_name_val)

  local buyer_name_display = ", buyerName: " .. buyer_name_val
  pktinfo.cols.info:append(buyer_name_display)
  tree:append_text(buyer_name_display)

  -- dissect the padding field
  local padding_tvbr = tvbuf:range(46, 2)
  local padding_val  = padding_tvbr:le_uint()
  tree:add_le(market_board_history_listing_fields.padding, padding_tvbr, padding_val)

  return len
end
