-- This file is generated by network:generate

local M = {}
M.types = {
  [0x0074] = {
    [0] = {
      title = "ItemMarketBoardInfo",
    },
  },
  [0x0079] = {
    [0] = {
      title = "SubmarineProgressionStatus",
    },
  },
  [0x0080] = {
    [0] = {
      title = "StatusEffectList",
      name = "ffxiv_ipc_status_effect_list",
      length = 380,
    },
  },
  [0x0087] = {
    [0] = {
      title = "SystemLogMessage",
    },
  },
  [0x0089] = {
    [0] = {
      title = "ResumeEventScene32",
    },
  },
  [0x00a3] = {
    [0] = {
      title = "FateInfo",
      name = "ffxiv_ipc_fate_info",
      length = 24,
    },
  },
  [0x00a4] = {
    [0] = {
      title = "StatusEffectList3",
    },
  },
  [0x00b2] = {
    [0] = {
      title = "CountdownCancel",
    },
  },
  [0x00bd] = {
    [0] = {
      title = "AirshipStatus",
    },
  },
  [0x00bf] = {
    [0] = {
      title = "ContentFinderNotifyPop",
      name = "ffxiv_ipc_content_finder_notify_pop",
      length = 32,
    },
  },
  [0x00c5] = {
    [0] = {
      title = "AoeEffect24",
      name = "ffxiv_ipc_aoe_effect24",
      length = 1784,
    },
  },
  [0x00c6] = {
    [0] = {
      title = "MarketBoardPurchase",
    },
  },
  [0x00c7] = {
    [0] = {
      title = "ChatHandler",
    },
  },
  [0x00d4] = {
    [0] = {
      title = "ContainerInfo",
      name = "ffxiv_ipc_container_info",
      length = 16,
    },
  },
  [0x00de] = {
    [0] = {
      title = "UpdateHpMpTp",
      name = "ffxiv_ipc_update_hp_mp_tp",
      length = 8,
    },
  },
  [0x00e0] = {
    [0] = {
      title = "Logout",
    },
  },
  [0x00e4] = {
    [0] = {
      title = "NpcYell",
    },
  },
  [0x00eb] = {
    [0] = {
      title = "SubmarineExplorationResult",
    },
  },
  [0x0103] = {
    [0] = {
      title = "BossStatusEffectList",
      name = "ffxiv_ipc_boss_status_effect_list",
      length = 740,
    },
  },
  [0x0110] = {
    [0] = {
      title = "ItemInfo",
      name = "ffxiv_ipc_item_info",
      length = 64,
    },
  },
  [0x0123] = {
    [0] = {
      title = "EffectResultBasic",
    },
  },
  [0x012b] = {
    [0] = {
      title = "ObjectSpawn",
      name = "ffxiv_ipc_object_spawn",
      length = 64,
    },
  },
  [0x0134] = {
    [0] = {
      title = "PlayerSpawn",
      name = "ffxiv_ipc_player_spawn",
      length = 624,
    },
  },
  [0x0142] = {
    [0] = {
      title = "MarketBoardRequestItemListingInfo",
    },
  },
  [0x0146] = {
    [0] = {
      title = "CountdownInitiate",
    },
  },
  [0x0156] = {
    [0] = {
      title = "AirshipExplorationResult",
    },
  },
  [0x016c] = {
    [0] = {
      title = "FreeCompanyInfo",
    },
  },
  [0x016d] = {
    [0] = {
      title = "MarketBoardPurchaseHandler",
    },
    [1] = {
      title = "RSV",
    },
  },
  [0x0171] = {
    [0] = {
      title = "MarketBoardItemListing",
    },
  },
  [0x0179] = {
    [0] = {
      title = "EffectResult",
      name = "ffxiv_ipc_effect_result",
      length = 26,
    },
  },
  [0x0184] = {
    [0] = {
      title = "ExamineSearchInfo",
    },
  },
  [0x018a] = {
    [0] = {
      title = "WeatherChange",
    },
  },
  [0x018b] = {
    [0] = {
      title = "CompanyAirshipStatus",
      name = "ffxiv_ipc_company_airship_status",
      length = 0,
    },
  },
  [0x0191] = {
    [0] = {
      title = "EnvironmentControl",
    },
  },
  [0x01a2] = {
    [0] = {
      title = "EventPlay4",
    },
  },
  [0x01a9] = {
    [0] = {
      title = "ActorControlSelf",
      name = "ffxiv_ipc_actor_control_self",
      length = 32,
    },
  },
  [0x01db] = {
    [0] = {
      title = "CurrencyCrystalInfo",
      name = "ffxiv_ipc_currency_crystal_info",
      length = 32,
    },
  },
  [0x01e5] = {
    [0] = {
      title = "EventStart",
    },
  },
  [0x01f1] = {
    [0] = {
      title = "StatusEffectList2",
    },
  },
  [0x01f8] = {
    [0] = {
      title = "ClientTrigger",
      name = "ffxiv_ipc_client_trigger",
      length = 32,
    },
    [1] = {
      title = "FreeCompanyDialog",
    },
  },
  [0x0201] = {
    [0] = {
      title = "InventoryHandlerOffset",
    },
    [1] = {
      title = "InventoryModifyHandler",
    },
  },
  [0x0212] = {
    [0] = {
      title = "PlayerSetup",
      name = "ffxiv_ipc_player_setup",
      length = 1938,
    },
  },
  [0x0213] = {
    [0] = {
      title = "PlaceFieldMarkerPreset",
    },
  },
  [0x021a] = {
    [0] = {
      title = "NpcSpawn",
      name = "ffxiv_ipc_npc_spawn",
      length = 624,
    },
    [1] = {
      title = "UpdatePositionInstance",
      name = "ffxiv_ipc_update_position_instance",
      length = 40,
    },
  },
  [0x0232] = {
    [0] = {
      title = "ActorSetPos",
      name = "ffxiv_ipc_actor_set_pos",
      length = 20,
    },
  },
  [0x023c] = {
    [0] = {
      title = "CFPreferredRole",
    },
  },
  [0x0247] = {
    [0] = {
      title = "ActorCast",
      name = "ffxiv_ipc_actor_cast",
      length = 30,
    },
  },
  [0x024a] = {
    [0] = {
      title = "WardLandInfo",
      name = "ffxiv_ipc_ward_land_info",
      length = 2408,
    },
  },
  [0x024b] = {
    [0] = {
      title = "NpcSpawn2",
      name = "ffxiv_ipc_npc_spawn2",
      length = 624,
    },
  },
  [0x024c] = {
    [0] = {
      title = "ActorGauge",
      name = "ffxiv_ipc_actor_gauge",
      length = 16,
    },
  },
  [0x025d] = {
    [0] = {
      title = "InitZone",
      name = "ffxiv_ipc_init_zone",
      length = 96,
    },
  },
  [0x0260] = {
    [0] = {
      title = "RetainerInformation",
      name = "ffxiv_ipc_retainer_information",
      length = 73,
    },
  },
  [0x027a] = {
    [0] = {
      title = "InventoryTransactionFinish",
      name = "ffxiv_ipc_inventory_transaction_finish",
      length = 16,
    },
  },
  [0x0298] = {
    [0] = {
      title = "Playtime",
    },
  },
  [0x029e] = {
    [0] = {
      title = "Effect",
      name = "ffxiv_ipc_effect",
      length = 120,
    },
  },
  [0x02a2] = {
    [0] = {
      title = "ActorFreeSpawn",
      name = "ffxiv_ipc_actor_free_spawn",
      length = 8,
    },
  },
  [0x02bb] = {
    [0] = {
      title = "ActorMove",
      name = "ffxiv_ipc_actor_move",
      length = 12,
    },
  },
  [0x02be] = {
    [0] = {
      title = "AoeEffect16",
      name = "ffxiv_ipc_aoe_effect16",
      length = 1208,
    },
  },
  [0x02c9] = {
    [0] = {
      title = "CEDirector",
      name = "ffxiv_ipc_ce_director",
      length = 16,
    },
  },
  [0x02d0] = {
    [0] = {
      title = "EventFinish",
    },
  },
  [0x02dd] = {
    [0] = {
      title = "Examine",
      name = "ffxiv_ipc_examine",
      length = 656,
    },
  },
  [0x02f0] = {
    [0] = {
      title = "UpdatePositionHandler",
    },
  },
  [0x0301] = {
    [0] = {
      title = "AoeEffect8",
      name = "ffxiv_ipc_aoe_effect8",
      length = 632,
    },
  },
  [0x030e] = {
    [0] = {
      title = "ActorControlTarget",
      name = "ffxiv_ipc_actor_control_target",
      length = 32,
    },
  },
  [0x0311] = {
    [0] = {
      title = "ActorControl",
      name = "ffxiv_ipc_actor_control",
      length = 24,
    },
  },
  [0x0313] = {
    [0] = {
      title = "PrepareZoning",
    },
  },
  [0x031c] = {
    [0] = {
      title = "SubmarineStatusList",
      name = "ffxiv_ipc_submarine_status_list",
      length = 240,
    },
  },
  [0x0335] = {
    [0] = {
      title = "MarketBoardSearchResult",
    },
  },
  [0x033a] = {
    [0] = {
      title = "AirshipStatusList",
    },
  },
  [0x0356] = {
    [0] = {
      title = "InventoryTransaction",
      name = "ffxiv_ipc_inventory_transaction",
      length = 36,
    },
  },
  [0x035e] = {
    [0] = {
      title = "ResumeEventScene16",
    },
  },
  [0x0371] = {
    [0] = {
      title = "CompanySubmersibleStatus",
      name = "ffxiv_ipc_company_submersible_status",
      length = 0,
    },
  },
  [0x0372] = {
    [0] = {
      title = "AoeEffect32",
      name = "ffxiv_ipc_aoe_effect32",
      length = 2360,
    },
  },
  [0x0374] = {
    [0] = {
      title = "PlaceFieldMarker",
    },
  },
  [0x0379] = {
    [0] = {
      title = "BattleTalk2",
    },
  },
  [0x0382] = {
    [0] = {
      title = "MarketBoardItemListingHistory",
    },
  },
  [0x038e] = {
    [0] = {
      title = "UpdateClassInfo",
      name = "ffxiv_ipc_update_class_info",
      length = 16,
    },
  },
  [0x039a] = {
    [0] = {
      title = "EventPlay",
    },
  },
  [0x03a3] = {
    [0] = {
      title = "UpdateSearchInfo",
    },
  },
  [0x03a8] = {
    [0] = {
      title = "UpdateInventorySlot",
      name = "ffxiv_ipc_update_inventory_slot",
      length = 64,
    },
  },
  [0x03ac] = {
    [0] = {
      title = "InventoryActionAck",
      name = "ffxiv_ipc_inventory_action_ack",
      length = 16,
    },
  },
  [0x03bb] = {
    [0] = {
      title = "IslandWorkshopSupplyDemand",
    },
  },
  [0x03c6] = {
    [0] = {
      title = "MarketBoardItemListingCount",
    },
  },
  [0x03ca] = {
    [0] = {
      title = "SetSearchInfoHandler",
    },
  },
  [0x03cf] = {
    [0] = {
      title = "EventPlay32",
    },
  },
  [0x03e6] = {
    [0] = {
      title = "PlayerStats",
      name = "ffxiv_ipc_player_stats",
      length = 120,
    },
  },
}

function M.getDissector(typeNum, length)
  local types = M.types[typeNum]
  if type(types) ~= "table" then
    return nil
  end

  local title = nil
  if types[0] ~= nil then
    title = types[0].title
  end

  for k, v in pairs(types) do
    if v.name ~= nil and v.length ~= nil and v.length == length then
      return Dissector.get(v.name), v.title
    end
  end

  for k, v in pairs(types) do
    if v.name ~= nil and v.length ~= nil and v.length < length then
      return Dissector.get(v.name), v.title
    end
  end

  return nil, title
end

return M
