-- This file is generated by network:generate

local resolver = require("ffxiv_ipc_resolver")
local M = {}
M.types = {
  [0x006c] = {
    [0] = {
      type = "InventoryHandlerOffset",
    },
    [1] = {
      type = "InventoryModifyHandler",
    },
  },
  [0x006d] = {
    [0] = {
      type = "ActorSetPos",
    },
  },
  [0x0079] = {
    [0] = {
      type = "MarketBoardItemListing",
    },
  },
  [0x0080] = {
    [0] = {
      type = "InventoryActionAck",
    },
  },
  [0x00ac] = {
    [0] = {
      type = "SubmarineExplorationResult",
    },
  },
  [0x00ad] = {
    [0] = {
      type = "ContainerInfo",
    },
  },
  [0x00af] = {
    [0] = {
      type = "CEDirector",
    },
  },
  [0x00bb] = {
    [0] = {
      type = "SetSearchInfoHandler",
    },
  },
  [0x00c6] = {
    [0] = {
      type = "UpdateClassInfo",
    },
  },
  [0x00cb] = {
    [0] = {
      type = "EffectResultBasic",
    },
  },
  [0x00e1] = {
    [0] = {
      type = "InitZone",
    },
  },
  [0x00e7] = {
    [0] = {
      type = "EnvironmentControl",
    },
  },
  [0x00f0] = {
    [0] = {
      type = "NpcYell",
    },
  },
  [0x00f1] = {
    [0] = {
      type = "AoeEffect32",
    },
  },
  [0x0104] = {
    [0] = {
      type = "MarketBoardPurchase",
    },
  },
  [0x010a] = {
    [0] = {
      type = "CountdownCancel",
    },
  },
  [0x011a] = {
    [0] = {
      type = "Effect",
    },
  },
  [0x0126] = {
    [0] = {
      type = "UpdatePositionHandler",
    },
  },
  [0x012c] = {
    [0] = {
      type = "MarketBoardItemListingHistory",
    },
  },
  [0x0137] = {
    [0] = {
      type = "UpdateHpMpTp",
    },
  },
  [0x013f] = {
    [0] = {
      type = "FreeCompanyInfo",
    },
  },
  [0x0146] = {
    [0] = {
      type = "MarketBoardPurchaseHandler",
    },
  },
  [0x014e] = {
    [0] = {
      type = "IslandWorkshopSupplyDemand",
    },
  },
  [0x017e] = {
    [0] = {
      type = "StatusEffectList2",
    },
  },
  [0x0187] = {
    [0] = {
      type = "UpdateInventorySlot",
    },
  },
  [0x0193] = {
    [0] = {
      type = "Playtime",
    },
  },
  [0x0197] = {
    [0] = {
      type = "SubmarineProgressionStatus",
    },
  },
  [0x019b] = {
    [0] = {
      type = "ActorControl",
    },
  },
  [0x01ab] = {
    [0] = {
      type = "AoeEffect16",
    },
  },
  [0x01b0] = {
    [0] = {
      type = "ResumeEventScene32",
    },
  },
  [0x01b9] = {
    [0] = {
      type = "FateInfo",
    },
  },
  [0x01be] = {
    [0] = {
      type = "SubmarineStatusList",
    },
  },
  [0x01c8] = {
    [0] = {
      type = "EventStart",
    },
  },
  [0x01c9] = {
    [0] = {
      type = "PlaceFieldMarker",
    },
  },
  [0x01cf] = {
    [0] = {
      type = "CountdownInitiate",
    },
  },
  [0x01d2] = {
    [0] = {
      type = "EventFinish",
    },
  },
  [0x01df] = {
    [0] = {
      type = "ResumeEventScene16",
    },
  },
  [0x01ef] = {
    [0] = {
      type = "ActorControlTarget",
    },
  },
  [0x01f3] = {
    [0] = {
      type = "PlayerSetup",
    },
  },
  [0x01f6] = {
    [0] = {
      type = "AirshipStatusList",
    },
  },
  [0x01f7] = {
    [0] = {
      type = "InventoryTransactionFinish",
    },
  },
  [0x0200] = {
    [0] = {
      type = "ActorFreeSpawn",
    },
  },
  [0x0207] = {
    [0] = {
      type = "ActorGauge",
    },
  },
  [0x0208] = {
    [0] = {
      type = "AirshipExplorationResult",
    },
  },
  [0x0227] = {
    [0] = {
      type = "ExamineSearchInfo",
    },
  },
  [0x0230] = {
    [0] = {
      type = "EventPlay",
    },
  },
  [0x0233] = {
    [0] = {
      type = "Examine",
    },
  },
  [0x023d] = {
    [0] = {
      type = "MarketBoardSearchResult",
    },
  },
  [0x0246] = {
    [0] = {
      type = "UpdatePositionInstance",
    },
  },
  [0x0248] = {
    [0] = {
      type = "StatusEffectList",
    },
  },
  [0x0253] = {
    [0] = {
      type = "ObjectSpawn",
    },
  },
  [0x0255] = {
    [0] = {
      type = "AoeEffect8",
    },
  },
  [0x0261] = {
    [0] = {
      type = "NpcSpawn",
    },
  },
  [0x0270] = {
    [0] = {
      type = "PlaceFieldMarkerPreset",
    },
  },
  [0x0298] = {
    [0] = {
      type = "EffectResult",
    },
  },
  [0x0299] = {
    [0] = {
      type = "BossStatusEffectList",
    },
  },
  [0x02b9] = {
    [0] = {
      type = "InventoryTransaction",
    },
  },
  [0x02c4] = {
    [0] = {
      type = "RSV",
    },
  },
  [0x02c5] = {
    [0] = {
      type = "ActorCast",
    },
  },
  [0x02c7] = {
    [0] = {
      type = "ContentFinderNotifyPop",
    },
  },
  [0x02da] = {
    [0] = {
      type = "UpdateSearchInfo",
    },
  },
  [0x02df] = {
    [0] = {
      type = "FreeCompanyDialog",
    },
  },
  [0x02e3] = {
    [0] = {
      type = "ItemMarketBoardInfo",
    },
  },
  [0x02f1] = {
    [0] = {
      type = "CFPreferredRole",
    },
  },
  [0x02f9] = {
    [0] = {
      type = "BattleTalk2",
    },
  },
  [0x02fb] = {
    [0] = {
      type = "EventPlay4",
    },
  },
  [0x0301] = {
    [0] = {
      type = "PlayerSpawn",
    },
  },
  [0x0303] = {
    [0] = {
      type = "PlayerStats",
    },
  },
  [0x031c] = {
    [0] = {
      type = "EventPlay32",
    },
  },
  [0x0326] = {
    [0] = {
      type = "NpcSpawn2",
    },
  },
  [0x032e] = {
    [0] = {
      type = "MarketBoardItemListingCount",
    },
  },
  [0x0338] = {
    [0] = {
      type = "AoeEffect24",
    },
  },
  [0x033f] = {
    [0] = {
      type = "ActorControlSelf",
    },
  },
  [0x0342] = {
    [0] = {
      type = "AirshipStatus",
    },
  },
  [0x0344] = {
    [0] = {
      type = "WeatherChange",
    },
  },
  [0x0346] = {
    [0] = {
      type = "PrepareZoning",
    },
  },
  [0x036c] = {
    [0] = {
      type = "CurrencyCrystalInfo",
    },
  },
  [0x0377] = {
    [0] = {
      type = "CompanySubmersibleStatus",
    },
  },
  [0x037f] = {
    [0] = {
      type = "ItemInfo",
    },
  },
  [0x0389] = {
    [0] = {
      type = "WardLandInfo",
    },
  },
  [0x0398] = {
    [0] = {
      type = "CompanyAirshipStatus",
    },
  },
  [0x039f] = {
    [0] = {
      type = "RetainerInformation",
    },
  },
  [0x03a6] = {
    [0] = {
      type = "ChatHandler",
    },
  },
  [0x03b5] = {
    [0] = {
      type = "SystemLogMessage",
    },
  },
  [0x03d6] = {
    [0] = {
      type = "Logout",
    },
  },
  [0x03e0] = {
    [0] = {
      type = "ClientTrigger",
    },
  },
  [0x03e3] = {
    [0] = {
      type = "StatusEffectList3",
    },
  },
  [0x03e5] = {
    [0] = {
      type = "ActorMove",
    },
  },
}

function M.getDissector(typeNum, length, direction)
  return resolver.getDissector(M.types[typeNum], length, direction)
end

return M
