-- This file is generated by network:generate

local resolver = require("ffxiv_ipc_resolver")
local M = {}
M.types = {
  [0x0078] = {
    [0] = {
      type = "ItemMarketBoardInfo",
    },
  },
  [0x007b] = {
    [0] = {
      type = "UpdateSearchInfo",
    },
  },
  [0x008b] = {
    [0] = {
      type = "InventoryActionAck",
    },
  },
  [0x00b1] = {
    [0] = {
      type = "BossStatusEffectList",
    },
  },
  [0x00bc] = {
    [0] = {
      type = "EventPlay4",
    },
  },
  [0x00c8] = {
    [0] = {
      type = "PlayerSpawn",
    },
  },
  [0x00c9] = {
    [0] = {
      type = "ActorGauge",
    },
  },
  [0x00ca] = {
    [0] = {
      type = "ContentFinderNotifyPop",
    },
  },
  [0x00cd] = {
    [0] = {
      type = "Effect",
    },
  },
  [0x00da] = {
    [0] = {
      type = "PlaceFieldMarker",
    },
  },
  [0x00de] = {
    [0] = {
      type = "EventStart",
    },
  },
  [0x00e1] = {
    [0] = {
      type = "CompanyAirshipStatus",
    },
  },
  [0x00ef] = {
    [0] = {
      type = "MarketBoardItemListingCount",
    },
  },
  [0x010c] = {
    [0] = {
      type = "ContainerInfo",
    },
  },
  [0x011f] = {
    [0] = {
      type = "FreeCompanyInfo",
    },
  },
  [0x0136] = {
    [0] = {
      type = "PlaceFieldMarkerPreset",
    },
  },
  [0x0137] = {
    [0] = {
      type = "FreeCompanyDialog",
    },
  },
  [0x013e] = {
    [0] = {
      type = "NpcSpawn2",
    },
  },
  [0x0146] = {
    [0] = {
      type = "PrepareZoning",
    },
  },
  [0x0149] = {
    [0] = {
      type = "StatusEffectList",
    },
  },
  [0x0153] = {
    [0] = {
      type = "ObjectSpawn",
    },
  },
  [0x0158] = {
    [0] = {
      type = "SubmarineExplorationResult",
    },
  },
  [0x017a] = {
    [0] = {
      type = "MarketBoardPurchaseHandler",
    },
  },
  [0x017d] = {
    [0] = {
      type = "PlayerStats",
    },
  },
  [0x0183] = {
    [0] = {
      type = "SystemLogMessage",
    },
  },
  [0x0184] = {
    [0] = {
      type = "ActorCast",
    },
  },
  [0x018c] = {
    [0] = {
      type = "AoeEffect32",
    },
  },
  [0x019d] = {
    [0] = {
      type = "SetSearchInfoHandler",
    },
  },
  [0x01a3] = {
    [0] = {
      type = "ActorControlSelf",
    },
  },
  [0x01c1] = {
    [0] = {
      type = "UpdateInventorySlot",
    },
  },
  [0x01e3] = {
    [0] = {
      type = "InitZone",
    },
  },
  [0x01e6] = {
    [0] = {
      type = "CompanySubmersibleStatus",
    },
  },
  [0x01ec] = {
    [0] = {
      type = "RetainerInformation",
    },
  },
  [0x01fc] = {
    [0] = {
      type = "InventoryTransaction",
    },
  },
  [0x0209] = {
    [0] = {
      type = "CurrencyCrystalInfo",
    },
  },
  [0x0215] = {
    [0] = {
      type = "AoeEffect8",
    },
  },
  [0x0247] = {
    [0] = {
      type = "UpdateHpMpTp",
    },
  },
  [0x024e] = {
    [0] = {
      type = "ActorSetPos",
    },
  },
  [0x0251] = {
    [0] = {
      type = "ResumeEventScene32",
    },
  },
  [0x0252] = {
    [0] = {
      type = "AoeEffect16",
    },
  },
  [0x0255] = {
    [0] = {
      type = "Examine",
    },
  },
  [0x0258] = {
    [0] = {
      type = "EffectResultBasic",
    },
  },
  [0x025a] = {
    [0] = {
      type = "MarketBoardSearchResult",
    },
  },
  [0x0271] = {
    [0] = {
      type = "AoeEffect24",
    },
  },
  [0x028c] = {
    [0] = {
      type = "UpdateClassInfo",
    },
  },
  [0x029a] = {
    [0] = {
      type = "InventoryHandlerOffset",
    },
    [1] = {
      type = "InventoryModifyHandler",
    },
  },
  [0x029f] = {
    [0] = {
      type = "WardLandInfo",
    },
  },
  [0x02a5] = {
    [0] = {
      type = "ActorControl",
    },
  },
  [0x02b1] = {
    [0] = {
      type = "EventFinish",
    },
  },
  [0x02cf] = {
    [0] = {
      type = "FateInfo",
    },
  },
  [0x02d0] = {
    [0] = {
      type = "ActorControlTarget",
    },
  },
  [0x02e3] = {
    [0] = {
      type = "AirshipStatusList",
    },
  },
  [0x0303] = {
    [0] = {
      type = "CFPreferredRole",
    },
  },
  [0x030e] = {
    [0] = {
      type = "EnvironmentControl",
    },
  },
  [0x030f] = {
    [0] = {
      type = "RSV",
    },
  },
  [0x0310] = {
    [0] = {
      type = "IslandWorkshopSupplyDemand",
    },
  },
  [0x0315] = {
    [0] = {
      type = "UpdatePositionHandler",
    },
  },
  [0x0320] = {
    [0] = {
      type = "UpdatePositionInstance",
    },
  },
  [0x0325] = {
    [0] = {
      type = "ClientTrigger",
    },
  },
  [0x0326] = {
    [0] = {
      type = "ChatHandler",
    },
  },
  [0x032e] = {
    [0] = {
      type = "AirshipExplorationResult",
    },
  },
  [0x033b] = {
    [0] = {
      type = "InventoryTransactionFinish",
    },
  },
  [0x033d] = {
    [0] = {
      type = "Logout",
    },
  },
  [0x033e] = {
    [0] = {
      type = "Playtime",
    },
  },
  [0x034a] = {
    [0] = {
      type = "MarketBoardPurchase",
    },
  },
  [0x0353] = {
    [0] = {
      type = "ExamineSearchInfo",
    },
  },
  [0x0365] = {
    [0] = {
      type = "SubmarineStatusList",
    },
  },
  [0x0366] = {
    [0] = {
      type = "NpcSpawn",
    },
  },
  [0x036b] = {
    [0] = {
      type = "ItemInfo",
    },
  },
  [0x0378] = {
    [0] = {
      type = "EffectResult",
    },
  },
  [0x038e] = {
    [0] = {
      type = "ActorMove",
    },
  },
  [0x0396] = {
    [0] = {
      type = "ResumeEventScene16",
    },
  },
  [0x039d] = {
    [0] = {
      type = "SubmarineProgressionStatus",
    },
  },
  [0x03a8] = {
    [0] = {
      type = "PlayerSetup",
    },
  },
  [0x03ac] = {
    [0] = {
      type = "MarketBoardItemListingHistory",
    },
  },
  [0x03b0] = {
    [0] = {
      type = "MarketBoardItemListing",
    },
  },
  [0x03b1] = {
    [0] = {
      type = "StatusEffectList2",
    },
  },
  [0x03c2] = {
    [0] = {
      type = "StatusEffectList3",
    },
  },
  [0x03c8] = {
    [0] = {
      type = "AirshipStatus",
    },
  },
  [0x03ce] = {
    [0] = {
      type = "EventPlay",
    },
  },
  [0x03df] = {
    [0] = {
      type = "ActorFreeSpawn",
    },
  },
  [0x03e6] = {
    [0] = {
      type = "CEDirector",
    },
  },
}

function M.getDissector(typeNum, length, direction)
  return resolver.getDissector(M.types[typeNum], length, direction)
end

return M
