-- This file is generated by network:generate

local M = {}
M.types = {
  [0x0066] = {
    [0] = {
      name = "ffxiv_ipc_player_setup",
      length = 1938,
    },
  },
  [0x00a2] = {
    [0] = {
      name = "ffxiv_ipc_update_inventory_slot",
      length = 64,
    },
  },
  [0x00b1] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect16",
      length = 1208,
    },
  },
  [0x00d5] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect32",
      length = 2360,
    },
  },
  [0x00da] = {
    [0] = {
      name = "ffxiv_ipc_company_submersible_status",
      length = 0,
    },
  },
  [0x00fd] = {
    [0] = {
      name = "ffxiv_ipc_object_spawn",
      length = 64,
    },
  },
  [0x0133] = {
    [0] = {
      name = "ffxiv_ipc_boss_status_effect_list",
      length = 740,
    },
    [1] = {
      name = "ffxiv_ipc_status_effect_list",
      length = 380,
    },
  },
  [0x013b] = {
    [0] = {
      name = "ffxiv_ipc_container_info",
      length = 16,
    },
  },
  [0x0142] = {
    [0] = {
      name = "ffxiv_ipc_npc_spawn",
      length = 624,
    },
  },
  [0x0166] = {
    [0] = {
      name = "ffxiv_ipc_actor_cast",
      length = 30,
    },
  },
  [0x016b] = {
    [0] = {
      name = "ffxiv_ipc_update_hp_mp_tp",
      length = 8,
    },
  },
  [0x0199] = {
    [0] = {
      name = "ffxiv_ipc_update_class_info",
      length = 16,
    },
  },
  [0x01ae] = {
    [0] = {
      name = "ffxiv_ipc_company_airship_status",
      length = 0,
    },
  },
  [0x01d4] = {
    [0] = {
      name = "ffxiv_ipc_retainer_information",
      length = 73,
    },
  },
  [0x01de] = {
    [0] = {
      name = "ffxiv_ipc_inventory_transaction",
      length = 36,
    },
  },
  [0x01e5] = {
    [0] = {
      name = "ffxiv_ipc_actor_move",
      length = 12,
    },
  },
  [0x01fa] = {
    [0] = {
      name = "ffxiv_ipc_client_trigger",
      length = 32,
    },
  },
  [0x01fe] = {
    [0] = {
      name = "ffxiv_ipc_inventory_transaction_finish",
      length = 16,
    },
  },
  [0x022b] = {
    [0] = {
      name = "ffxiv_ipc_ward_land_info",
      length = 2408,
    },
  },
  [0x0242] = {
    [0] = {
      name = "ffxiv_ipc_init_zone",
      length = 96,
    },
  },
  [0x025e] = {
    [0] = {
      name = "ffxiv_ipc_examine",
      length = 656,
    },
  },
  [0x028b] = {
    [0] = {
      name = "ffxiv_ipc_actor_control_self",
      length = 32,
    },
  },
  [0x028c] = {
    [0] = {
      name = "ffxiv_ipc_item_info",
      length = 64,
    },
  },
  [0x02a6] = {
    [0] = {
      name = "ffxiv_ipc_content_finder_notify_pop",
      length = 32,
    },
  },
  [0x02b7] = {
    [0] = {
      name = "ffxiv_ipc_actor_free_spawn",
      length = 8,
    },
  },
  [0x02d1] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect8",
      length = 632,
    },
  },
  [0x02d3] = {
    [0] = {
      name = "ffxiv_ipc_player_stats",
      length = 120,
    },
  },
  [0x02d6] = {
    [0] = {
      name = "ffxiv_ipc_effect",
      length = 120,
    },
  },
  [0x0302] = {
    [0] = {
      name = "ffxiv_ipc_actor_gauge",
      length = 16,
    },
  },
  [0x0323] = {
    [0] = {
      name = "ffxiv_ipc_actor_set_pos",
      length = 20,
    },
  },
  [0x0342] = {
    [0] = {
      name = "ffxiv_ipc_npc_spawn2",
      length = 624,
    },
  },
  [0x035e] = {
    [0] = {
      name = "ffxiv_ipc_player_spawn",
      length = 624,
    },
  },
  [0x0379] = {
    [0] = {
      name = "ffxiv_ipc_effect_result",
      length = 26,
    },
  },
  [0x0382] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect24",
      length = 1784,
    },
  },
  [0x038f] = {
    [0] = {
      name = "ffxiv_ipc_actor_control",
      length = 24,
    },
  },
  [0x03ad] = {
    [0] = {
      name = "ffxiv_ipc_currency_crystal_info",
      length = 32,
    },
  },
  [0x03da] = {
    [0] = {
      name = "ffxiv_ipc_inventory_action_ack",
      length = 16,
    },
  },
}

function M.getDissector(typeNum, length)
  local types = M.types[typeNum]
  if type(types) ~= "table" then
    return nil
  end

  for k, v in pairs(types) do
    if v.length == length then
      return Dissector.get(v.name)
    end
  end

  for k, v in pairs(types) do
    if v.length < length then
      return Dissector.get(v.name)
    end
  end

  return nil
end

return M
