-- This file is generated by network:generate

local M = {}
M.types = {
  [0x0077] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect8",
      length = 632,
    },
  },
  [0x007c] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect32",
      length = 2360,
    },
  },
  [0x0094] = {
    [0] = {
      name = "ffxiv_ipc_item_info",
      length = 64,
    },
  },
  [0x00ad] = {
    [0] = {
      name = "ffxiv_ipc_client_trigger",
      length = 32,
    },
  },
  [0x00b2] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect24",
      length = 1784,
    },
  },
  [0x00d7] = {
    [0] = {
      name = "ffxiv_ipc_player_setup",
      length = 1938,
    },
  },
  [0x00e0] = {
    [0] = {
      name = "ffxiv_ipc_actor_control_target",
      length = 32,
    },
  },
  [0x00ea] = {
    [0] = {
      name = "ffxiv_ipc_update_hp_mp_tp",
      length = 8,
    },
  },
  [0x00f5] = {
    [0] = {
      name = "ffxiv_ipc_ce_director",
      length = 16,
    },
  },
  [0x00fa] = {
    [0] = {
      name = "ffxiv_ipc_boss_status_effect_list",
      length = 740,
    },
  },
  [0x0114] = {
    [0] = {
      name = "ffxiv_ipc_effect_result",
      length = 26,
    },
  },
  [0x011c] = {
    [0] = {
      name = "ffxiv_ipc_object_spawn",
      length = 64,
    },
  },
  [0x013b] = {
    [0] = {
      name = "ffxiv_ipc_actor_move",
      length = 12,
    },
  },
  [0x013e] = {
    [0] = {
      name = "ffxiv_ipc_player_spawn",
      length = 624,
    },
    [1] = {
      name = "ffxiv_ipc_update_position_instance",
      length = 40,
    },
  },
  [0x01a1] = {
    [0] = {
      name = "ffxiv_ipc_actor_cast",
      length = 30,
    },
  },
  [0x01a4] = {
    [0] = {
      name = "ffxiv_ipc_init_zone",
      length = 96,
    },
  },
  [0x01a9] = {
    [0] = {
      name = "ffxiv_ipc_inventory_transaction",
      length = 36,
    },
  },
  [0x01cc] = {
    [0] = {
      name = "ffxiv_ipc_actor_gauge",
      length = 16,
    },
  },
  [0x01e7] = {
    [0] = {
      name = "ffxiv_ipc_effect",
      length = 120,
    },
  },
  [0x0202] = {
    [0] = {
      name = "ffxiv_ipc_actor_set_pos",
      length = 20,
    },
  },
  [0x020d] = {
    [0] = {
      name = "ffxiv_ipc_container_info",
      length = 16,
    },
  },
  [0x020e] = {
    [0] = {
      name = "ffxiv_ipc_fate_info",
      length = 24,
    },
  },
  [0x0212] = {
    [0] = {
      name = "ffxiv_ipc_npc_spawn2",
      length = 624,
    },
  },
  [0x0235] = {
    [0] = {
      name = "ffxiv_ipc_examine",
      length = 656,
    },
  },
  [0x024f] = {
    [0] = {
      name = "ffxiv_ipc_content_finder_notify_pop",
      length = 32,
    },
  },
  [0x0262] = {
    [0] = {
      name = "ffxiv_ipc_currency_crystal_info",
      length = 32,
    },
  },
  [0x0267] = {
    [0] = {
      name = "ffxiv_ipc_company_submersible_status",
      length = 0,
    },
  },
  [0x0273] = {
    [0] = {
      name = "ffxiv_ipc_actor_free_spawn",
      length = 8,
    },
  },
  [0x028c] = {
    [0] = {
      name = "ffxiv_ipc_submarine_status_list",
      length = 240,
    },
  },
  [0x02b3] = {
    [0] = {
      name = "ffxiv_ipc_actor_control_self",
      length = 32,
    },
  },
  [0x02bb] = {
    [0] = {
      name = "ffxiv_ipc_update_class_info",
      length = 16,
    },
  },
  [0x02c8] = {
    [0] = {
      name = "ffxiv_ipc_actor_control",
      length = 24,
    },
  },
  [0x02cd] = {
    [0] = {
      name = "ffxiv_ipc_update_inventory_slot",
      length = 64,
    },
  },
  [0x02e8] = {
    [0] = {
      name = "ffxiv_ipc_npc_spawn",
      length = 624,
    },
  },
  [0x02f0] = {
    [0] = {
      name = "ffxiv_ipc_player_stats",
      length = 120,
    },
  },
  [0x031e] = {
    [0] = {
      name = "ffxiv_ipc_status_effect_list",
      length = 380,
    },
  },
  [0x034d] = {
    [0] = {
      name = "ffxiv_ipc_inventory_transaction_finish",
      length = 16,
    },
  },
  [0x0368] = {
    [0] = {
      name = "ffxiv_ipc_ward_land_info",
      length = 2408,
    },
  },
  [0x038f] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect16",
      length = 1208,
    },
  },
  [0x039b] = {
    [0] = {
      name = "ffxiv_ipc_inventory_action_ack",
      length = 16,
    },
  },
  [0x03c6] = {
    [0] = {
      name = "ffxiv_ipc_company_airship_status",
      length = 0,
    },
  },
  [0x03d4] = {
    [0] = {
      name = "ffxiv_ipc_retainer_information",
      length = 73,
    },
  },
}

function M.getDissector(typeNum, length)
  local types = M.types[typeNum]
  if type(types) ~= "table" then
    return nil
  end

  for k, v in pairs(types) do
    if v.length == length then
      return Dissector.get(v.name)
    end
  end

  for k, v in pairs(types) do
    if v.length < length then
      return Dissector.get(v.name)
    end
  end

  return nil
end

return M
