-- This file is generated by network:generate

local resolver = require("ffxiv_ipc_resolver")
local M = {}
M.types = {
  [0x006b] = {
    [0] = {
      type = "MarketBoardItemListing",
    },
  },
  [0x006d] = {
    [0] = {
      type = "AirshipStatusList",
    },
  },
  [0x007c] = {
    [0] = {
      type = "Logout",
    },
  },
  [0x007d] = {
    [0] = {
      type = "NpcSpawn2",
    },
  },
  [0x0081] = {
    [0] = {
      type = "CurrencyCrystalInfo",
    },
  },
  [0x0091] = {
    [0] = {
      type = "BattleTalk2",
    },
  },
  [0x0099] = {
    [0] = {
      type = "StatusEffectList3",
    },
  },
  [0x00a1] = {
    [0] = {
      type = "EventFinish",
    },
  },
  [0x00a3] = {
    [0] = {
      type = "UpdatePositionHandler",
    },
  },
  [0x00a4] = {
    [0] = {
      type = "ExamineSearchInfo",
    },
  },
  [0x00b3] = {
    [0] = {
      type = "PlaceFieldMarker",
    },
  },
  [0x00bc] = {
    [0] = {
      type = "SubmarineExplorationResult",
    },
  },
  [0x00c2] = {
    [0] = {
      type = "ActorControl",
    },
  },
  [0x00e1] = {
    [0] = {
      type = "EventPlay",
    },
  },
  [0x00e2] = {
    [0] = {
      type = "MarketBoardItemListingCount",
    },
  },
  [0x00e4] = {
    [0] = {
      type = "MarketBoardPurchase",
    },
  },
  [0x00e9] = {
    [0] = {
      type = "NpcYell",
    },
  },
  [0x0102] = {
    [0] = {
      type = "SubmarineStatusList",
    },
  },
  [0x0103] = {
    [0] = {
      type = "MarketBoardItemListingHistory",
    },
  },
  [0x0119] = {
    [0] = {
      type = "StatusEffectList",
    },
  },
  [0x0121] = {
    [0] = {
      type = "UpdateInventorySlot",
    },
  },
  [0x0126] = {
    [0] = {
      type = "RSV",
    },
  },
  [0x0127] = {
    [0] = {
      type = "ActorFreeSpawn",
    },
  },
  [0x012d] = {
    [0] = {
      type = "EnvironmentControl",
    },
  },
  [0x0137] = {
    [0] = {
      type = "ItemMarketBoardInfo",
    },
  },
  [0x013f] = {
    [0] = {
      type = "StatusEffectList2",
    },
  },
  [0x0149] = {
    [0] = {
      type = "CountdownInitiate",
    },
  },
  [0x014c] = {
    [0] = {
      type = "NpcSpawn",
    },
  },
  [0x0163] = {
    [0] = {
      type = "UpdateClassInfo",
    },
  },
  [0x0165] = {
    [0] = {
      type = "Effect",
    },
  },
  [0x0166] = {
    [0] = {
      type = "PlayerSetup",
    },
  },
  [0x016f] = {
    [0] = {
      type = "AoeEffect8",
    },
  },
  [0x017d] = {
    [0] = {
      type = "IslandWorkshopSupplyDemand",
    },
  },
  [0x0195] = {
    [0] = {
      type = "WeatherChange",
    },
  },
  [0x01a9] = {
    [0] = {
      type = "FateInfo",
    },
  },
  [0x01c1] = {
    [0] = {
      type = "ClientTrigger",
    },
  },
  [0x01c3] = {
    [0] = {
      type = "ActorSetPos",
    },
  },
  [0x01cc] = {
    [0] = {
      type = "AirshipStatus",
    },
  },
  [0x01e5] = {
    [0] = {
      type = "WardLandInfo",
    },
  },
  [0x01ea] = {
    [0] = {
      type = "FreeCompanyInfo",
    },
  },
  [0x01ef] = {
    [0] = {
      type = "InventoryActionAck",
    },
  },
  [0x01f0] = {
    [0] = {
      type = "PlayerSpawn",
    },
  },
  [0x01f6] = {
    [0] = {
      type = "InventoryTransaction",
    },
  },
  [0x0205] = {
    [0] = {
      type = "PlayerStats",
    },
  },
  [0x0206] = {
    [0] = {
      type = "AirshipExplorationResult",
    },
  },
  [0x0207] = {
    [0] = {
      type = "ActorGauge",
    },
  },
  [0x0211] = {
    [0] = {
      type = "CountdownCancel",
    },
  },
  [0x0212] = {
    [0] = {
      type = "ActorControlTarget",
    },
  },
  [0x0220] = {
    [0] = {
      type = "ChatHandler",
    },
  },
  [0x0234] = {
    [0] = {
      type = "UpdateHpMpTp",
    },
  },
  [0x0245] = {
    [0] = {
      type = "AoeEffect32",
    },
  },
  [0x024b] = {
    [0] = {
      type = "MarketBoardPurchaseHandler",
    },
  },
  [0x024f] = {
    [0] = {
      type = "EventPlay4",
    },
  },
  [0x025a] = {
    [0] = {
      type = "ObjectSpawn",
    },
  },
  [0x025c] = {
    [0] = {
      type = "InventoryTransactionFinish",
    },
  },
  [0x0265] = {
    [0] = {
      type = "AoeEffect24",
    },
  },
  [0x0267] = {
    [0] = {
      type = "ActorControlSelf",
    },
  },
  [0x026f] = {
    [0] = {
      type = "UpdatePositionInstance",
    },
  },
  [0x0274] = {
    [0] = {
      type = "EventStart",
    },
  },
  [0x027b] = {
    [0] = {
      type = "EffectResult",
    },
  },
  [0x0292] = {
    [0] = {
      type = "CompanySubmersibleStatus",
    },
  },
  [0x0294] = {
    [0] = {
      type = "AoeEffect16",
    },
  },
  [0x029c] = {
    [0] = {
      type = "ContainerInfo",
    },
  },
  [0x029f] = {
    [0] = {
      type = "EventPlay32",
    },
  },
  [0x02a7] = {
    [0] = {
      type = "Playtime",
    },
  },
  [0x02e1] = {
    [0] = {
      type = "CompanyAirshipStatus",
    },
  },
  [0x02ea] = {
    [0] = {
      type = "ContentFinderNotifyPop",
    },
  },
  [0x02fa] = {
    [0] = {
      type = "Examine",
    },
  },
  [0x02fc] = {
    [0] = {
      type = "InventoryHandlerOffset",
    },
    [1] = {
      type = "InventoryModifyHandler",
    },
  },
  [0x02ff] = {
    [0] = {
      type = "CEDirector",
    },
  },
  [0x030e] = {
    [0] = {
      type = "SetSearchInfoHandler",
    },
  },
  [0x0316] = {
    [0] = {
      type = "SystemLogMessage",
    },
  },
  [0x0325] = {
    [0] = {
      type = "ResumeEventScene16",
    },
  },
  [0x0328] = {
    [0] = {
      type = "UpdateSearchInfo",
    },
  },
  [0x0333] = {
    [0] = {
      type = "RetainerInformation",
    },
  },
  [0x0349] = {
    [0] = {
      type = "BossStatusEffectList",
    },
  },
  [0x0359] = {
    [0] = {
      type = "CFPreferredRole",
    },
  },
  [0x0365] = {
    [0] = {
      type = "EffectResultBasic",
    },
  },
  [0x036b] = {
    [0] = {
      type = "ItemInfo",
    },
  },
  [0x036e] = {
    [0] = {
      type = "ActorCast",
    },
  },
  [0x0370] = {
    [0] = {
      type = "SubmarineProgressionStatus",
    },
  },
  [0x0371] = {
    [0] = {
      type = "PrepareZoning",
    },
  },
  [0x0376] = {
    [0] = {
      type = "PlaceFieldMarkerPreset",
    },
  },
  [0x039f] = {
    [0] = {
      type = "MarketBoardSearchResult",
    },
  },
  [0x03b1] = {
    [0] = {
      type = "ResumeEventScene32",
    },
  },
  [0x03b4] = {
    [0] = {
      type = "InitZone",
    },
  },
  [0x03cd] = {
    [0] = {
      type = "FreeCompanyDialog",
    },
  },
  [0x03dd] = {
    [0] = {
      type = "ActorMove",
    },
  },
}

function M.getDissector(typeNum, length, direction)
  return resolver.getDissector(M.types[typeNum], length, direction)
end

return M
