-- This file is generated by network:generate

local ffxiv_ipc_first_attack = Proto("ffxiv_ipc_first_attack", "FFXIV-IPC FirstAttack")

local first_attack_fields = {
  type     = ProtoField.uint8("ffxiv_ipc_first_attack.type", "type", base.DEC),
  unknown  = ProtoField.bytes("ffxiv_ipc_first_attack.unknown", "unknown", base.NONE),
  actor_id = ProtoField.uint64("ffxiv_ipc_first_attack.actor_id", "actorId", base.DEC),
}

ffxiv_ipc_first_attack.fields = first_attack_fields

function ffxiv_ipc_first_attack.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_first_attack, tvbuf)
  local len = tvbuf:len()
  if len < 16 then
    tree:add_expert_info(PI_MALFORMED, PI_ERROR, "Truncated FirstAttack payload")
    return len
  end

  -- dissect the type field
  local type_tvbr = tvbuf:range(0, 1)
  local type_val  = type_tvbr:le_uint()
  tree:add_le(first_attack_fields.type, type_tvbr, type_val)

  -- dissect the unknown field
  local unknown_tvbr = tvbuf:range(1, 7)
  local unknown_val  = unknown_tvbr:raw()
  tree:add(first_attack_fields.unknown, unknown_tvbr, unknown_val)

  -- dissect the actor_id field
  local actor_id_tvbr = tvbuf:range(8, 8)
  local actor_id_val  = actor_id_tvbr:le_uint64()
  tree:add_le(first_attack_fields.actor_id, actor_id_tvbr, actor_id_val)

  return len
end
