-- This file is generated by network:generate

local ffxiv_ipc_player_setup_hunts = Proto("ffxiv_ipc_player_setup_hunts", "FFXIV-IPC PlayerSetupHunts")

local player_setup_hunts_fields = {
  daily_available_id                = ProtoField.uint8("ffxiv_ipc_player_setup_hunts.daily_available_id", "dailyAvailableId", base.DEC),
  daily_obtained_id_and_flags       = ProtoField.uint8("ffxiv_ipc_player_setup_hunts.daily_obtained_id_and_flags", "dailyObtainedIdAndFlags", base.DEC),
  elite_obtained_id_and_flags       = ProtoField.uint8("ffxiv_ipc_player_setup_hunts.elite_obtained_id_and_flags", "eliteObtainedIdAndFlags", base.DEC),
  daily_kill_counts                 = ProtoField.uint8("ffxiv_ipc_player_setup_hunts.daily_kill_counts", "dailyKillCounts", base.DEC),
  elite_available_id_and_kill_count = ProtoField.uint8("ffxiv_ipc_player_setup_hunts.elite_available_id_and_kill_count", "eliteAvailableIdAndKillCount", base.DEC),
}

ffxiv_ipc_player_setup_hunts.fields = player_setup_hunts_fields

function ffxiv_ipc_player_setup_hunts.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_player_setup_hunts, tvbuf)
  local len = tvbuf:len()
  if len < 124 then
    tree:add_expert_info(PI_MALFORMED, PI_ERROR, "Truncated PlayerSetupHunts payload")
    return len
  end

  -- dissect the daily_available_id field
  local daily_available_id_tvbr = tvbuf:range(0, 1)
  local daily_available_id_val  = daily_available_id_tvbr:le_uint()
  tree:add_le(player_setup_hunts_fields.daily_available_id, daily_available_id_tvbr, daily_available_id_val)

  -- dissect the daily_obtained_id_and_flags field
  local daily_obtained_id_and_flags_tvbr = tvbuf:range(1, 1)
  local daily_obtained_id_and_flags_val  = daily_obtained_id_and_flags_tvbr:le_uint()
  tree:add_le(player_setup_hunts_fields.daily_obtained_id_and_flags, daily_obtained_id_and_flags_tvbr, daily_obtained_id_and_flags_val)

  -- dissect the elite_obtained_id_and_flags field
  local elite_obtained_id_and_flags_tvbr = tvbuf:range(2, 1)
  local elite_obtained_id_and_flags_val  = elite_obtained_id_and_flags_tvbr:le_uint()
  tree:add_le(player_setup_hunts_fields.elite_obtained_id_and_flags, elite_obtained_id_and_flags_tvbr, elite_obtained_id_and_flags_val)

  -- dissect the daily_kill_counts field
  local daily_kill_counts_pos = 3
  local daily_kill_counts_len = 1
  local daily_kill_counts_count = 5

  while daily_kill_counts_pos + daily_kill_counts_len <= len do
    local daily_kill_counts_tvbr = tvbuf:range(daily_kill_counts_pos, daily_kill_counts_len)
    local daily_kill_counts_val  = daily_kill_counts_tvbr:le_uint()
    tree:add_le(player_setup_hunts_fields.daily_kill_counts, daily_kill_counts_tvbr, daily_kill_counts_val)
    daily_kill_counts_pos = daily_kill_counts_pos + daily_kill_counts_len
    daily_kill_counts_count = daily_kill_counts_count - 1
    if daily_kill_counts_count <= 0 then
      break
    end
  end

  -- dissect the elite_available_id_and_kill_count field
  local elite_available_id_and_kill_count_tvbr = tvbuf:range(8, 1)
  local elite_available_id_and_kill_count_val  = elite_available_id_and_kill_count_tvbr:le_uint()
  tree:add_le(player_setup_hunts_fields.elite_available_id_and_kill_count, elite_available_id_and_kill_count_tvbr, elite_available_id_and_kill_count_val)

  -- dissect groups
  local groups_dissector = Dissector.get('ffxiv_ipc_player_setup_hunt_group')
  local groups_pos = 9
  local groups_len = 23
  local groups_count = 5

  while groups_pos + groups_len <= len do
    local groups_tvbr = tvbuf:range(groups_pos, 23)
    groups_dissector:call(groups_tvbr:tvb(), pktinfo, root)
    groups_pos = groups_pos + groups_len
    groups_count = groups_count - 1
    if groups_count <= 0 then
      break
    end
  end

  return len
end
