-- This file is generated by network:generate

local resolver = require("ffxiv_ipc_resolver")
local M = {}
M.types = {
  [0x00a4] = {
    [0] = {
      type = "CFPreferredRole",
    },
  },
  [0x00b4] = {
    [0] = {
      type = "BossStatusEffectList",
    },
    [1] = {
      type = "StatusEffectList",
    },
  },
  [0x00bd] = {
    [0] = {
      type = "Examine",
    },
  },
  [0x00be] = {
    [0] = {
      type = "MarketBoardItemListingCount",
    },
  },
  [0x00ff] = {
    [0] = {
      type = "AoeEffect32",
    },
  },
  [0x0105] = {
    [0] = {
      type = "Playtime",
    },
  },
  [0x010e] = {
    [0] = {
      type = "EventStart",
    },
  },
  [0x011e] = {
    [0] = {
      type = "RetainerInformation",
    },
  },
  [0x0128] = {
    [0] = {
      type = "NpcSpawn2",
    },
  },
  [0x0131] = {
    [0] = {
      type = "CurrencyCrystalInfo",
    },
  },
  [0x0139] = {
    [0] = {
      type = "AoeEffect16",
    },
  },
  [0x013c] = {
    [0] = {
      type = "UpdateInventorySlot",
    },
  },
  [0x016d] = {
    [0] = {
      type = "ContentFinderNotifyPop",
    },
  },
  [0x0179] = {
    [0] = {
      type = "ActorControlSelf",
    },
  },
  [0x0184] = {
    [0] = {
      type = "NpcSpawn",
    },
  },
  [0x01b1] = {
    [0] = {
      type = "AoeEffect8",
    },
  },
  [0x01b9] = {
    [0] = {
      type = "EventFinish",
    },
  },
  [0x0202] = {
    [0] = {
      type = "InventoryTransaction",
    },
  },
  [0x0214] = {
    [0] = {
      type = "EventPlay4",
    },
  },
  [0x0216] = {
    [0] = {
      type = "EventPlay",
    },
  },
  [0x021b] = {
    [0] = {
      type = "ResumeEventScene32",
    },
  },
  [0x0236] = {
    [0] = {
      type = "ExamineSearchInfo",
    },
  },
  [0x0237] = {
    [0] = {
      type = "EffectResult",
    },
  },
  [0x023b] = {
    [0] = {
      type = "SetSearchInfoHandler",
    },
  },
  [0x023e] = {
    [0] = {
      type = "Effect",
    },
  },
  [0x0251] = {
    [0] = {
      type = "MarketBoardSearchResult",
    },
  },
  [0x025f] = {
    [0] = {
      type = "ClientTrigger",
    },
  },
  [0x0261] = {
    [0] = {
      type = "ActorSetPos",
    },
  },
  [0x0268] = {
    [0] = {
      type = "ItemInfo",
    },
  },
  [0x028a] = {
    [0] = {
      type = "ContainerInfo",
    },
  },
  [0x029d] = {
    [0] = {
      type = "PlayerSpawn",
    },
  },
  [0x02b4] = {
    [0] = {
      type = "MarketBoardItemListingHistory",
    },
  },
  [0x02be] = {
    [0] = {
      type = "SystemLogMessage",
    },
  },
  [0x02c5] = {
    [0] = {
      type = "ChatHandler",
    },
  },
  [0x0311] = {
    [0] = {
      type = "UpdateSearchInfo",
    },
  },
  [0x032c] = {
    [0] = {
      type = "ActorCast",
    },
  },
  [0x0345] = {
    [0] = {
      type = "InitZone",
    },
  },
  [0x034a] = {
    [0] = {
      type = "UpdateHpMpTp",
    },
  },
  [0x0350] = {
    [0] = {
      type = "ActorGauge",
    },
  },
  [0x0366] = {
    [0] = {
      type = "ActorControl",
    },
  },
  [0x0376] = {
    [0] = {
      type = "PlayerSetup",
    },
  },
  [0x0378] = {
    [0] = {
      type = "InventoryTransactionFinish",
    },
  },
  [0x038b] = {
    [0] = {
      type = "AoeEffect24",
    },
  },
  [0x038f] = {
    [0] = {
      type = "InventoryModifyHandler",
    },
  },
  [0x0399] = {
    [0] = {
      type = "StatusEffectList2",
    },
  },
  [0x039e] = {
    [0] = {
      type = "ActorMove",
    },
  },
  [0x03c5] = {
    [0] = {
      type = "UpdateClassInfo",
    },
  },
  [0x03cb] = {
    [0] = {
      type = "MarketBoardItemListing",
    },
  },
}

function M.getDissector(typeNum, length, direction)
  return resolver.getDissector(M.types[typeNum], length, direction)
end

return M
