-- This file is generated by network:generate

local resolver = require("ffxiv_ipc_resolver")
local M = {}
M.types = {
  [0x0065] = {
    [0] = {
      type = "EffectResult",
    },
  },
  [0x0070] = {
    [0] = {
      type = "UpdateInventorySlot",
    },
  },
  [0x007c] = {
    [0] = {
      type = "ActorControlSelf",
    },
  },
  [0x0084] = {
    [0] = {
      type = "AoeEffect16",
    },
  },
  [0x0087] = {
    [0] = {
      type = "ResumeEventScene16",
    },
  },
  [0x0095] = {
    [0] = {
      type = "RetainerInformation",
    },
  },
  [0x00a8] = {
    [0] = {
      type = "InventoryTransaction",
    },
  },
  [0x00b3] = {
    [0] = {
      type = "NpcSpawn",
    },
  },
  [0x00d1] = {
    [0] = {
      type = "PlayerSpawn",
    },
  },
  [0x00f5] = {
    [0] = {
      type = "ActorGauge",
    },
  },
  [0x00f8] = {
    [0] = {
      type = "ActorMove",
    },
  },
  [0x0121] = {
    [0] = {
      type = "UpdateSearchInfo",
    },
  },
  [0x0144] = {
    [0] = {
      type = "CEDirector",
    },
  },
  [0x0146] = {
    [0] = {
      type = "EventStart",
    },
  },
  [0x014d] = {
    [0] = {
      type = "PlaceFieldMarker",
    },
  },
  [0x0158] = {
    [0] = {
      type = "MarketBoardItemListing",
    },
  },
  [0x0173] = {
    [0] = {
      type = "ChatHandler",
    },
  },
  [0x0179] = {
    [0] = {
      type = "ObjectSpawn",
    },
  },
  [0x019f] = {
    [0] = {
      type = "ActorCast",
    },
  },
  [0x01a1] = {
    [0] = {
      type = "PrepareZoning",
    },
  },
  [0x01ae] = {
    [0] = {
      type = "SetSearchInfoHandler",
    },
  },
  [0x01b8] = {
    [0] = {
      type = "PlaceFieldMarkerPreset",
    },
  },
  [0x01b9] = {
    [0] = {
      type = "EventPlay",
    },
  },
  [0x01c4] = {
    [0] = {
      type = "ExamineSearchInfo",
    },
  },
  [0x01d4] = {
    [0] = {
      type = "AoeEffect8",
    },
  },
  [0x01d7] = {
    [0] = {
      type = "ContainerInfo",
    },
  },
  [0x01f3] = {
    [0] = {
      type = "MarketBoardItemListingHistory",
    },
  },
  [0x01f4] = {
    [0] = {
      type = "ActorControlTarget",
    },
  },
  [0x01f9] = {
    [0] = {
      type = "PlayerSetup",
    },
  },
  [0x0243] = {
    [0] = {
      type = "AoeEffect24",
    },
  },
  [0x0250] = {
    [0] = {
      type = "UpdatePositionInstance",
    },
  },
  [0x0271] = {
    [0] = {
      type = "CompanyAirshipStatus",
    },
  },
  [0x0279] = {
    [0] = {
      type = "ActorSetPos",
    },
  },
  [0x027c] = {
    [0] = {
      type = "ActorControl",
    },
  },
  [0x0280] = {
    [0] = {
      type = "MarketBoardItemListingCount",
    },
  },
  [0x0283] = {
    [0] = {
      type = "UpdatePositionHandler",
    },
  },
  [0x02ac] = {
    [0] = {
      type = "Playtime",
    },
  },
  [0x02b1] = {
    [0] = {
      type = "UpdateClassInfo",
    },
  },
  [0x02b5] = {
    [0] = {
      type = "EventFinish",
    },
  },
  [0x02b9] = {
    [0] = {
      type = "ActorFreeSpawn",
    },
    [1] = {
      type = "UpdateHpMpTp",
    },
  },
  [0x02d0] = {
    [0] = {
      type = "ContentFinderNotifyPop",
    },
  },
  [0x02d2] = {
    [0] = {
      type = "InitZone",
    },
  },
  [0x02f2] = {
    [0] = {
      type = "ResumeEventScene32",
    },
  },
  [0x02f6] = {
    [0] = {
      type = "InventoryTransactionFinish",
    },
  },
  [0x02fb] = {
    [0] = {
      type = "Effect",
    },
  },
  [0x0309] = {
    [0] = {
      type = "PlayerStats",
    },
  },
  [0x0316] = {
    [0] = {
      type = "Examine",
    },
  },
  [0x031a] = {
    [0] = {
      type = "ItemInfo",
    },
  },
  [0x0343] = {
    [0] = {
      type = "Logout",
    },
  },
  [0x0344] = {
    [0] = {
      type = "InventoryActionAck",
    },
  },
  [0x0345] = {
    [0] = {
      type = "CompanySubmersibleStatus",
    },
  },
  [0x0356] = {
    [0] = {
      type = "EventPlay4",
    },
  },
  [0x036b] = {
    [0] = {
      type = "StatusEffectList",
    },
  },
  [0x037b] = {
    [0] = {
      type = "SystemLogMessage",
    },
  },
  [0x037c] = {
    [0] = {
      type = "CurrencyCrystalInfo",
    },
  },
  [0x0390] = {
    [0] = {
      type = "MarketBoardSearchResult",
    },
  },
  [0x039f] = {
    [0] = {
      type = "AoeEffect32",
    },
  },
  [0x03a6] = {
    [0] = {
      type = "InventoryModifyHandler",
    },
  },
  [0x03ad] = {
    [0] = {
      type = "WardLandInfo",
    },
  },
  [0x03dd] = {
    [0] = {
      type = "ClientTrigger",
    },
  },
}

function M.getDissector(typeNum, length, direction)
  return resolver.getDissector(M.types[typeNum], length, direction)
end

return M
