-- This file is generated by network:generate

local db = require('ffxiv_db')
local enum = require('ffxiv_enum')

local ffxiv_ipc_actor_cast = Proto("ffxiv_ipc_actor_cast", "FFXIV-IPC ActorCast")

local actor_cast_fields = {
  action     = ProtoField.uint16("ffxiv_ipc_actor_cast.action", "action", base.DEC, db.Action),
  skill_type = ProtoField.uint8("ffxiv_ipc_actor_cast.skill_type", "skillType", base.DEC, enum.reverse.actor_cast_skill_type),
  item_id    = ProtoField.uint32("ffxiv_ipc_actor_cast.item_id", "itemId", base.DEC, db.Item),
  cast_time  = ProtoField.float("ffxiv_ipc_actor_cast.cast_time", "castTime", base.DEC),
  target_id  = ProtoField.uint32("ffxiv_ipc_actor_cast.target_id", "targetId", base.HEX),
  rotation   = ProtoField.float("ffxiv_ipc_actor_cast.rotation", "rotation", base.DEC),
  x          = ProtoField.uint16("ffxiv_ipc_actor_cast.x", "x", base.DEC),
  y          = ProtoField.uint16("ffxiv_ipc_actor_cast.y", "y", base.DEC),
  z          = ProtoField.uint16("ffxiv_ipc_actor_cast.z", "z", base.DEC),
}

ffxiv_ipc_actor_cast.fields = actor_cast_fields

function ffxiv_ipc_actor_cast.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_actor_cast, tvbuf)
  local len = tvbuf:len()

  -- dissect the action field
  local action_tvbr = tvbuf:range(0, 2)
  local action_val  = action_tvbr:le_uint()
  tree:add_le(actor_cast_fields.action, action_tvbr, action_val)

  -- dissect the skill_type field
  local skill_type_tvbr = tvbuf:range(2, 1)
  local skill_type_val  = skill_type_tvbr:le_uint()
  tree:add_le(actor_cast_fields.skill_type, skill_type_tvbr, skill_type_val)

  -- dissect the item_id field
  local item_id_tvbr = tvbuf:range(4, 4)
  local item_id_val  = item_id_tvbr:le_uint()
  tree:add_le(actor_cast_fields.item_id, item_id_tvbr, item_id_val)

  -- dissect the cast_time field
  local cast_time_tvbr = tvbuf:range(8, 4)
  local cast_time_val  = cast_time_tvbr:le_float()
  tree:add_le(actor_cast_fields.cast_time, cast_time_tvbr, cast_time_val)

  -- dissect the target_id field
  local target_id_tvbr = tvbuf:range(12, 4)
  local target_id_val  = target_id_tvbr:le_uint()
  tree:add_le(actor_cast_fields.target_id, target_id_tvbr, target_id_val)

  -- dissect the rotation field
  local rotation_tvbr = tvbuf:range(16, 4)
  local rotation_val  = rotation_tvbr:le_float()
  tree:add_le(actor_cast_fields.rotation, rotation_tvbr, rotation_val)

  -- dissect the x field
  local x_tvbr = tvbuf:range(24, 2)
  local x_val  = x_tvbr:le_uint()
  tree:add_le(actor_cast_fields.x, x_tvbr, x_val)

  -- dissect the y field
  local y_tvbr = tvbuf:range(26, 2)
  local y_val  = y_tvbr:le_uint()
  tree:add_le(actor_cast_fields.y, y_tvbr, y_val)

  -- dissect the z field
  local z_tvbr = tvbuf:range(28, 2)
  local z_val  = z_tvbr:le_uint()
  tree:add_le(actor_cast_fields.z, z_tvbr, z_val)

  return len
end
