-- This file is generated by network:generate

local resolver = require("ffxiv_ipc_resolver")
local M = {}
M.types = {
  [0x006d] = {
    [0] = {
      type = "Examine",
    },
  },
  [0x0082] = {
    [0] = {
      type = "CompanySubmersibleStatus",
    },
  },
  [0x0084] = {
    [0] = {
      type = "ActorSetPos",
    },
  },
  [0x008b] = {
    [0] = {
      type = "InitZone",
    },
  },
  [0x008c] = {
    [0] = {
      type = "UpdateSearchInfo",
    },
  },
  [0x00af] = {
    [0] = {
      type = "Logout",
    },
  },
  [0x00b0] = {
    [0] = {
      type = "ChatHandler",
    },
  },
  [0x00ce] = {
    [0] = {
      type = "ActorMove",
    },
  },
  [0x00cf] = {
    [0] = {
      type = "ContentFinderNotifyPop",
    },
  },
  [0x00da] = {
    [0] = {
      type = "StatusEffectList2",
    },
  },
  [0x00e4] = {
    [0] = {
      type = "CEDirector",
    },
  },
  [0x00e5] = {
    [0] = {
      type = "PlaceFieldMarkerPreset",
    },
  },
  [0x00e7] = {
    [0] = {
      type = "NpcSpawn",
    },
  },
  [0x00eb] = {
    [0] = {
      type = "FreeCompanyDialog",
    },
  },
  [0x00ec] = {
    [0] = {
      type = "UpdateClassInfo",
    },
  },
  [0x00ef] = {
    [0] = {
      type = "AoeEffect8",
    },
  },
  [0x0116] = {
    [0] = {
      type = "EffectResultBasic",
    },
  },
  [0x012b] = {
    [0] = {
      type = "Playtime",
    },
  },
  [0x012c] = {
    [0] = {
      type = "AirshipExplorationResult",
    },
  },
  [0x0130] = {
    [0] = {
      type = "ResumeEventScene32",
    },
  },
  [0x0144] = {
    [0] = {
      type = "MarketBoardPurchase",
    },
  },
  [0x0151] = {
    [0] = {
      type = "SetSearchInfoHandler",
    },
  },
  [0x0164] = {
    [0] = {
      type = "UpdatePositionHandler",
    },
  },
  [0x0178] = {
    [0] = {
      type = "PlayerSetup",
    },
  },
  [0x017b] = {
    [0] = {
      type = "PlaceFieldMarker",
    },
  },
  [0x017c] = {
    [0] = {
      type = "AirshipStatus",
    },
  },
  [0x0180] = {
    [0] = {
      type = "CompanyAirshipStatus",
    },
  },
  [0x018f] = {
    [0] = {
      type = "NpcSpawn2",
    },
  },
  [0x0197] = {
    [0] = {
      type = "SystemLogMessage",
    },
  },
  [0x01a7] = {
    [0] = {
      type = "SubmarineProgressionStatus",
    },
  },
  [0x01ac] = {
    [0] = {
      type = "AirshipStatusList",
    },
  },
  [0x01c1] = {
    [0] = {
      type = "IslandWorkshopSupplyDemand",
    },
  },
  [0x01d6] = {
    [0] = {
      type = "ObjectSpawn",
    },
  },
  [0x01de] = {
    [0] = {
      type = "SubmarineExplorationResult",
    },
  },
  [0x01e4] = {
    [0] = {
      type = "MarketBoardSearchResult",
    },
  },
  [0x01ec] = {
    [0] = {
      type = "EventFinish",
    },
  },
  [0x01fb] = {
    [0] = {
      type = "CFPreferredRole",
    },
  },
  [0x01ff] = {
    [0] = {
      type = "ActorControlTarget",
    },
  },
  [0x0200] = {
    [0] = {
      type = "ItemMarketBoardInfo",
    },
  },
  [0x0207] = {
    [0] = {
      type = "InventoryTransactionFinish",
    },
  },
  [0x0208] = {
    [0] = {
      type = "FateInfo",
    },
  },
  [0x020e] = {
    [0] = {
      type = "RetainerInformation",
    },
  },
  [0x022b] = {
    [0] = {
      type = "MarketBoardItemListing",
    },
  },
  [0x022e] = {
    [0] = {
      type = "ActorGauge",
    },
  },
  [0x022f] = {
    [0] = {
      type = "FreeCompanyInfo",
    },
  },
  [0x0243] = {
    [0] = {
      type = "ContainerInfo",
    },
  },
  [0x0249] = {
    [0] = {
      type = "ActorControl",
    },
  },
  [0x024b] = {
    [0] = {
      type = "EnvironmentControl",
    },
  },
  [0x029f] = {
    [0] = {
      type = "PlayerSpawn",
    },
  },
  [0x02ad] = {
    [0] = {
      type = "WardLandInfo",
    },
  },
  [0x02b5] = {
    [0] = {
      type = "EventPlay4",
    },
  },
  [0x02bb] = {
    [0] = {
      type = "EventStart",
    },
  },
  [0x02be] = {
    [0] = {
      type = "EventPlay",
    },
  },
  [0x02e6] = {
    [0] = {
      type = "AoeEffect32",
    },
  },
  [0x02e7] = {
    [0] = {
      type = "Effect",
    },
  },
  [0x02f1] = {
    [0] = {
      type = "InventoryTransaction",
    },
  },
  [0x02f2] = {
    [0] = {
      type = "StatusEffectList",
    },
  },
  [0x02f9] = {
    [0] = {
      type = "ResumeEventScene16",
    },
  },
  [0x030a] = {
    [0] = {
      type = "InventoryActionAck",
    },
  },
  [0x030e] = {
    [0] = {
      type = "EffectResult",
    },
  },
  [0x030f] = {
    [0] = {
      type = "CurrencyCrystalInfo",
    },
  },
  [0x032a] = {
    [0] = {
      type = "PlayerStats",
    },
  },
  [0x0331] = {
    [0] = {
      type = "SubmarineStatusList",
    },
  },
  [0x033b] = {
    [0] = {
      type = "ActorCast",
    },
  },
  [0x0350] = {
    [0] = {
      type = "UpdateInventorySlot",
    },
  },
  [0x0369] = {
    [0] = {
      type = "InventoryHandlerOffset",
    },
    [1] = {
      type = "InventoryModifyHandler",
    },
  },
  [0x036f] = {
    [0] = {
      type = "AoeEffect16",
    },
  },
  [0x0371] = {
    [0] = {
      type = "ExamineSearchInfo",
    },
  },
  [0x0383] = {
    [0] = {
      type = "MarketBoardPurchaseHandler",
    },
  },
  [0x0387] = {
    [0] = {
      type = "ClientTrigger",
    },
  },
  [0x0391] = {
    [0] = {
      type = "BossStatusEffectList",
    },
  },
  [0x0397] = {
    [0] = {
      type = "ActorControlSelf",
    },
  },
  [0x0398] = {
    [0] = {
      type = "ItemInfo",
    },
  },
  [0x0399] = {
    [0] = {
      type = "UpdateHpMpTp",
    },
  },
  [0x03ac] = {
    [0] = {
      type = "PrepareZoning",
    },
  },
  [0x03b6] = {
    [0] = {
      type = "UpdatePositionInstance",
    },
  },
  [0x03bc] = {
    [0] = {
      type = "MarketBoardItemListingHistory",
    },
  },
  [0x03c4] = {
    [0] = {
      type = "AoeEffect24",
    },
  },
  [0x03cd] = {
    [0] = {
      type = "StatusEffectList3",
    },
  },
  [0x03e4] = {
    [0] = {
      type = "MarketBoardItemListingCount",
    },
  },
}

function M.getDissector(typeNum, length, direction)
  return resolver.getDissector(M.types[typeNum], length, direction)
end

return M
