-- This file is generated by network:generate

local M = {}
M.types = {
  [0x0071] = {
    [0] = {
      title = "RetainerInformation",
      name = "ffxiv_ipc_retainer_information",
      length = 73,
    },
  },
  [0x0076] = {
    [0] = {
      title = "AoeEffect32",
      name = "ffxiv_ipc_aoe_effect32",
      length = 2360,
    },
  },
  [0x007b] = {
    [0] = {
      title = "NpcSpawn",
      name = "ffxiv_ipc_npc_spawn",
      length = 624,
    },
  },
  [0x008c] = {
    [0] = {
      title = "PrepareZoning",
    },
  },
  [0x0096] = {
    [0] = {
      title = "EffectResultBasic",
    },
  },
  [0x009b] = {
    [0] = {
      title = "UpdateInventorySlot",
      name = "ffxiv_ipc_update_inventory_slot",
      length = 64,
    },
  },
  [0x009c] = {
    [0] = {
      title = "Examine",
      name = "ffxiv_ipc_examine",
      length = 656,
    },
  },
  [0x00a7] = {
    [0] = {
      title = "CurrencyCrystalInfo",
      name = "ffxiv_ipc_currency_crystal_info",
      length = 32,
    },
  },
  [0x00b0] = {
    [0] = {
      title = "ContainerInfo",
      name = "ffxiv_ipc_container_info",
      length = 16,
    },
  },
  [0x00b2] = {
    [0] = {
      title = "MarketBoardItemListingHistory",
    },
  },
  [0x00b5] = {
    [0] = {
      title = "SubmarineExplorationResult",
    },
  },
  [0x00b6] = {
    [0] = {
      title = "AirshipStatus",
    },
  },
  [0x00bd] = {
    [0] = {
      title = "MarketBoardItemListingCount",
    },
  },
  [0x00c1] = {
    [0] = {
      title = "ActorControlTarget",
      name = "ffxiv_ipc_actor_control_target",
      length = 32,
    },
  },
  [0x00da] = {
    [0] = {
      title = "AirshipStatusList",
    },
  },
  [0x00ff] = {
    [0] = {
      title = "ActorControl",
      name = "ffxiv_ipc_actor_control",
      length = 24,
    },
  },
  [0x0100] = {
    [0] = {
      title = "Effect",
      name = "ffxiv_ipc_effect",
      length = 120,
    },
  },
  [0x0103] = {
    [0] = {
      title = "AoeEffect24",
      name = "ffxiv_ipc_aoe_effect24",
      length = 1784,
    },
  },
  [0x010a] = {
    [0] = {
      title = "MarketBoardSearchResult",
    },
  },
  [0x0113] = {
    [0] = {
      title = "ActorGauge",
      name = "ffxiv_ipc_actor_gauge",
      length = 16,
    },
  },
  [0x012a] = {
    [0] = {
      title = "ActorSetPos",
      name = "ffxiv_ipc_actor_set_pos",
      length = 20,
    },
  },
  [0x012e] = {
    [0] = {
      title = "PlaceFieldMarker",
      name = "ffxiv_ipc_place_field_marker",
      length = 16,
    },
  },
  [0x0140] = {
    [0] = {
      title = "UpdateSearchInfo",
    },
  },
  [0x0153] = {
    [0] = {
      title = "ResumeEventScene16",
    },
  },
  [0x0155] = {
    [0] = {
      title = "ActorCast",
      name = "ffxiv_ipc_actor_cast",
      length = 30,
    },
  },
  [0x0158] = {
    [0] = {
      title = "StatusEffectList2",
    },
  },
  [0x0163] = {
    [0] = {
      title = "InitZone",
      name = "ffxiv_ipc_init_zone",
      length = 96,
    },
  },
  [0x0199] = {
    [0] = {
      title = "EventPlay4",
    },
  },
  [0x01a7] = {
    [0] = {
      title = "NpcSpawn2",
      name = "ffxiv_ipc_npc_spawn2",
      length = 624,
    },
  },
  [0x01ad] = {
    [0] = {
      title = "CEDirector",
      name = "ffxiv_ipc_ce_director",
      length = 16,
    },
  },
  [0x01bb] = {
    [0] = {
      title = "PlayerSetup",
      name = "ffxiv_ipc_player_setup",
      length = 1938,
    },
  },
  [0x01bd] = {
    [0] = {
      title = "ObjectSpawn",
      name = "ffxiv_ipc_object_spawn",
      length = 64,
    },
  },
  [0x01c1] = {
    [0] = {
      title = "Playtime",
    },
  },
  [0x01c5] = {
    [0] = {
      title = "MarketBoardPurchase",
    },
  },
  [0x01c7] = {
    [0] = {
      title = "ActorMove",
      name = "ffxiv_ipc_actor_move",
      length = 12,
    },
  },
  [0x01d1] = {
    [0] = {
      title = "FreeCompanyDialog",
    },
  },
  [0x01e9] = {
    [0] = {
      title = "ChatHandler",
    },
  },
  [0x01ef] = {
    [0] = {
      title = "MarketBoardPurchaseHandler",
    },
  },
  [0x01fe] = {
    [0] = {
      title = "InventoryTransactionFinish",
      name = "ffxiv_ipc_inventory_transaction_finish",
      length = 16,
    },
  },
  [0x0203] = {
    [0] = {
      title = "SetSearchInfoHandler",
    },
  },
  [0x0208] = {
    [0] = {
      title = "PlayerSpawn",
      name = "ffxiv_ipc_player_spawn",
      length = 624,
    },
  },
  [0x0216] = {
    [0] = {
      title = "SubmarineStatusList",
      name = "ffxiv_ipc_submarine_status_list",
      length = 240,
    },
  },
  [0x022c] = {
    [0] = {
      title = "EventStart",
    },
  },
  [0x0230] = {
    [0] = {
      title = "ContentFinderNotifyPop",
      name = "ffxiv_ipc_content_finder_notify_pop",
      length = 32,
    },
  },
  [0x0233] = {
    [0] = {
      title = "SubmarineProgressionStatus",
    },
  },
  [0x0236] = {
    [0] = {
      title = "UpdateHpMpTp",
      name = "ffxiv_ipc_update_hp_mp_tp",
      length = 8,
    },
  },
  [0x0242] = {
    [0] = {
      title = "AoeEffect16",
      name = "ffxiv_ipc_aoe_effect16",
      length = 1208,
    },
  },
  [0x0249] = {
    [0] = {
      title = "WardLandInfo",
      name = "ffxiv_ipc_ward_land_info",
      length = 2408,
    },
  },
  [0x024d] = {
    [0] = {
      title = "MarketBoardItemListing",
    },
  },
  [0x027c] = {
    [0] = {
      title = "ResumeEventScene32",
    },
  },
  [0x0281] = {
    [0] = {
      title = "SystemLogMessage",
    },
  },
  [0x028e] = {
    [0] = {
      title = "CompanySubmersibleStatus",
      name = "ffxiv_ipc_company_submersible_status",
      length = 0,
    },
  },
  [0x028f] = {
    [0] = {
      title = "StatusEffectList",
      name = "ffxiv_ipc_status_effect_list",
      length = 380,
    },
  },
  [0x0296] = {
    [0] = {
      title = "CompanyAirshipStatus",
      name = "ffxiv_ipc_company_airship_status",
      length = 0,
    },
  },
  [0x0299] = {
    [0] = {
      title = "PlaceFieldMarkerPreset",
    },
  },
  [0x02a2] = {
    [0] = {
      title = "ItemMarketBoardInfo",
    },
  },
  [0x02ac] = {
    [0] = {
      title = "InventoryHandlerOffset",
    },
    [1] = {
      title = "InventoryModifyHandler",
    },
  },
  [0x02b5] = {
    [0] = {
      title = "AirshipExplorationResult",
    },
  },
  [0x02c9] = {
    [0] = {
      title = "ExamineSearchInfo",
    },
  },
  [0x02ce] = {
    [0] = {
      title = "PlayerStats",
      name = "ffxiv_ipc_player_stats",
      length = 120,
    },
  },
  [0x02d9] = {
    [0] = {
      title = "StatusEffectList3",
    },
  },
  [0x02dd] = {
    [0] = {
      title = "ItemInfo",
      name = "ffxiv_ipc_item_info",
      length = 64,
    },
  },
  [0x02e5] = {
    [0] = {
      title = "EventPlay",
    },
  },
  [0x02ef] = {
    [0] = {
      title = "InventoryTransaction",
      name = "ffxiv_ipc_inventory_transaction",
      length = 36,
    },
  },
  [0x0314] = {
    [0] = {
      title = "AoeEffect8",
      name = "ffxiv_ipc_aoe_effect8",
      length = 632,
    },
  },
  [0x0324] = {
    [0] = {
      title = "UpdatePositionHandler",
    },
  },
  [0x032c] = {
    [0] = {
      title = "UpdatePositionInstance",
      name = "ffxiv_ipc_update_position_instance",
      length = 40,
    },
  },
  [0x032f] = {
    [0] = {
      title = "BossStatusEffectList",
      name = "ffxiv_ipc_boss_status_effect_list",
      length = 740,
    },
  },
  [0x033b] = {
    [0] = {
      title = "EventFinish",
    },
  },
  [0x033d] = {
    [0] = {
      title = "ClientTrigger",
      name = "ffxiv_ipc_client_trigger",
      length = 32,
    },
  },
  [0x034f] = {
    [0] = {
      title = "UpdateClassInfo",
      name = "ffxiv_ipc_update_class_info",
      length = 16,
    },
  },
  [0x035b] = {
    [0] = {
      title = "FateInfo",
      name = "ffxiv_ipc_fate_info",
      length = 24,
    },
  },
  [0x037a] = {
    [0] = {
      title = "Logout",
    },
  },
  [0x037b] = {
    [0] = {
      title = "EffectResult",
      name = "ffxiv_ipc_effect_result",
      length = 26,
    },
  },
  [0x03ac] = {
    [0] = {
      title = "CFPreferredRole",
    },
  },
  [0x03b1] = {
    [0] = {
      title = "FreeCompanyInfo",
    },
  },
  [0x03b7] = {
    [0] = {
      title = "ActorControlSelf",
      name = "ffxiv_ipc_actor_control_self",
      length = 32,
    },
  },
  [0x03cd] = {
    [0] = {
      title = "InventoryActionAck",
      name = "ffxiv_ipc_inventory_action_ack",
      length = 16,
    },
  },
}

function M.getDissector(typeNum, length)
  local types = M.types[typeNum]
  if type(types) ~= "table" then
    return nil
  end

  local title = nil
  if types[0] ~= nil then
    title = types[0].title
  end

  for k, v in pairs(types) do
    if v.name ~= nil and v.length ~= nil and v.length == length then
      return Dissector.get(v.name), v.title
    end
  end

  for k, v in pairs(types) do
    if v.name ~= nil and v.length ~= nil and v.length < length then
      return Dissector.get(v.name), v.title
    end
  end

  return nil, title
end

return M
