-- This file is generated by tools/json2lua.js

local ffxiv_ipc_company_info = Proto("ffxiv_ipc_company_info", "FFXIV-IPC Company Info")

local company_info_fields = {
  captain = ProtoField.string("ffxiv_ipc_company_info.captain", "Captain", base.UNICODE),
  content = ProtoField.string("ffxiv_ipc_company_info.content", "Content", base.UNICODE),
}

ffxiv_ipc_company_info.fields = company_info_fields

function ffxiv_ipc_company_info.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_company_info, tvbuf)

  -- dissect the captain field
  local captain_tvbr = tvbuf:range(0, 32)
  local captain_val  = captain_tvbr:string(ENC_UTF_8)
  tree:add(company_info_fields.captain, captain_val)

  -- dissect the content field
  local content_tvbr = tvbuf:range(1)
  local content_val  = content_tvbr:string(ENC_UTF_8)
  tree:add(company_info_fields.content, content_val)


  pktinfo.cols.info:set("Company Info")
  return tvbuf:len()
end