-- This file is generated by network:generate

local M = {}
M.types = {
  [0x0067] = {
    [0] = {
      title = "ExamineSearchInfo",
    },
  },
  [0x006e] = {
    [0] = {
      title = "ActionRequest",
    },
  },
  [0x0073] = {
    [0] = {
      title = "MarketBoardItemListingHistory",
      name = "ffxiv_ipc_market_board_item_listing_history",
      length = 964,
    },
  },
  [0x007b] = {
    [0] = {
      title = "AoeEffect16",
      name = "ffxiv_ipc_aoe_effect16",
      length = 1208,
    },
  },
  [0x007e] = {
    [0] = {
      title = "ContainerInfo",
      name = "ffxiv_ipc_container_info",
      length = 16,
    },
  },
  [0x0084] = {
    [0] = {
      title = "ItemMarketBoardInfo",
      name = "ffxiv_ipc_item_market_board_info",
      length = 20,
    },
  },
  [0x009d] = {
    [0] = {
      title = "ObjectSpawn",
      name = "ffxiv_ipc_object_spawn",
      length = 64,
    },
  },
  [0x00a7] = {
    [0] = {
      title = "WeatherChange",
      name = "ffxiv_ipc_weather_change",
      length = 8,
    },
  },
  [0x00b2] = {
    [0] = {
      title = "ActorSetPos",
      name = "ffxiv_ipc_actor_set_pos",
      length = 20,
    },
  },
  [0x00bc] = {
    [0] = {
      title = "SubmarineStatusList",
      name = "ffxiv_ipc_submarine_status_list",
      length = 240,
    },
  },
  [0x00be] = {
    [0] = {
      title = "PlayerStats",
      name = "ffxiv_ipc_player_stats",
      length = 120,
    },
  },
  [0x00cc] = {
    [0] = {
      title = "MapEffect8",
    },
  },
  [0x00f4] = {
    [0] = {
      title = "EffectResult",
      name = "ffxiv_ipc_effect_result",
      length = 42,
    },
  },
  [0x00fe] = {
    [0] = {
      title = "EventPlay32",
      name = "ffxiv_ipc_event_play32",
      length = 156,
    },
  },
  [0x010b] = {
    [0] = {
      title = "SubmarineExplorationResult",
      name = "ffxiv_ipc_submarine_exploration_result",
      length = 288,
    },
  },
  [0x0120] = {
    [0] = {
      title = "NpcSpawn2",
      name = "ffxiv_ipc_npc_spawn2",
      length = 624,
    },
  },
  [0x0129] = {
    [0] = {
      title = "ClientTrigger",
      name = "ffxiv_ipc_client_trigger",
      length = 32,
    },
  },
  [0x012b] = {
    [0] = {
      title = "CFPreferredRole",
    },
  },
  [0x012c] = {
    [0] = {
      title = "ActorFreeSpawn",
      name = "ffxiv_ipc_actor_free_spawn",
      length = 8,
    },
  },
  [0x012f] = {
    [0] = {
      title = "UpdatePositionHandler",
      name = "ffxiv_ipc_update_position_handler",
      length = 20,
    },
  },
  [0x0133] = {
    [0] = {
      title = "EffectResultBasic",
    },
  },
  [0x0134] = {
    [0] = {
      title = "Examine",
      name = "ffxiv_ipc_examine",
      length = 656,
    },
  },
  [0x0138] = {
    [0] = {
      title = "BossStatusEffectList",
      name = "ffxiv_ipc_boss_status_effect_list",
      length = 740,
    },
  },
  [0x0139] = {
    [0] = {
      title = "EffectResult8",
    },
  },
  [0x013b] = {
    [0] = {
      title = "IslandWorkshopSupplyDemand",
      name = "ffxiv_ipc_island_workshop_supply_demand",
      length = 2,
    },
  },
  [0x0140] = {
    [0] = {
      title = "PrepareZoning",
      name = "ffxiv_ipc_prepare_zoning",
      length = 16,
    },
  },
  [0x0141] = {
    [0] = {
      title = "PlayerSetup",
      name = "ffxiv_ipc_player_setup",
      length = 1938,
    },
  },
  [0x0145] = {
    [0] = {
      title = "WardLandInfo",
      name = "ffxiv_ipc_ward_land_info",
      length = 2408,
    },
  },
  [0x0149] = {
    [0] = {
      title = "CountdownCancel",
    },
  },
  [0x0157] = {
    [0] = {
      title = "UpdateClassInfo",
      name = "ffxiv_ipc_update_class_info",
      length = 16,
    },
  },
  [0x015d] = {
    [0] = {
      title = "UpdateHpMpTp",
      name = "ffxiv_ipc_update_hp_mp_tp",
      length = 8,
    },
  },
  [0x0162] = {
    [0] = {
      title = "ActorControlSelf",
      name = "ffxiv_ipc_actor_control_self",
      length = 32,
    },
  },
  [0x016e] = {
    [0] = {
      title = "MarketBoardItemListing",
      name = "ffxiv_ipc_market_board_item_listing",
      length = 1444,
    },
  },
  [0x0176] = {
    [0] = {
      title = "FateInfo",
      name = "ffxiv_ipc_fate_info",
      length = 24,
    },
  },
  [0x0178] = {
    [0] = {
      title = "EventPlay4",
      name = "ffxiv_ipc_event_play4",
      length = 44,
    },
  },
  [0x0183] = {
    [0] = {
      title = "SystemLogMessage32",
    },
  },
  [0x0188] = {
    [0] = {
      title = "UpdateParty",
    },
  },
  [0x018c] = {
    [0] = {
      title = "BattleTalk2",
    },
  },
  [0x0192] = {
    [0] = {
      title = "ActorMove",
      name = "ffxiv_ipc_actor_move",
      length = 12,
    },
  },
  [0x0197] = {
    [0] = {
      title = "NpcSpawn",
      name = "ffxiv_ipc_npc_spawn",
      length = 624,
    },
  },
  [0x019c] = {
    [0] = {
      title = "PlaceFieldMarkerPreset",
    },
  },
  [0x019e] = {
    [0] = {
      title = "StatusEffectList2",
    },
  },
  [0x01a4] = {
    [0] = {
      title = "MapEffect4",
    },
  },
  [0x01ac] = {
    [0] = {
      title = "StatusEffectListForay3",
    },
  },
  [0x01b6] = {
    [0] = {
      title = "MarketBoardSearchResult",
      name = "ffxiv_ipc_market_board_search_result",
      length = 176,
    },
  },
  [0x01b9] = {
    [0] = {
      title = "EventFinish",
      name = "ffxiv_ipc_event_finish",
      length = 4,
    },
  },
  [0x01bc] = {
    [0] = {
      title = "SystemLogMessage144",
    },
  },
  [0x01bf] = {
    [0] = {
      title = "EffectResult4",
    },
  },
  [0x01c6] = {
    [0] = {
      title = "AirshipExplorationResult",
      name = "ffxiv_ipc_airship_exploration_result",
      length = 284,
    },
  },
  [0x01cc] = {
    [0] = {
      title = "Effect",
      name = "ffxiv_ipc_effect",
      length = 120,
    },
  },
  [0x01cd] = {
    [0] = {
      title = "SystemLogMessage80",
    },
  },
  [0x01e2] = {
    [0] = {
      title = "CountdownInitiate",
    },
  },
  [0x01e6] = {
    [0] = {
      title = "InventoryTransactionFinish",
      name = "ffxiv_ipc_inventory_transaction_finish",
      length = 16,
    },
  },
  [0x01ec] = {
    [0] = {
      title = "ActorControl",
      name = "ffxiv_ipc_actor_control",
      length = 24,
    },
  },
  [0x01f4] = {
    [0] = {
      title = "UpdateInventorySlot",
      name = "ffxiv_ipc_update_inventory_slot",
      length = 64,
    },
  },
  [0x01ff] = {
    [0] = {
      title = "InventoryHandlerOffset",
    },
    [1] = {
      title = "InventoryModifyHandler",
      name = "ffxiv_ipc_inventory_modify_handler",
      length = 44,
    },
  },
  [0x0201] = {
    [0] = {
      title = "MarketBoardPurchaseHandler",
      name = "ffxiv_ipc_market_board_purchase_handler",
      length = 28,
    },
    [1] = {
      title = "RSV",
    },
  },
  [0x0211] = {
    [0] = {
      title = "ItemInfo",
      name = "ffxiv_ipc_item_info",
      length = 64,
    },
  },
  [0x0215] = {
    [0] = {
      title = "ContentFinderNotifyPop",
      name = "ffxiv_ipc_content_finder_notify_pop",
      length = 32,
    },
  },
  [0x0216] = {
    [0] = {
      title = "PlaceFieldMarker",
      name = "ffxiv_ipc_place_field_marker",
      length = 16,
    },
  },
  [0x021a] = {
    [0] = {
      title = "ResumeEventScene32",
    },
  },
  [0x0221] = {
    [0] = {
      title = "PlayerSpawn",
      name = "ffxiv_ipc_player_spawn",
      length = 624,
    },
    [1] = {
      title = "UpdatePositionInstance",
      name = "ffxiv_ipc_update_position_instance",
      length = 40,
    },
  },
  [0x0223] = {
    [0] = {
      title = "ActorControlTarget",
      name = "ffxiv_ipc_actor_control_target",
      length = 32,
    },
  },
  [0x0226] = {
    [0] = {
      title = "EventPlay",
      name = "ffxiv_ipc_event_play",
      length = 32,
    },
  },
  [0x0240] = {
    [0] = {
      title = "InventoryTransaction",
      name = "ffxiv_ipc_inventory_transaction",
      length = 36,
    },
  },
  [0x024e] = {
    [0] = {
      title = "StatusEffectList3",
    },
  },
  [0x0254] = {
    [0] = {
      title = "UpdateSearchInfo",
    },
  },
  [0x0256] = {
    [0] = {
      title = "CEDirector",
      name = "ffxiv_ipc_ce_director",
      length = 16,
    },
  },
  [0x0261] = {
    [0] = {
      title = "EffectResult16",
    },
  },
  [0x0265] = {
    [0] = {
      title = "AoeEffect32",
      name = "ffxiv_ipc_aoe_effect32",
      length = 2360,
    },
  },
  [0x0266] = {
    [0] = {
      title = "SystemLogMessage",
      name = "ffxiv_ipc_system_log_message",
      length = 16,
    },
  },
  [0x026e] = {
    [0] = {
      title = "InventoryActionAck",
      name = "ffxiv_ipc_inventory_action_ack",
      length = 16,
    },
  },
  [0x0290] = {
    [0] = {
      title = "NpcYell",
    },
  },
  [0x02af] = {
    [0] = {
      title = "ActorGauge",
      name = "ffxiv_ipc_actor_gauge",
      length = 16,
    },
  },
  [0x02ba] = {
    [0] = {
      title = "AirshipStatus",
      name = "ffxiv_ipc_airship_status",
      length = 72,
    },
  },
  [0x02c0] = {
    [0] = {
      title = "InitZone",
      name = "ffxiv_ipc_init_zone",
      length = 96,
    },
  },
  [0x02d8] = {
    [0] = {
      title = "RSF",
    },
  },
  [0x02de] = {
    [0] = {
      title = "Playtime",
      name = "ffxiv_ipc_playtime",
      length = 4,
    },
  },
  [0x02e4] = {
    [0] = {
      title = "CompanySubmersibleStatus",
      name = "ffxiv_ipc_company_submersible_status",
      length = 144,
    },
  },
  [0x02ed] = {
    [0] = {
      title = "SystemLogMessage48",
    },
  },
  [0x02fd] = {
    [0] = {
      title = "ActionRequestGroundTargeted",
    },
  },
  [0x02fe] = {
    [0] = {
      title = "AoeEffect24",
      name = "ffxiv_ipc_aoe_effect24",
      length = 1784,
    },
  },
  [0x0307] = {
    [0] = {
      title = "ResumeEventScene16",
    },
  },
  [0x031c] = {
    [0] = {
      title = "EnvironmentControl",
    },
  },
  [0x0331] = {
    [0] = {
      title = "CurrencyCrystalInfo",
      name = "ffxiv_ipc_currency_crystal_info",
      length = 32,
    },
  },
  [0x0338] = {
    [0] = {
      title = "MarketBoardPurchase",
      name = "ffxiv_ipc_market_board_purchase",
      length = 12,
    },
  },
  [0x0341] = {
    [0] = {
      title = "MarketBoardRequestItemListingInfo",
    },
    [1] = {
      title = "WorldVisitQueue",
    },
  },
  [0x0345] = {
    [0] = {
      title = "CompanyAirshipStatus",
      name = "ffxiv_ipc_company_airship_status",
      length = 144,
    },
  },
  [0x0356] = {
    [0] = {
      title = "FreeCompanyInfo",
      name = "ffxiv_ipc_free_company_info",
      length = 80,
    },
  },
  [0x035c] = {
    [0] = {
      title = "SetSearchInfoHandler",
    },
  },
  [0x035d] = {
    [0] = {
      title = "AirshipStatusList",
      name = "ffxiv_ipc_airship_status_list",
      length = 158,
    },
  },
  [0x0366] = {
    [0] = {
      title = "StatusEffectList",
      name = "ffxiv_ipc_status_effect_list",
      length = 380,
    },
  },
  [0x0373] = {
    [0] = {
      title = "FreeCompanyDialog",
      name = "ffxiv_ipc_free_company_dialog",
      length = 79,
    },
  },
  [0x037a] = {
    [0] = {
      title = "RetainerInformation",
      name = "ffxiv_ipc_retainer_information",
      length = 73,
    },
  },
  [0x038a] = {
    [0] = {
      title = "Logout",
      name = "ffxiv_ipc_logout",
      length = 8,
    },
  },
  [0x0390] = {
    [0] = {
      title = "MarketBoardItemListingCount",
      name = "ffxiv_ipc_market_board_item_listing_count",
      length = 8,
    },
  },
  [0x0391] = {
    [0] = {
      title = "EventStart",
      name = "ffxiv_ipc_event_start",
      length = 12,
    },
  },
  [0x0396] = {
    [0] = {
      title = "EurekaStatusEffectList",
    },
  },
  [0x039f] = {
    [0] = {
      title = "ChatHandler",
    },
  },
  [0x03ad] = {
    [0] = {
      title = "ActorCast",
      name = "ffxiv_ipc_actor_cast",
      length = 30,
    },
  },
  [0x03c9] = {
    [0] = {
      title = "SubmarineProgressionStatus",
      name = "ffxiv_ipc_submarine_progression_status",
      length = 31,
    },
  },
  [0x03d4] = {
    [0] = {
      title = "MapEffect12",
    },
  },
  [0x03df] = {
    [0] = {
      title = "AoeEffect8",
      name = "ffxiv_ipc_aoe_effect8",
      length = 632,
    },
  },
}

function M.getDissector(typeNum, length)
  local types = M.types[typeNum]
  if type(types) ~= "table" then
    return nil
  end

  local title = nil
  if types[0] ~= nil then
    title = types[0].title
  end

  for k, v in pairs(types) do
    if v.name ~= nil and v.length ~= nil and v.length == length then
      return Dissector.get(v.name), v.title
    end
  end

  for k, v in pairs(types) do
    if v.name ~= nil and v.length ~= nil and v.length < length then
      return Dissector.get(v.name), v.title
    end
  end

  return nil, title
end

return M
