-- This file is generated by network:generate

local ffxiv_ipc_balloon_talk4 = Proto("ffxiv_ipc_balloon_talk4", "FFXIV-IPC BalloonTalk4")

local balloon_talk4_fields = {
  entities = ProtoField.uint32("ffxiv_ipc_balloon_talk4.entities", "entities", base.DEC),
}

ffxiv_ipc_balloon_talk4.fields = balloon_talk4_fields

function ffxiv_ipc_balloon_talk4.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_balloon_talk4, tvbuf)
  local len = tvbuf:len()
  if len < 56 then
    tree:add_expert_info(PI_MALFORMED, PI_ERROR, "Truncated BalloonTalk4 payload")
    return len
  end

  -- dissect header
  local header_dissector = Dissector.get('ffxiv_ipc_balloon_talk_header')
  local header_pos = 0
  local header_len = 36
  local header_count = 1

  while header_pos + header_len <= len do
    local header_tvbr = tvbuf:range(header_pos, 36)
    header_dissector:call(header_tvbr:tvb(), pktinfo, root)
    header_pos = header_pos + header_len
    header_count = header_count - 1
    if header_count <= 0 then
      break
    end
  end

  -- dissect the entities field
  local entities_pos = 36
  local entities_len = 4
  local entities_count = 4

  while entities_pos + entities_len <= len do
    local entities_tvbr = tvbuf:range(entities_pos, entities_len)
    local entities_val  = entities_tvbr:le_uint()
    tree:add_le(balloon_talk4_fields.entities, entities_tvbr, entities_val)
    entities_pos = entities_pos + entities_len
    entities_count = entities_count - 1
    if entities_count <= 0 then
      break
    end
  end

  return len
end
