-- This file is generated by network:generate

local ffxiv_ipc_achievement = Proto("ffxiv_ipc_achievement", "FFXIV-IPC Achievement")

local achievement_fields = {
  completed_achievement_ids = ProtoField.uint32("ffxiv_ipc_achievement.completed_achievement_ids", "completedAchievementIds", base.DEC),
  history                   = ProtoField.uint16("ffxiv_ipc_achievement.history", "history", base.DEC),
  auxiliary_flag_indices    = ProtoField.uint32("ffxiv_ipc_achievement.auxiliary_flag_indices", "auxiliaryFlagIndices", base.DEC),
  unknown_tail              = ProtoField.bytes("ffxiv_ipc_achievement.unknown_tail", "unknownTail", base.NONE),
}

ffxiv_ipc_achievement.fields = achievement_fields

function ffxiv_ipc_achievement.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_achievement, tvbuf)
  local len = tvbuf:len()
  if len < 552 then
    tree:add_expert_info(PI_MALFORMED, PI_ERROR, "Truncated Achievement payload")
    return len
  end

  -- dissect the completed_achievement_ids field
  for completed_achievement_ids_pos = 0, 510 - 1 do
    local completed_achievement_ids_tvbr = tvbuf:range(completed_achievement_ids_pos, 1)
    local completed_achievement_ids_byte = completed_achievement_ids_tvbr:le_uint()
    for completed_achievement_ids_bit = 0, 7 do
      if math.floor(completed_achievement_ids_byte / 2 ^ completed_achievement_ids_bit) % 2 == 1 then
        local completed_achievement_ids_val = (completed_achievement_ids_pos - 0) * 8 + completed_achievement_ids_bit
        tree:add_le(achievement_fields.completed_achievement_ids, completed_achievement_ids_tvbr, completed_achievement_ids_val)
      end
    end
  end

  -- dissect the history field
  local history_pos = 510
  local history_len = 2
  local history_count = 5

  while history_pos + history_len <= len do
    local history_tvbr = tvbuf:range(history_pos, history_len)
    local history_val  = history_tvbr:le_uint()
    tree:add_le(achievement_fields.history, history_tvbr, history_val)
    history_pos = history_pos + history_len
    history_count = history_count - 1
    if history_count <= 0 then
      break
    end
  end

  -- dissect the auxiliary_flag_indices field
  for auxiliary_flag_indices_pos = 520, 546 - 1 do
    local auxiliary_flag_indices_tvbr = tvbuf:range(auxiliary_flag_indices_pos, 1)
    local auxiliary_flag_indices_byte = auxiliary_flag_indices_tvbr:le_uint()
    for auxiliary_flag_indices_bit = 0, 7 do
      if math.floor(auxiliary_flag_indices_byte / 2 ^ auxiliary_flag_indices_bit) % 2 == 1 then
        local auxiliary_flag_indices_val = (auxiliary_flag_indices_pos - 520) * 8 + auxiliary_flag_indices_bit
        tree:add_le(achievement_fields.auxiliary_flag_indices, auxiliary_flag_indices_tvbr, auxiliary_flag_indices_val)
      end
    end
  end

  -- dissect the unknown_tail field
  local unknown_tail_tvbr = tvbuf:range(546, 6)
  local unknown_tail_val  = unknown_tail_tvbr:raw()
  tree:add(achievement_fields.unknown_tail, unknown_tail_tvbr, unknown_tail_val)

  return len
end
