-- This file is generated by network:generate

local ffxiv_ipc_event_handler_return4 = Proto("ffxiv_ipc_event_handler_return4", "FFXIV-IPC EventHandlerReturn4")

local event_handler_return4_fields = {
  event_id    = ProtoField.uint32("ffxiv_ipc_event_handler_return4.event_id", "eventId", base.DEC),
  scene       = ProtoField.int16("ffxiv_ipc_event_handler_return4.scene", "scene", base.DEC),
  error_code  = ProtoField.uint8("ffxiv_ipc_event_handler_return4.error_code", "errorCode", base.DEC),
  param_count = ProtoField.uint8("ffxiv_ipc_event_handler_return4.param_count", "paramCount", base.DEC),
  params      = ProtoField.uint32("ffxiv_ipc_event_handler_return4.params", "params", base.DEC),
}

ffxiv_ipc_event_handler_return4.fields = event_handler_return4_fields

function ffxiv_ipc_event_handler_return4.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_event_handler_return4, tvbuf)
  local len = tvbuf:len()
  if len < 24 then
    tree:add_expert_info(PI_MALFORMED, PI_ERROR, "Truncated EventHandlerReturn4 payload")
    return len
  end

  -- dissect the event_id field
  local event_id_tvbr = tvbuf:range(0, 4)
  local event_id_val  = event_id_tvbr:le_uint()
  tree:add_le(event_handler_return4_fields.event_id, event_id_tvbr, event_id_val)

  -- dissect the scene field
  local scene_tvbr = tvbuf:range(4, 2)
  local scene_val  = scene_tvbr:le_int()
  tree:add_le(event_handler_return4_fields.scene, scene_tvbr, scene_val)

  -- dissect the error_code field
  local error_code_tvbr = tvbuf:range(6, 1)
  local error_code_val  = error_code_tvbr:le_uint()
  tree:add_le(event_handler_return4_fields.error_code, error_code_tvbr, error_code_val)

  -- dissect the param_count field
  local param_count_tvbr = tvbuf:range(7, 1)
  local param_count_val  = param_count_tvbr:le_uint()
  tree:add_le(event_handler_return4_fields.param_count, param_count_tvbr, param_count_val)

  -- dissect the params field
  local params_pos = 8
  local params_len = 4
  local params_count = 4

  while params_pos + params_len <= len do
    local params_tvbr = tvbuf:range(params_pos, params_len)
    local params_val  = params_tvbr:le_uint()
    tree:add_le(event_handler_return4_fields.params, params_tvbr, params_val)
    params_pos = params_pos + params_len
    params_count = params_count - 1
    if params_count <= 0 then
      break
    end
  end

  return len
end
