-- This file is generated by network:generate

local resolver = require("ffxiv_ipc_resolver")
local M = {}
M.types = {
  [0x0066] = {
    [0] = {
      type = "InventoryModifyHandler",
    },
  },
  [0x0070] = {
    [0] = {
      type = "MarketBoardItemListingCount",
    },
  },
  [0x007a] = {
    [0] = {
      type = "CFPreferredRole",
    },
  },
  [0x009a] = {
    [0] = {
      type = "InventoryActionAck",
    },
  },
  [0x00a7] = {
    [0] = {
      type = "PlayerStats",
    },
  },
  [0x00bb] = {
    [0] = {
      type = "AoeEffect24",
    },
  },
  [0x00d0] = {
    [0] = {
      type = "SetSearchInfoHandler",
    },
  },
  [0x00ef] = {
    [0] = {
      type = "MarketBoardSearchResult",
    },
  },
  [0x00f0] = {
    [0] = {
      type = "StatusEffectList2",
    },
  },
  [0x00f2] = {
    [0] = {
      type = "EventStart",
    },
  },
  [0x0103] = {
    [0] = {
      type = "EventFinish",
    },
  },
  [0x011e] = {
    [0] = {
      type = "InventoryTransaction",
    },
  },
  [0x0132] = {
    [0] = {
      type = "ChatHandler",
    },
  },
  [0x013c] = {
    [0] = {
      type = "InitZone",
    },
  },
  [0x0146] = {
    [0] = {
      type = "ActorCast",
    },
  },
  [0x014f] = {
    [0] = {
      type = "UpdateSearchInfo",
    },
  },
  [0x0152] = {
    [0] = {
      type = "Playtime",
    },
  },
  [0x0158] = {
    [0] = {
      type = "ActorSetPos",
    },
  },
  [0x0165] = {
    [0] = {
      type = "BossStatusEffectList",
    },
    [1] = {
      type = "StatusEffectList",
    },
  },
  [0x0168] = {
    [0] = {
      type = "CompanyAirshipStatus",
    },
  },
  [0x0174] = {
    [0] = {
      type = "Examine",
    },
  },
  [0x0175] = {
    [0] = {
      type = "MarketBoardItemListing",
    },
  },
  [0x0179] = {
    [0] = {
      type = "RetainerInformation",
    },
  },
  [0x01b8] = {
    [0] = {
      type = "UpdateClassInfo",
    },
  },
  [0x01f0] = {
    [0] = {
      type = "InventoryTransactionFinish",
    },
  },
  [0x0201] = {
    [0] = {
      type = "ExamineSearchInfo",
    },
  },
  [0x0202] = {
    [0] = {
      type = "ActorMove",
    },
  },
  [0x0204] = {
    [0] = {
      type = "ClientTrigger",
    },
  },
  [0x0211] = {
    [0] = {
      type = "NpcSpawn",
    },
  },
  [0x021f] = {
    [0] = {
      type = "AoeEffect16",
    },
  },
  [0x0228] = {
    [0] = {
      type = "SystemLogMessage",
    },
  },
  [0x0229] = {
    [0] = {
      type = "ActorControl",
    },
  },
  [0x0237] = {
    [0] = {
      type = "UpdateHpMpTp",
    },
  },
  [0x025e] = {
    [0] = {
      type = "ActorControlSelf",
    },
  },
  [0x029f] = {
    [0] = {
      type = "AoeEffect32",
    },
  },
  [0x02a2] = {
    [0] = {
      type = "EventPlay4",
    },
  },
  [0x02d0] = {
    [0] = {
      type = "EffectResult",
    },
  },
  [0x02dd] = {
    [0] = {
      type = "PlayerSetup",
    },
  },
  [0x02de] = {
    [0] = {
      type = "ResumeEventScene32",
    },
  },
  [0x02eb] = {
    [0] = {
      type = "ContainerInfo",
    },
  },
  [0x02f0] = {
    [0] = {
      type = "ItemInfo",
    },
  },
  [0x0306] = {
    [0] = {
      type = "CompanySubmersibleStatus",
    },
  },
  [0x031d] = {
    [0] = {
      type = "MarketBoardItemListingHistory",
    },
  },
  [0x034a] = {
    [0] = {
      type = "AoeEffect8",
    },
  },
  [0x034f] = {
    [0] = {
      type = "ContentFinderNotifyPop",
    },
  },
  [0x0350] = {
    [0] = {
      type = "EventPlay",
    },
  },
  [0x035e] = {
    [0] = {
      type = "Effect",
    },
  },
  [0x036a] = {
    [0] = {
      type = "ActorGauge",
    },
  },
  [0x0375] = {
    [0] = {
      type = "CurrencyCrystalInfo",
    },
  },
  [0x03a0] = {
    [0] = {
      type = "PlayerSpawn",
    },
  },
  [0x03c8] = {
    [0] = {
      type = "UpdateInventorySlot",
    },
  },
  [0x03c9] = {
    [0] = {
      type = "NpcSpawn2",
    },
  },
}

function M.getDissector(typeNum, length, direction)
  return resolver.getDissector(M.types[typeNum], length, direction)
end

return M
