-- This file is generated by network:generate

local ffxiv_ipc_market_board_item_listing = Proto("ffxiv_ipc_market_board_item_listing", "FFXIV-IPC MarketBoardItemListing")

local market_board_item_listing_fields = {
  listing_index_end   = ProtoField.uint8("ffxiv_ipc_market_board_item_listing.listing_index_end", "listingIndexEnd", base.DEC),
  listing_index_start = ProtoField.uint8("ffxiv_ipc_market_board_item_listing.listing_index_start", "listingIndexStart", base.DEC),
  request_id          = ProtoField.uint16("ffxiv_ipc_market_board_item_listing.request_id", "requestId", base.DEC),
}

ffxiv_ipc_market_board_item_listing.fields = market_board_item_listing_fields

function ffxiv_ipc_market_board_item_listing.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_market_board_item_listing, tvbuf)
  local len = tvbuf:len()

  -- dissect listings
  local listings_dissector = Dissector.get('ffxiv_ipc_market_board_listing')
  local listings_pos = 0
  local listings_len = 144
  local listings_count = 10

  while listings_pos + listings_len <= len do
    local listings_tvbr = tvbuf:range(listings_pos, 144)
    listings_dissector:call(listings_tvbr:tvb(), pktinfo, root)
    listings_pos = listings_pos + listings_len
    listings_count = listings_count - 1
    if listings_count <= 0 then
      break
    end
  end

  -- dissect the listing_index_end field
  local listing_index_end_tvbr = tvbuf:range(1440, 1)
  local listing_index_end_val  = listing_index_end_tvbr:le_uint()
  tree:add_le(market_board_item_listing_fields.listing_index_end, listing_index_end_tvbr, listing_index_end_val)

  -- dissect the listing_index_start field
  local listing_index_start_tvbr = tvbuf:range(1441, 1)
  local listing_index_start_val  = listing_index_start_tvbr:le_uint()
  tree:add_le(market_board_item_listing_fields.listing_index_start, listing_index_start_tvbr, listing_index_start_val)

  -- dissect the request_id field
  local request_id_tvbr = tvbuf:range(1442, 2)
  local request_id_val  = request_id_tvbr:le_uint()
  tree:add_le(market_board_item_listing_fields.request_id, request_id_tvbr, request_id_val)

  return len
end
