-- This file is generated by network:generate

local resolver = require("ffxiv_ipc_resolver")
local M = {}
M.types = {
  [0x0068] = {
    [0] = {
      type = "PlaceFieldMarkerPreset",
    },
  },
  [0x0094] = {
    [0] = {
      type = "Examine",
    },
  },
  [0x00a4] = {
    [0] = {
      type = "EventFinish",
    },
  },
  [0x00a5] = {
    [0] = {
      type = "ActorCast",
    },
  },
  [0x00b3] = {
    [0] = {
      type = "ExamineSearchInfo",
    },
  },
  [0x00b5] = {
    [0] = {
      type = "PlayerSpawn",
    },
  },
  [0x00ca] = {
    [0] = {
      type = "CurrencyCrystalInfo",
    },
  },
  [0x00cc] = {
    [0] = {
      type = "UpdatePositionHandler",
    },
  },
  [0x00cf] = {
    [0] = {
      type = "ItemInfo",
    },
  },
  [0x00d8] = {
    [0] = {
      type = "UpdateHpMpTp",
    },
  },
  [0x00f6] = {
    [0] = {
      type = "PrepareZoning",
    },
  },
  [0x00f8] = {
    [0] = {
      type = "ActorSetPos",
    },
  },
  [0x010e] = {
    [0] = {
      type = "UpdateSearchInfo",
    },
  },
  [0x0118] = {
    [0] = {
      type = "EventPlay4",
    },
  },
  [0x0127] = {
    [0] = {
      type = "InventoryModifyHandler",
    },
  },
  [0x0130] = {
    [0] = {
      type = "WardLandInfo",
    },
  },
  [0x0141] = {
    [0] = {
      type = "ClientTrigger",
    },
  },
  [0x014c] = {
    [0] = {
      type = "EventStart",
    },
  },
  [0x0159] = {
    [0] = {
      type = "CompanyAirshipStatus",
    },
  },
  [0x0165] = {
    [0] = {
      type = "UpdateInventorySlot",
    },
  },
  [0x0176] = {
    [0] = {
      type = "EventPlay",
    },
  },
  [0x0181] = {
    [0] = {
      type = "UpdatePositionInstance",
    },
  },
  [0x0186] = {
    [0] = {
      type = "PlayerStats",
    },
  },
  [0x0187] = {
    [0] = {
      type = "MarketBoardItemListingHistory",
    },
  },
  [0x019f] = {
    [0] = {
      type = "InventoryActionAck",
    },
  },
  [0x01a8] = {
    [0] = {
      type = "AoeEffect8",
    },
  },
  [0x01ab] = {
    [0] = {
      type = "SetSearchInfoHandler",
    },
  },
  [0x01b4] = {
    [0] = {
      type = "RetainerInformation",
    },
  },
  [0x01ba] = {
    [0] = {
      type = "ObjectSpawn",
    },
  },
  [0x01d1] = {
    [0] = {
      type = "MarketBoardItemListingCount",
    },
  },
  [0x01d3] = {
    [0] = {
      type = "NpcSpawn",
    },
  },
  [0x01eb] = {
    [0] = {
      type = "MarketBoardSearchResult",
    },
  },
  [0x0217] = {
    [0] = {
      type = "Playtime",
    },
  },
  [0x0234] = {
    [0] = {
      type = "ContainerInfo",
    },
  },
  [0x023a] = {
    [0] = {
      type = "CompanySubmersibleStatus",
    },
  },
  [0x024a] = {
    [0] = {
      type = "AoeEffect24",
    },
  },
  [0x0267] = {
    [0] = {
      type = "ChatHandler",
    },
  },
  [0x027b] = {
    [0] = {
      type = "AoeEffect32",
    },
  },
  [0x0294] = {
    [0] = {
      type = "InitZone",
    },
  },
  [0x02a4] = {
    [0] = {
      type = "MarketBoardItemListing",
    },
  },
  [0x02b0] = {
    [0] = {
      type = "ActorControlSelf",
    },
  },
  [0x02c3] = {
    [0] = {
      type = "UpdateClassInfo",
    },
  },
  [0x02c6] = {
    [0] = {
      type = "ActorControlTarget",
    },
  },
  [0x02d2] = {
    [0] = {
      type = "SystemLogMessage",
    },
  },
  [0x02dc] = {
    [0] = {
      type = "ActorMove",
    },
  },
  [0x02f2] = {
    [0] = {
      type = "ActorGauge",
    },
  },
  [0x02f5] = {
    [0] = {
      type = "PlayerSetup",
    },
  },
  [0x0300] = {
    [0] = {
      type = "AoeEffect16",
    },
  },
  [0x0301] = {
    [0] = {
      type = "ContentFinderNotifyPop",
    },
  },
  [0x0307] = {
    [0] = {
      type = "ResumeEventScene32",
    },
  },
  [0x0312] = {
    [0] = {
      type = "ActorControl",
    },
  },
  [0x0319] = {
    [0] = {
      type = "PlaceFieldMarker",
    },
  },
  [0x0360] = {
    [0] = {
      type = "StatusEffectList",
    },
  },
  [0x036e] = {
    [0] = {
      type = "ActorFreeSpawn",
    },
  },
  [0x037c] = {
    [0] = {
      type = "EffectResult",
    },
  },
  [0x038f] = {
    [0] = {
      type = "InventoryTransaction",
    },
  },
  [0x03ce] = {
    [0] = {
      type = "InventoryTransactionFinish",
    },
  },
  [0x03d2] = {
    [0] = {
      type = "Effect",
    },
  },
}

function M.getDissector(typeNum, length, direction)
  return resolver.getDissector(M.types[typeNum], length, direction)
end

return M
