-- This file is generated by network:generate

local ffxiv_ipc_airship_status_list = Proto("ffxiv_ipc_airship_status_list", "FFXIV-IPC AirshipStatusList")

local airship_status_list_fields = {
  unlocked_airship_count = ProtoField.uint8("ffxiv_ipc_airship_status_list.unlocked_airship_count", "unlockedAirshipCount", base.DEC),
  unknown0               = ProtoField.uint8("ffxiv_ipc_airship_status_list.unknown0", "unknown0", base.DEC),
  unknown1               = ProtoField.uint8("ffxiv_ipc_airship_status_list.unknown1", "unknown1", base.DEC),
  unknown2               = ProtoField.uint8("ffxiv_ipc_airship_status_list.unknown2", "unknown2", base.DEC),
  unlocked_sectors       = ProtoField.bytes("ffxiv_ipc_airship_status_list.unlocked_sectors", "unlockedSectors", base.NONE),
  explored_sectors       = ProtoField.bytes("ffxiv_ipc_airship_status_list.explored_sectors", "exploredSectors", base.NONE),
  unknown3               = ProtoField.uint16("ffxiv_ipc_airship_status_list.unknown3", "unknown3", base.DEC),
}

ffxiv_ipc_airship_status_list.fields = airship_status_list_fields

function ffxiv_ipc_airship_status_list.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_airship_status_list, tvbuf)
  local len = tvbuf:len()

  -- dissect the unlocked_airship_count field
  local unlocked_airship_count_tvbr = tvbuf:range(0, 1)
  local unlocked_airship_count_val  = unlocked_airship_count_tvbr:le_uint()
  tree:add_le(airship_status_list_fields.unlocked_airship_count, unlocked_airship_count_tvbr, unlocked_airship_count_val)

  -- dissect the unknown0 field
  local unknown0_tvbr = tvbuf:range(1, 1)
  local unknown0_val  = unknown0_tvbr:le_uint()
  tree:add_le(airship_status_list_fields.unknown0, unknown0_tvbr, unknown0_val)

  -- dissect the unknown1 field
  local unknown1_tvbr = tvbuf:range(2, 1)
  local unknown1_val  = unknown1_tvbr:le_uint()
  tree:add_le(airship_status_list_fields.unknown1, unknown1_tvbr, unknown1_val)

  -- dissect the unknown2 field
  local unknown2_tvbr = tvbuf:range(3, 1)
  local unknown2_val  = unknown2_tvbr:le_uint()
  tree:add_le(airship_status_list_fields.unknown2, unknown2_tvbr, unknown2_val)

  -- dissect status_list
  local status_list_dissector = Dissector.get('ffxiv_ipc_airship_status_list_item')
  local status_list_pos = 4
  local status_list_len = 36
  local status_list_count = 4

  while status_list_pos + status_list_len <= len do
    local status_list_tvbr = tvbuf:range(status_list_pos, 36)
    status_list_dissector:call(status_list_tvbr:tvb(), pktinfo, root)
    status_list_pos = status_list_pos + status_list_len
    status_list_count = status_list_count - 1
    if status_list_count <= 0 then
      break
    end
  end

  -- dissect the unlocked_sectors field
  local unlocked_sectors_tvbr = tvbuf:range(148, 4)
  local unlocked_sectors_val  = unlocked_sectors_tvbr:raw(148)
  tree:add(airship_status_list_fields.unlocked_sectors, unlocked_sectors_tvbr, unlocked_sectors_val)

  -- dissect the explored_sectors field
  local explored_sectors_tvbr = tvbuf:range(152, 4)
  local explored_sectors_val  = explored_sectors_tvbr:raw(152)
  tree:add(airship_status_list_fields.explored_sectors, explored_sectors_tvbr, explored_sectors_val)

  -- dissect the unknown3 field
  local unknown3_tvbr = tvbuf:range(156, 2)
  local unknown3_val  = unknown3_tvbr:le_uint()
  tree:add_le(airship_status_list_fields.unknown3, unknown3_tvbr, unknown3_val)

  return len
end
