-- This file is generated by network:generate

local ffxiv_ipc_battle_talk_header = Proto("ffxiv_ipc_battle_talk_header", "FFXIV-IPC BattleTalkHeader")

local battle_talk_header_fields = {
  actor_id    = ProtoField.uint64("ffxiv_ipc_battle_talk_header.actor_id", "actorId", base.DEC),
  event_id    = ProtoField.uint32("ffxiv_ipc_battle_talk_header.event_id", "eventId", base.DEC),
  name_id     = ProtoField.uint32("ffxiv_ipc_battle_talk_header.name_id", "nameId", base.DEC),
  message_id  = ProtoField.uint32("ffxiv_ipc_battle_talk_header.message_id", "messageId", base.DEC),
  duration    = ProtoField.uint32("ffxiv_ipc_battle_talk_header.duration", "duration", base.DEC),
  unknown1    = ProtoField.uint32("ffxiv_ipc_battle_talk_header.unknown1", "unknown1", base.DEC),
  kind        = ProtoField.uint8("ffxiv_ipc_battle_talk_header.kind", "kind", base.DEC),
  unknown2    = ProtoField.uint8("ffxiv_ipc_battle_talk_header.unknown2", "unknown2", base.DEC),
  param_count = ProtoField.uint8("ffxiv_ipc_battle_talk_header.param_count", "paramCount", base.DEC),
  padding     = ProtoField.uint8("ffxiv_ipc_battle_talk_header.padding", "padding", base.DEC),
}

ffxiv_ipc_battle_talk_header.fields = battle_talk_header_fields

function ffxiv_ipc_battle_talk_header.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_battle_talk_header, tvbuf)
  local len = tvbuf:len()
  if len < 32 then
    tree:add_expert_info(PI_MALFORMED, PI_ERROR, "Truncated BattleTalkHeader payload")
    return len
  end

  -- dissect the actor_id field
  local actor_id_tvbr = tvbuf:range(0, 8)
  local actor_id_val  = actor_id_tvbr:le_uint64()
  tree:add_le(battle_talk_header_fields.actor_id, actor_id_tvbr, actor_id_val)

  -- dissect the event_id field
  local event_id_tvbr = tvbuf:range(8, 4)
  local event_id_val  = event_id_tvbr:le_uint()
  tree:add_le(battle_talk_header_fields.event_id, event_id_tvbr, event_id_val)

  -- dissect the name_id field
  local name_id_tvbr = tvbuf:range(12, 4)
  local name_id_val  = name_id_tvbr:le_uint()
  tree:add_le(battle_talk_header_fields.name_id, name_id_tvbr, name_id_val)

  -- dissect the message_id field
  local message_id_tvbr = tvbuf:range(16, 4)
  local message_id_val  = message_id_tvbr:le_uint()
  tree:add_le(battle_talk_header_fields.message_id, message_id_tvbr, message_id_val)

  -- dissect the duration field
  local duration_tvbr = tvbuf:range(20, 4)
  local duration_val  = duration_tvbr:le_uint()
  tree:add_le(battle_talk_header_fields.duration, duration_tvbr, duration_val)

  -- dissect the unknown1 field
  local unknown1_tvbr = tvbuf:range(24, 4)
  local unknown1_val  = unknown1_tvbr:le_uint()
  tree:add_le(battle_talk_header_fields.unknown1, unknown1_tvbr, unknown1_val)

  -- dissect the kind field
  local kind_tvbr = tvbuf:range(28, 1)
  local kind_val  = kind_tvbr:le_uint()
  tree:add_le(battle_talk_header_fields.kind, kind_tvbr, kind_val)

  -- dissect the unknown2 field
  local unknown2_tvbr = tvbuf:range(29, 1)
  local unknown2_val  = unknown2_tvbr:le_uint()
  tree:add_le(battle_talk_header_fields.unknown2, unknown2_tvbr, unknown2_val)

  -- dissect the param_count field
  local param_count_tvbr = tvbuf:range(30, 1)
  local param_count_val  = param_count_tvbr:le_uint()
  tree:add_le(battle_talk_header_fields.param_count, param_count_tvbr, param_count_val)

  -- dissect the padding field
  local padding_tvbr = tvbuf:range(31, 1)
  local padding_val  = padding_tvbr:le_uint()
  tree:add_le(battle_talk_header_fields.padding, padding_tvbr, padding_val)

  return len
end
