-- This file is generated by network:generate

local resolver = require("ffxiv_ipc_resolver")
local M = {}
M.types = {
  [0x00de] = {
    [0] = {
      type = "ActorControl",
    },
  },
  [0x01c3] = {
    [0] = {
      type = "ActorControlSelf",
    },
  },
  [0x0265] = {
    [0] = {
      type = "ContentFinderNotifyPop",
    },
  },
  [0x0315] = {
    [0] = {
      type = "ClientTrigger",
    },
  },
  [0x0318] = {
    [0] = {
      type = "InventoryTransactionFinish",
    },
  },
  [0x0382] = {
    [0] = {
      type = "ActorGauge",
    },
  },
  [0x03ac] = {
    [0] = {
      type = "ActorControlTarget",
    },
  },
}

function M.getDissector(typeNum, length, direction)
  return resolver.getDissector(M.types[typeNum], length, direction)
end

return M
