-- This file is generated by network:generate

local ffxiv_ipc_status_effect_list_player_double = Proto("ffxiv_ipc_status_effect_list_player_double", "FFXIV-IPC StatusEffectListPlayerDouble")

local status_effect_list_player_double_fields = {
}

ffxiv_ipc_status_effect_list_player_double.fields = status_effect_list_player_double_fields

function ffxiv_ipc_status_effect_list_player_double.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_status_effect_list_player_double, tvbuf)
  local len = tvbuf:len()
  if len < 720 then
    tree:add_expert_info(PI_MALFORMED, PI_ERROR, "Truncated StatusEffectListPlayerDouble payload")
    return len
  end

  -- dissect status_effects
  local status_effects_dissector = Dissector.get('ffxiv_ipc_status_effect')
  local status_effects_pos = 0
  local status_effects_len = 12
  local status_effects_count = 60

  while status_effects_pos + status_effects_len <= len do
    local status_effects_tvbr = tvbuf:range(status_effects_pos, 12)
    status_effects_dissector:call(status_effects_tvbr:tvb(), pktinfo, root)
    status_effects_pos = status_effects_pos + status_effects_len
    status_effects_count = status_effects_count - 1
    if status_effects_count <= 0 then
      break
    end
  end

  return len
end
