-- This file is generated by network:generate

local ffxiv_ipc_weather_change = Proto("ffxiv_ipc_weather_change", "FFXIV-IPC WeatherChange")

local weather_change_fields = {
  weather_id = ProtoField.uint32("ffxiv_ipc_weather_change.weather_id", "weatherId", base.DEC),
  delay      = ProtoField.float("ffxiv_ipc_weather_change.delay", "delay", base.DEC),
}

ffxiv_ipc_weather_change.fields = weather_change_fields

function ffxiv_ipc_weather_change.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_weather_change, tvbuf)
  local len = tvbuf:len()

  -- dissect the weather_id field
  local weather_id_tvbr = tvbuf:range(0, 4)
  local weather_id_val  = weather_id_tvbr:le_uint()
  tree:add_le(weather_change_fields.weather_id, weather_id_tvbr, weather_id_val)

  -- dissect the delay field
  local delay_tvbr = tvbuf:range(4, 4)
  local delay_val  = delay_tvbr:le_float()
  tree:add_le(weather_change_fields.delay, delay_tvbr, delay_val)

  return len
end
