-- This file is generated by network:generate

local db = require('ffxiv_db')

local ffxiv_ipc_player_setup_header = Proto("ffxiv_ipc_player_setup_header", "FFXIV-IPC PlayerSetupHeader")

local player_setup_header_fields = {
  content_id                             = ProtoField.uint64("ffxiv_ipc_player_setup_header.content_id", "contentId", base.HEX),
  unknown8                               = ProtoField.bytes("ffxiv_ipc_player_setup_header.unknown8", "unknown8", base.NONE),
  unknown10                              = ProtoField.bytes("ffxiv_ipc_player_setup_header.unknown10", "unknown10", base.NONE),
  entity_id                              = ProtoField.uint32("ffxiv_ipc_player_setup_header.entity_id", "entityId", base.HEX),
  rested_exp                             = ProtoField.uint32("ffxiv_ipc_player_setup_header.rested_exp", "restedExp", base.DEC),
  companion_current_exp                  = ProtoField.uint32("ffxiv_ipc_player_setup_header.companion_current_exp", "companionCurrentExp", base.DEC),
  unknown_gc_supply24                    = ProtoField.uint32("ffxiv_ipc_player_setup_header.unknown_gc_supply24", "unknownGcSupply24", base.DEC),
  fish_caught                            = ProtoField.uint32("ffxiv_ipc_player_setup_header.fish_caught", "fishCaught", base.DEC),
  fishing_bait                           = ProtoField.uint32("ffxiv_ipc_player_setup_header.fishing_bait", "fishingBait", base.DEC, db.Item),
  spearfish_caught                       = ProtoField.uint32("ffxiv_ipc_player_setup_header.spearfish_caught", "spearfishCaught", base.DEC),
  unknown_pvp34                          = ProtoField.uint16("ffxiv_ipc_player_setup_header.unknown_pvp34", "unknownPvp34", base.DEC),
  unknown36                              = ProtoField.bytes("ffxiv_ipc_player_setup_header.unknown36", "unknown36", base.NONE),
  frontline_total_matches                = ProtoField.uint32("ffxiv_ipc_player_setup_header.frontline_total_matches", "frontlineTotalMatches", base.DEC),
  squadron_mission_completion_timestamp  = ProtoField.int32("ffxiv_ipc_player_setup_header.squadron_mission_completion_timestamp", "squadronMissionCompletionTimestamp", base.DEC),
  squadron_training_completion_timestamp = ProtoField.int32("ffxiv_ipc_player_setup_header.squadron_training_completion_timestamp", "squadronTrainingCompletionTimestamp", base.DEC),
  unknown44                              = ProtoField.uint32("ffxiv_ipc_player_setup_header.unknown44", "unknown44", base.DEC),
  weekly_bingo_task_status               = ProtoField.uint32("ffxiv_ipc_player_setup_header.weekly_bingo_task_status", "weeklyBingoTaskStatus", base.DEC),
  weekly_bingo_flags                     = ProtoField.uint32("ffxiv_ipc_player_setup_header.weekly_bingo_flags", "weeklyBingoFlags", base.DEC),
  companion_time_left                    = ProtoField.float("ffxiv_ipc_player_setup_header.companion_time_left", "companionTimeLeft", base.DEC),
  unknown54                              = ProtoField.uint32("ffxiv_ipc_player_setup_header.unknown54", "unknown54", base.DEC),
  unknown_timestamp58                    = ProtoField.int32("ffxiv_ipc_player_setup_header.unknown_timestamp58", "unknownTimestamp58", base.DEC),
  unknown5_c                             = ProtoField.bytes("ffxiv_ipc_player_setup_header.unknown5_c", "unknown5C", base.NONE),
  unknown_pvp5_e                         = ProtoField.uint16("ffxiv_ipc_player_setup_header.unknown_pvp5_e", "unknownPvp5E", base.DEC),
  pvp_series_experience                  = ProtoField.uint16("ffxiv_ipc_player_setup_header.pvp_series_experience", "pvpSeriesExperience", base.DEC),
  player_commendations                   = ProtoField.uint16("ffxiv_ipc_player_setup_header.player_commendations", "playerCommendations", base.DEC),
  unknown_daily_quest6_a                 = ProtoField.uint16("ffxiv_ipc_player_setup_header.unknown_daily_quest6_a", "unknownDailyQuest6A", base.DEC),
  unknown6_c                             = ProtoField.uint16("ffxiv_ipc_player_setup_header.unknown6_c", "unknown6C", base.DEC),
  frontline_weekly_matches               = ProtoField.uint16("ffxiv_ipc_player_setup_header.frontline_weekly_matches", "frontlineWeeklyMatches", base.DEC),
  anima_weapon7_work                     = ProtoField.uint16("ffxiv_ipc_player_setup_header.anima_weapon7_work", "animaWeapon7Work", base.DEC),
  active_gc_army_expedition              = ProtoField.uint16("ffxiv_ipc_player_setup_header.active_gc_army_expedition", "activeGcArmyExpedition", base.DEC),
  active_gc_army_training                = ProtoField.uint16("ffxiv_ipc_player_setup_header.active_gc_army_training", "activeGcArmyTraining", base.DEC),
  unknown_gold_saucer76                  = ProtoField.uint16("ffxiv_ipc_player_setup_header.unknown_gold_saucer76", "unknownGoldSaucer76", base.DEC),
  weekly_bingo_stickers                  = ProtoField.uint16("ffxiv_ipc_player_setup_header.weekly_bingo_stickers", "weeklyBingoStickers", base.DEC),
  rival_wings_total_matches              = ProtoField.uint16("ffxiv_ipc_player_setup_header.rival_wings_total_matches", "rivalWingsTotalMatches", base.DEC),
  rival_wings_total_matches_won          = ProtoField.uint16("ffxiv_ipc_player_setup_header.rival_wings_total_matches_won", "rivalWingsTotalMatchesWon", base.DEC),
  rival_wings_weekly_matches             = ProtoField.uint16("ffxiv_ipc_player_setup_header.rival_wings_weekly_matches", "rivalWingsWeeklyMatches", base.DEC),
  rival_wings_weekly_matches_won         = ProtoField.uint16("ffxiv_ipc_player_setup_header.rival_wings_weekly_matches_won", "rivalWingsWeeklyMatchesWon", base.DEC),
  max_level                              = ProtoField.uint8("ffxiv_ipc_player_setup_header.max_level", "maxLevel", base.DEC),
  expansion                              = ProtoField.uint8("ffxiv_ipc_player_setup_header.expansion", "expansion", base.DEC),
  has_premium_saddlebag                  = ProtoField.uint8("ffxiv_ipc_player_setup_header.has_premium_saddlebag", "hasPremiumSaddlebag", base.DEC),
  unknown_booleans85                     = ProtoField.uint8("ffxiv_ipc_player_setup_header.unknown_booleans85", "unknownBooleans85", base.DEC),
  race                                   = ProtoField.uint8("ffxiv_ipc_player_setup_header.race", "race", base.DEC),
  tribe                                  = ProtoField.uint8("ffxiv_ipc_player_setup_header.tribe", "tribe", base.DEC),
  gender                                 = ProtoField.uint8("ffxiv_ipc_player_setup_header.gender", "gender", base.DEC),
  current_job                            = ProtoField.uint8("ffxiv_ipc_player_setup_header.current_job", "currentJob", base.DEC, db.ClassJob),
  first_class                            = ProtoField.uint8("ffxiv_ipc_player_setup_header.first_class", "firstClass", base.DEC),
  deity                                  = ProtoField.uint8("ffxiv_ipc_player_setup_header.deity", "deity", base.DEC),
  nameday_month                          = ProtoField.uint8("ffxiv_ipc_player_setup_header.nameday_month", "namedayMonth", base.DEC),
  nameday_day                            = ProtoField.uint8("ffxiv_ipc_player_setup_header.nameday_day", "namedayDay", base.DEC),
  city_state                             = ProtoField.uint8("ffxiv_ipc_player_setup_header.city_state", "cityState", base.DEC),
  homepoint                              = ProtoField.uint16("ffxiv_ipc_player_setup_header.homepoint", "homepoint", base.DEC, db.Aetheryte),
  quest_special_flags                    = ProtoField.uint8("ffxiv_ipc_player_setup_header.quest_special_flags", "questSpecialFlags", base.DEC),
  unknown_pet93                          = ProtoField.uint8("ffxiv_ipc_player_setup_header.unknown_pet93", "unknownPet93", base.DEC),
  companion_rank                         = ProtoField.uint8("ffxiv_ipc_player_setup_header.companion_rank", "companionRank", base.DEC),
  companion_stars                        = ProtoField.uint8("ffxiv_ipc_player_setup_header.companion_stars", "companionStars", base.DEC),
  companion_sp                           = ProtoField.uint8("ffxiv_ipc_player_setup_header.companion_sp", "companionSp", base.DEC),
  companion_active_command               = ProtoField.uint8("ffxiv_ipc_player_setup_header.companion_active_command", "companionActiveCommand", base.DEC),
  companion_color                        = ProtoField.uint8("ffxiv_ipc_player_setup_header.companion_color", "companionColor", base.DEC, db.Stain),
  companion_favo_feed                    = ProtoField.uint8("ffxiv_ipc_player_setup_header.companion_favo_feed", "companionFavoFeed", base.DEC),
  favourite_aetheryte_count              = ProtoField.uint8("ffxiv_ipc_player_setup_header.favourite_aetheryte_count", "favouriteAetheryteCount", base.DEC),
  daily_quest_seed                       = ProtoField.uint8("ffxiv_ipc_player_setup_header.daily_quest_seed", "dailyQuestSeed", base.DEC),
  received_content_rewards               = ProtoField.uint8("ffxiv_ipc_player_setup_header.received_content_rewards", "receivedContentRewards", base.DEC),
  weekly_lockout_info                    = ProtoField.uint8("ffxiv_ipc_player_setup_header.weekly_lockout_info", "weeklyLockoutInfo", base.DEC),
  relic_id                               = ProtoField.uint8("ffxiv_ipc_player_setup_header.relic_id", "relicId", base.DEC),
  relic_note_id                          = ProtoField.uint8("ffxiv_ipc_player_setup_header.relic_note_id", "relicNoteId", base.DEC),
  sightseeing_log_unlock_state           = ProtoField.uint8("ffxiv_ipc_player_setup_header.sightseeing_log_unlock_state", "sightseeingLogUnlockState", base.DEC),
  sightseeing_log_unlock_state_ex        = ProtoField.uint8("ffxiv_ipc_player_setup_header.sightseeing_log_unlock_state_ex", "sightseeingLogUnlockStateEx", base.DEC),
  unknown_boolean_a2                     = ProtoField.uint8("ffxiv_ipc_player_setup_header.unknown_boolean_a2", "unknownBooleanA2", base.DEC),
  unknown_a3                             = ProtoField.uint8("ffxiv_ipc_player_setup_header.unknown_a3", "unknownA3", base.DEC),
  meister_flag                           = ProtoField.uint8("ffxiv_ipc_player_setup_header.meister_flag", "meisterFlag", base.DEC),
  gold_saucer_additional_flags           = ProtoField.uint8("ffxiv_ipc_player_setup_header.gold_saucer_additional_flags", "goldSaucerAdditionalFlags", base.DEC),
  aether_current_zone_completion_first   = ProtoField.uint32("ffxiv_ipc_player_setup_header.aether_current_zone_completion_first", "aetherCurrentZoneCompletionFirst", base.DEC),
  beginner_guide_flags                   = ProtoField.uint8("ffxiv_ipc_player_setup_header.beginner_guide_flags", "beginnerGuideFlags", base.DEC),
  has_new_gc_army_candidate              = ProtoField.uint8("ffxiv_ipc_player_setup_header.has_new_gc_army_candidate", "hasNewGcArmyCandidate", base.DEC),
  completed_lo_vm_stages                 = ProtoField.uint8("ffxiv_ipc_player_setup_header.completed_lo_vm_stages", "completedLoVMStages", base.DEC),
  unknown_aa                             = ProtoField.uint8("ffxiv_ipc_player_setup_header.unknown_aa", "unknownAA", base.DEC),
  satisfaction_supply_seed               = ProtoField.uint8("ffxiv_ipc_player_setup_header.satisfaction_supply_seed", "satisfactionSupplySeed", base.DEC),
  gold_saucer_content_status             = ProtoField.uint8("ffxiv_ipc_player_setup_header.gold_saucer_content_status", "goldSaucerContentStatus", base.DEC),
  mentor_version                         = ProtoField.uint8("ffxiv_ipc_player_setup_header.mentor_version", "mentorVersion", base.DEC),
  unknown_hwd_ae                         = ProtoField.uint8("ffxiv_ipc_player_setup_header.unknown_hwd_ae", "unknownHwdAE", base.DEC),
  weekly_bingo_exp_multiplier            = ProtoField.uint8("ffxiv_ipc_player_setup_header.weekly_bingo_exp_multiplier", "weeklyBingoExpMultiplier", base.DEC),
  weekly_bingo_unknown_flag              = ProtoField.uint8("ffxiv_ipc_player_setup_header.weekly_bingo_unknown_flag", "weeklyBingoUnknownFlag", base.DEC),
  pvp_series_current_rank                = ProtoField.uint8("ffxiv_ipc_player_setup_header.pvp_series_current_rank", "pvpSeriesCurrentRank", base.DEC),
  pvp_series_claimed_rank                = ProtoField.uint8("ffxiv_ipc_player_setup_header.pvp_series_claimed_rank", "pvpSeriesClaimedRank", base.DEC),
  pvp_previous_series_claimed_rank       = ProtoField.uint8("ffxiv_ipc_player_setup_header.pvp_previous_series_claimed_rank", "pvpPreviousSeriesClaimedRank", base.DEC),
  pvp_previous_series_rank               = ProtoField.uint8("ffxiv_ipc_player_setup_header.pvp_previous_series_rank", "pvpPreviousSeriesRank", base.DEC),
  unknown_b5                             = ProtoField.uint8("ffxiv_ipc_player_setup_header.unknown_b5", "unknownB5", base.DEC),
  unknown_b6                             = ProtoField.bytes("ffxiv_ipc_player_setup_header.unknown_b6", "unknownB6", base.NONE),
  unknown_b7                             = ProtoField.uint16("ffxiv_ipc_player_setup_header.unknown_b7", "unknownB7", base.DEC),
  unknown_b9                             = ProtoField.uint8("ffxiv_ipc_player_setup_header.unknown_b9", "unknownB9", base.DEC),
  unknown_ba                             = ProtoField.bytes("ffxiv_ipc_player_setup_header.unknown_ba", "unknownBA", base.NONE),
}

ffxiv_ipc_player_setup_header.fields = player_setup_header_fields

function ffxiv_ipc_player_setup_header.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_player_setup_header, tvbuf)
  local len = tvbuf:len()
  if len < 188 then
    tree:add_expert_info(PI_MALFORMED, PI_ERROR, "Truncated PlayerSetupHeader payload")
    return len
  end

  -- dissect the content_id field
  local content_id_tvbr = tvbuf:range(0, 8)
  local content_id_val  = content_id_tvbr:le_uint64()
  tree:add_le(player_setup_header_fields.content_id, content_id_tvbr, content_id_val)

  -- dissect the unknown8 field
  local unknown8_tvbr = tvbuf:range(8, 8)
  local unknown8_val  = unknown8_tvbr:raw()
  tree:add(player_setup_header_fields.unknown8, unknown8_tvbr, unknown8_val)

  -- dissect the unknown10 field
  local unknown10_tvbr = tvbuf:range(16, 8)
  local unknown10_val  = unknown10_tvbr:raw()
  tree:add(player_setup_header_fields.unknown10, unknown10_tvbr, unknown10_val)

  -- dissect the entity_id field
  local entity_id_tvbr = tvbuf:range(24, 4)
  local entity_id_val  = entity_id_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.entity_id, entity_id_tvbr, entity_id_val)

  -- dissect the rested_exp field
  local rested_exp_tvbr = tvbuf:range(28, 4)
  local rested_exp_val  = rested_exp_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.rested_exp, rested_exp_tvbr, rested_exp_val)

  -- dissect the companion_current_exp field
  local companion_current_exp_tvbr = tvbuf:range(32, 4)
  local companion_current_exp_val  = companion_current_exp_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.companion_current_exp, companion_current_exp_tvbr, companion_current_exp_val)

  -- dissect the unknown_gc_supply24 field
  local unknown_gc_supply24_tvbr = tvbuf:range(36, 4)
  local unknown_gc_supply24_val  = unknown_gc_supply24_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.unknown_gc_supply24, unknown_gc_supply24_tvbr, unknown_gc_supply24_val)

  -- dissect the fish_caught field
  local fish_caught_tvbr = tvbuf:range(40, 4)
  local fish_caught_val  = fish_caught_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.fish_caught, fish_caught_tvbr, fish_caught_val)

  -- dissect the fishing_bait field
  local fishing_bait_tvbr = tvbuf:range(44, 4)
  local fishing_bait_val  = fishing_bait_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.fishing_bait, fishing_bait_tvbr, fishing_bait_val)

  -- dissect the spearfish_caught field
  local spearfish_caught_tvbr = tvbuf:range(48, 4)
  local spearfish_caught_val  = spearfish_caught_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.spearfish_caught, spearfish_caught_tvbr, spearfish_caught_val)

  -- dissect the unknown_pvp34 field
  local unknown_pvp34_tvbr = tvbuf:range(52, 2)
  local unknown_pvp34_val  = unknown_pvp34_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.unknown_pvp34, unknown_pvp34_tvbr, unknown_pvp34_val)

  -- dissect the unknown36 field
  local unknown36_tvbr = tvbuf:range(54, 2)
  local unknown36_val  = unknown36_tvbr:raw()
  tree:add(player_setup_header_fields.unknown36, unknown36_tvbr, unknown36_val)

  -- dissect the frontline_total_matches field
  local frontline_total_matches_tvbr = tvbuf:range(56, 4)
  local frontline_total_matches_val  = frontline_total_matches_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.frontline_total_matches, frontline_total_matches_tvbr, frontline_total_matches_val)

  -- dissect the squadron_mission_completion_timestamp field
  local squadron_mission_completion_timestamp_tvbr = tvbuf:range(60, 4)
  local squadron_mission_completion_timestamp_val  = squadron_mission_completion_timestamp_tvbr:le_int()
  tree:add_le(player_setup_header_fields.squadron_mission_completion_timestamp, squadron_mission_completion_timestamp_tvbr, squadron_mission_completion_timestamp_val)

  -- dissect the squadron_training_completion_timestamp field
  local squadron_training_completion_timestamp_tvbr = tvbuf:range(64, 4)
  local squadron_training_completion_timestamp_val  = squadron_training_completion_timestamp_tvbr:le_int()
  tree:add_le(player_setup_header_fields.squadron_training_completion_timestamp, squadron_training_completion_timestamp_tvbr, squadron_training_completion_timestamp_val)

  -- dissect the unknown44 field
  local unknown44_tvbr = tvbuf:range(68, 4)
  local unknown44_val  = unknown44_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.unknown44, unknown44_tvbr, unknown44_val)

  -- dissect the weekly_bingo_task_status field
  local weekly_bingo_task_status_tvbr = tvbuf:range(72, 4)
  local weekly_bingo_task_status_val  = weekly_bingo_task_status_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.weekly_bingo_task_status, weekly_bingo_task_status_tvbr, weekly_bingo_task_status_val)

  -- dissect the weekly_bingo_flags field
  local weekly_bingo_flags_tvbr = tvbuf:range(76, 4)
  local weekly_bingo_flags_val  = weekly_bingo_flags_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.weekly_bingo_flags, weekly_bingo_flags_tvbr, weekly_bingo_flags_val)

  -- dissect the companion_time_left field
  local companion_time_left_tvbr = tvbuf:range(80, 4)
  local companion_time_left_val  = companion_time_left_tvbr:le_float()
  tree:add_le(player_setup_header_fields.companion_time_left, companion_time_left_tvbr, companion_time_left_val)

  -- dissect the unknown54 field
  local unknown54_tvbr = tvbuf:range(84, 4)
  local unknown54_val  = unknown54_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.unknown54, unknown54_tvbr, unknown54_val)

  -- dissect the unknown_timestamp58 field
  local unknown_timestamp58_tvbr = tvbuf:range(88, 4)
  local unknown_timestamp58_val  = unknown_timestamp58_tvbr:le_int()
  tree:add_le(player_setup_header_fields.unknown_timestamp58, unknown_timestamp58_tvbr, unknown_timestamp58_val)

  -- dissect the unknown5_c field
  local unknown5_c_tvbr = tvbuf:range(92, 2)
  local unknown5_c_val  = unknown5_c_tvbr:raw()
  tree:add(player_setup_header_fields.unknown5_c, unknown5_c_tvbr, unknown5_c_val)

  -- dissect the unknown_pvp5_e field
  local unknown_pvp5_e_pos = 94
  local unknown_pvp5_e_len = 2
  local unknown_pvp5_e_count = 4

  while unknown_pvp5_e_pos + unknown_pvp5_e_len <= len do
    local unknown_pvp5_e_tvbr = tvbuf:range(unknown_pvp5_e_pos, unknown_pvp5_e_len)
    local unknown_pvp5_e_val  = unknown_pvp5_e_tvbr:le_uint()
    tree:add_le(player_setup_header_fields.unknown_pvp5_e, unknown_pvp5_e_tvbr, unknown_pvp5_e_val)
    unknown_pvp5_e_pos = unknown_pvp5_e_pos + unknown_pvp5_e_len
    unknown_pvp5_e_count = unknown_pvp5_e_count - 1
    if unknown_pvp5_e_count <= 0 then
      break
    end
  end

  -- dissect the pvp_series_experience field
  local pvp_series_experience_tvbr = tvbuf:range(102, 2)
  local pvp_series_experience_val  = pvp_series_experience_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.pvp_series_experience, pvp_series_experience_tvbr, pvp_series_experience_val)

  -- dissect the player_commendations field
  local player_commendations_tvbr = tvbuf:range(104, 2)
  local player_commendations_val  = player_commendations_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.player_commendations, player_commendations_tvbr, player_commendations_val)

  -- dissect the unknown_daily_quest6_a field
  local unknown_daily_quest6_a_tvbr = tvbuf:range(106, 2)
  local unknown_daily_quest6_a_val  = unknown_daily_quest6_a_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.unknown_daily_quest6_a, unknown_daily_quest6_a_tvbr, unknown_daily_quest6_a_val)

  -- dissect the unknown6_c field
  local unknown6_c_tvbr = tvbuf:range(108, 2)
  local unknown6_c_val  = unknown6_c_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.unknown6_c, unknown6_c_tvbr, unknown6_c_val)

  -- dissect the frontline_weekly_matches field
  local frontline_weekly_matches_tvbr = tvbuf:range(110, 2)
  local frontline_weekly_matches_val  = frontline_weekly_matches_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.frontline_weekly_matches, frontline_weekly_matches_tvbr, frontline_weekly_matches_val)

  -- dissect the anima_weapon7_work field
  local anima_weapon7_work_tvbr = tvbuf:range(112, 2)
  local anima_weapon7_work_val  = anima_weapon7_work_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.anima_weapon7_work, anima_weapon7_work_tvbr, anima_weapon7_work_val)

  -- dissect the active_gc_army_expedition field
  local active_gc_army_expedition_tvbr = tvbuf:range(114, 2)
  local active_gc_army_expedition_val  = active_gc_army_expedition_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.active_gc_army_expedition, active_gc_army_expedition_tvbr, active_gc_army_expedition_val)

  -- dissect the active_gc_army_training field
  local active_gc_army_training_tvbr = tvbuf:range(116, 2)
  local active_gc_army_training_val  = active_gc_army_training_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.active_gc_army_training, active_gc_army_training_tvbr, active_gc_army_training_val)

  -- dissect the unknown_gold_saucer76 field
  local unknown_gold_saucer76_tvbr = tvbuf:range(118, 2)
  local unknown_gold_saucer76_val  = unknown_gold_saucer76_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.unknown_gold_saucer76, unknown_gold_saucer76_tvbr, unknown_gold_saucer76_val)

  -- dissect the weekly_bingo_stickers field
  local weekly_bingo_stickers_tvbr = tvbuf:range(120, 2)
  local weekly_bingo_stickers_val  = weekly_bingo_stickers_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.weekly_bingo_stickers, weekly_bingo_stickers_tvbr, weekly_bingo_stickers_val)

  -- dissect the rival_wings_total_matches field
  local rival_wings_total_matches_tvbr = tvbuf:range(122, 2)
  local rival_wings_total_matches_val  = rival_wings_total_matches_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.rival_wings_total_matches, rival_wings_total_matches_tvbr, rival_wings_total_matches_val)

  -- dissect the rival_wings_total_matches_won field
  local rival_wings_total_matches_won_tvbr = tvbuf:range(124, 2)
  local rival_wings_total_matches_won_val  = rival_wings_total_matches_won_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.rival_wings_total_matches_won, rival_wings_total_matches_won_tvbr, rival_wings_total_matches_won_val)

  -- dissect the rival_wings_weekly_matches field
  local rival_wings_weekly_matches_tvbr = tvbuf:range(126, 2)
  local rival_wings_weekly_matches_val  = rival_wings_weekly_matches_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.rival_wings_weekly_matches, rival_wings_weekly_matches_tvbr, rival_wings_weekly_matches_val)

  -- dissect the rival_wings_weekly_matches_won field
  local rival_wings_weekly_matches_won_tvbr = tvbuf:range(128, 2)
  local rival_wings_weekly_matches_won_val  = rival_wings_weekly_matches_won_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.rival_wings_weekly_matches_won, rival_wings_weekly_matches_won_tvbr, rival_wings_weekly_matches_won_val)

  -- dissect the max_level field
  local max_level_tvbr = tvbuf:range(130, 1)
  local max_level_val  = max_level_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.max_level, max_level_tvbr, max_level_val)

  -- dissect the expansion field
  local expansion_tvbr = tvbuf:range(131, 1)
  local expansion_val  = expansion_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.expansion, expansion_tvbr, expansion_val)

  -- dissect the has_premium_saddlebag field
  local has_premium_saddlebag_tvbr = tvbuf:range(132, 1)
  local has_premium_saddlebag_val  = has_premium_saddlebag_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.has_premium_saddlebag, has_premium_saddlebag_tvbr, has_premium_saddlebag_val)

  -- dissect the unknown_booleans85 field
  local unknown_booleans85_pos = 133
  local unknown_booleans85_len = 1
  local unknown_booleans85_count = 2

  while unknown_booleans85_pos + unknown_booleans85_len <= len do
    local unknown_booleans85_tvbr = tvbuf:range(unknown_booleans85_pos, unknown_booleans85_len)
    local unknown_booleans85_val  = unknown_booleans85_tvbr:le_uint()
    tree:add_le(player_setup_header_fields.unknown_booleans85, unknown_booleans85_tvbr, unknown_booleans85_val)
    unknown_booleans85_pos = unknown_booleans85_pos + unknown_booleans85_len
    unknown_booleans85_count = unknown_booleans85_count - 1
    if unknown_booleans85_count <= 0 then
      break
    end
  end

  -- dissect the race field
  local race_tvbr = tvbuf:range(135, 1)
  local race_val  = race_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.race, race_tvbr, race_val)

  -- dissect the tribe field
  local tribe_tvbr = tvbuf:range(136, 1)
  local tribe_val  = tribe_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.tribe, tribe_tvbr, tribe_val)

  -- dissect the gender field
  local gender_tvbr = tvbuf:range(137, 1)
  local gender_val  = gender_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.gender, gender_tvbr, gender_val)

  -- dissect the current_job field
  local current_job_tvbr = tvbuf:range(138, 1)
  local current_job_val  = current_job_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.current_job, current_job_tvbr, current_job_val)

  -- dissect the first_class field
  local first_class_tvbr = tvbuf:range(139, 1)
  local first_class_val  = first_class_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.first_class, first_class_tvbr, first_class_val)

  -- dissect the deity field
  local deity_tvbr = tvbuf:range(140, 1)
  local deity_val  = deity_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.deity, deity_tvbr, deity_val)

  -- dissect the nameday_month field
  local nameday_month_tvbr = tvbuf:range(141, 1)
  local nameday_month_val  = nameday_month_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.nameday_month, nameday_month_tvbr, nameday_month_val)

  -- dissect the nameday_day field
  local nameday_day_tvbr = tvbuf:range(142, 1)
  local nameday_day_val  = nameday_day_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.nameday_day, nameday_day_tvbr, nameday_day_val)

  -- dissect the city_state field
  local city_state_tvbr = tvbuf:range(143, 1)
  local city_state_val  = city_state_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.city_state, city_state_tvbr, city_state_val)

  -- dissect the homepoint field
  local homepoint_tvbr = tvbuf:range(144, 2)
  local homepoint_val  = homepoint_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.homepoint, homepoint_tvbr, homepoint_val)

  -- dissect the quest_special_flags field
  local quest_special_flags_tvbr = tvbuf:range(146, 1)
  local quest_special_flags_val  = quest_special_flags_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.quest_special_flags, quest_special_flags_tvbr, quest_special_flags_val)

  -- dissect the unknown_pet93 field
  local unknown_pet93_tvbr = tvbuf:range(147, 1)
  local unknown_pet93_val  = unknown_pet93_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.unknown_pet93, unknown_pet93_tvbr, unknown_pet93_val)

  -- dissect the companion_rank field
  local companion_rank_tvbr = tvbuf:range(148, 1)
  local companion_rank_val  = companion_rank_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.companion_rank, companion_rank_tvbr, companion_rank_val)

  -- dissect the companion_stars field
  local companion_stars_tvbr = tvbuf:range(149, 1)
  local companion_stars_val  = companion_stars_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.companion_stars, companion_stars_tvbr, companion_stars_val)

  -- dissect the companion_sp field
  local companion_sp_tvbr = tvbuf:range(150, 1)
  local companion_sp_val  = companion_sp_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.companion_sp, companion_sp_tvbr, companion_sp_val)

  -- dissect the companion_active_command field
  local companion_active_command_tvbr = tvbuf:range(151, 1)
  local companion_active_command_val  = companion_active_command_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.companion_active_command, companion_active_command_tvbr, companion_active_command_val)

  -- dissect the companion_color field
  local companion_color_tvbr = tvbuf:range(152, 1)
  local companion_color_val  = companion_color_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.companion_color, companion_color_tvbr, companion_color_val)

  -- dissect the companion_favo_feed field
  local companion_favo_feed_tvbr = tvbuf:range(153, 1)
  local companion_favo_feed_val  = companion_favo_feed_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.companion_favo_feed, companion_favo_feed_tvbr, companion_favo_feed_val)

  -- dissect the favourite_aetheryte_count field
  local favourite_aetheryte_count_tvbr = tvbuf:range(154, 1)
  local favourite_aetheryte_count_val  = favourite_aetheryte_count_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.favourite_aetheryte_count, favourite_aetheryte_count_tvbr, favourite_aetheryte_count_val)

  -- dissect the daily_quest_seed field
  local daily_quest_seed_tvbr = tvbuf:range(155, 1)
  local daily_quest_seed_val  = daily_quest_seed_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.daily_quest_seed, daily_quest_seed_tvbr, daily_quest_seed_val)

  -- dissect the received_content_rewards field
  local received_content_rewards_tvbr = tvbuf:range(156, 1)
  local received_content_rewards_val  = received_content_rewards_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.received_content_rewards, received_content_rewards_tvbr, received_content_rewards_val)

  -- dissect the weekly_lockout_info field
  local weekly_lockout_info_tvbr = tvbuf:range(157, 1)
  local weekly_lockout_info_val  = weekly_lockout_info_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.weekly_lockout_info, weekly_lockout_info_tvbr, weekly_lockout_info_val)

  -- dissect the relic_id field
  local relic_id_tvbr = tvbuf:range(158, 1)
  local relic_id_val  = relic_id_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.relic_id, relic_id_tvbr, relic_id_val)

  -- dissect the relic_note_id field
  local relic_note_id_tvbr = tvbuf:range(159, 1)
  local relic_note_id_val  = relic_note_id_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.relic_note_id, relic_note_id_tvbr, relic_note_id_val)

  -- dissect the sightseeing_log_unlock_state field
  local sightseeing_log_unlock_state_tvbr = tvbuf:range(160, 1)
  local sightseeing_log_unlock_state_val  = sightseeing_log_unlock_state_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.sightseeing_log_unlock_state, sightseeing_log_unlock_state_tvbr, sightseeing_log_unlock_state_val)

  -- dissect the sightseeing_log_unlock_state_ex field
  local sightseeing_log_unlock_state_ex_tvbr = tvbuf:range(161, 1)
  local sightseeing_log_unlock_state_ex_val  = sightseeing_log_unlock_state_ex_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.sightseeing_log_unlock_state_ex, sightseeing_log_unlock_state_ex_tvbr, sightseeing_log_unlock_state_ex_val)

  -- dissect the unknown_boolean_a2 field
  local unknown_boolean_a2_tvbr = tvbuf:range(162, 1)
  local unknown_boolean_a2_val  = unknown_boolean_a2_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.unknown_boolean_a2, unknown_boolean_a2_tvbr, unknown_boolean_a2_val)

  -- dissect the unknown_a3 field
  local unknown_a3_tvbr = tvbuf:range(163, 1)
  local unknown_a3_val  = unknown_a3_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.unknown_a3, unknown_a3_tvbr, unknown_a3_val)

  -- dissect the meister_flag field
  local meister_flag_tvbr = tvbuf:range(164, 1)
  local meister_flag_val  = meister_flag_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.meister_flag, meister_flag_tvbr, meister_flag_val)

  -- dissect the gold_saucer_additional_flags field
  local gold_saucer_additional_flags_tvbr = tvbuf:range(165, 1)
  local gold_saucer_additional_flags_val  = gold_saucer_additional_flags_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.gold_saucer_additional_flags, gold_saucer_additional_flags_tvbr, gold_saucer_additional_flags_val)

  -- dissect the aether_current_zone_completion_first field
  for aether_current_zone_completion_first_pos = 166, 167 - 1 do
    local aether_current_zone_completion_first_tvbr = tvbuf:range(aether_current_zone_completion_first_pos, 1)
    local aether_current_zone_completion_first_byte = aether_current_zone_completion_first_tvbr:le_uint()
    for aether_current_zone_completion_first_bit = 0, 7 do
      if math.floor(aether_current_zone_completion_first_byte / 2 ^ aether_current_zone_completion_first_bit) % 2 == 1 then
        local aether_current_zone_completion_first_val = (aether_current_zone_completion_first_pos - 166) * 8 + aether_current_zone_completion_first_bit
        tree:add_le(player_setup_header_fields.aether_current_zone_completion_first, aether_current_zone_completion_first_tvbr, aether_current_zone_completion_first_val)
      end
    end
  end

  -- dissect the beginner_guide_flags field
  local beginner_guide_flags_tvbr = tvbuf:range(167, 1)
  local beginner_guide_flags_val  = beginner_guide_flags_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.beginner_guide_flags, beginner_guide_flags_tvbr, beginner_guide_flags_val)

  -- dissect the has_new_gc_army_candidate field
  local has_new_gc_army_candidate_tvbr = tvbuf:range(168, 1)
  local has_new_gc_army_candidate_val  = has_new_gc_army_candidate_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.has_new_gc_army_candidate, has_new_gc_army_candidate_tvbr, has_new_gc_army_candidate_val)

  -- dissect the completed_lo_vm_stages field
  local completed_lo_vm_stages_tvbr = tvbuf:range(169, 1)
  local completed_lo_vm_stages_val  = completed_lo_vm_stages_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.completed_lo_vm_stages, completed_lo_vm_stages_tvbr, completed_lo_vm_stages_val)

  -- dissect the unknown_aa field
  local unknown_aa_tvbr = tvbuf:range(170, 1)
  local unknown_aa_val  = unknown_aa_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.unknown_aa, unknown_aa_tvbr, unknown_aa_val)

  -- dissect the satisfaction_supply_seed field
  local satisfaction_supply_seed_tvbr = tvbuf:range(171, 1)
  local satisfaction_supply_seed_val  = satisfaction_supply_seed_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.satisfaction_supply_seed, satisfaction_supply_seed_tvbr, satisfaction_supply_seed_val)

  -- dissect the gold_saucer_content_status field
  local gold_saucer_content_status_tvbr = tvbuf:range(172, 1)
  local gold_saucer_content_status_val  = gold_saucer_content_status_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.gold_saucer_content_status, gold_saucer_content_status_tvbr, gold_saucer_content_status_val)

  -- dissect the mentor_version field
  local mentor_version_tvbr = tvbuf:range(173, 1)
  local mentor_version_val  = mentor_version_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.mentor_version, mentor_version_tvbr, mentor_version_val)

  -- dissect the unknown_hwd_ae field
  local unknown_hwd_ae_tvbr = tvbuf:range(174, 1)
  local unknown_hwd_ae_val  = unknown_hwd_ae_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.unknown_hwd_ae, unknown_hwd_ae_tvbr, unknown_hwd_ae_val)

  -- dissect the weekly_bingo_exp_multiplier field
  local weekly_bingo_exp_multiplier_tvbr = tvbuf:range(175, 1)
  local weekly_bingo_exp_multiplier_val  = weekly_bingo_exp_multiplier_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.weekly_bingo_exp_multiplier, weekly_bingo_exp_multiplier_tvbr, weekly_bingo_exp_multiplier_val)

  -- dissect the weekly_bingo_unknown_flag field
  local weekly_bingo_unknown_flag_tvbr = tvbuf:range(176, 1)
  local weekly_bingo_unknown_flag_val  = weekly_bingo_unknown_flag_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.weekly_bingo_unknown_flag, weekly_bingo_unknown_flag_tvbr, weekly_bingo_unknown_flag_val)

  -- dissect the pvp_series_current_rank field
  local pvp_series_current_rank_tvbr = tvbuf:range(177, 1)
  local pvp_series_current_rank_val  = pvp_series_current_rank_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.pvp_series_current_rank, pvp_series_current_rank_tvbr, pvp_series_current_rank_val)

  -- dissect the pvp_series_claimed_rank field
  local pvp_series_claimed_rank_tvbr = tvbuf:range(178, 1)
  local pvp_series_claimed_rank_val  = pvp_series_claimed_rank_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.pvp_series_claimed_rank, pvp_series_claimed_rank_tvbr, pvp_series_claimed_rank_val)

  -- dissect the pvp_previous_series_claimed_rank field
  local pvp_previous_series_claimed_rank_tvbr = tvbuf:range(179, 1)
  local pvp_previous_series_claimed_rank_val  = pvp_previous_series_claimed_rank_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.pvp_previous_series_claimed_rank, pvp_previous_series_claimed_rank_tvbr, pvp_previous_series_claimed_rank_val)

  -- dissect the pvp_previous_series_rank field
  local pvp_previous_series_rank_tvbr = tvbuf:range(180, 1)
  local pvp_previous_series_rank_val  = pvp_previous_series_rank_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.pvp_previous_series_rank, pvp_previous_series_rank_tvbr, pvp_previous_series_rank_val)

  -- dissect the unknown_b5 field
  local unknown_b5_tvbr = tvbuf:range(181, 1)
  local unknown_b5_val  = unknown_b5_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.unknown_b5, unknown_b5_tvbr, unknown_b5_val)

  -- dissect the unknown_b6 field
  local unknown_b6_tvbr = tvbuf:range(182, 1)
  local unknown_b6_val  = unknown_b6_tvbr:raw()
  tree:add(player_setup_header_fields.unknown_b6, unknown_b6_tvbr, unknown_b6_val)

  -- dissect the unknown_b7 field
  local unknown_b7_tvbr = tvbuf:range(183, 2)
  local unknown_b7_val  = unknown_b7_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.unknown_b7, unknown_b7_tvbr, unknown_b7_val)

  -- dissect the unknown_b9 field
  local unknown_b9_tvbr = tvbuf:range(185, 1)
  local unknown_b9_val  = unknown_b9_tvbr:le_uint()
  tree:add_le(player_setup_header_fields.unknown_b9, unknown_b9_tvbr, unknown_b9_val)

  -- dissect the unknown_ba field
  local unknown_ba_tvbr = tvbuf:range(186, 2)
  local unknown_ba_val  = unknown_ba_tvbr:raw()
  tree:add(player_setup_header_fields.unknown_ba, unknown_ba_tvbr, unknown_ba_val)

  return len
end
