-- This file is generated by network:generate

local M = {}
M.types = {
  [0x006a] = {
    [0] = {
      name = "ffxiv_ipc_actor_gauge",
      length = 16,
      title = "ActorGauge",
    },
  },
  [0x0074] = {
    [0] = {
      name = "ffxiv_ipc_company_submersible_status",
      length = 0,
      title = "CompanySubmersibleStatus",
    },
  },
  [0x009f] = {
    [0] = {
      name = "ffxiv_ipc_npc_spawn2",
      length = 624,
      title = "NpcSpawn2",
    },
  },
  [0x00a2] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect24",
      length = 1784,
      title = "AoeEffect24",
    },
  },
  [0x00b6] = {
    [0] = {
      name = "ffxiv_ipc_effect",
      length = 120,
      title = "Effect",
    },
  },
  [0x00b7] = {
    [0] = {
      name = "ffxiv_ipc_ward_land_info",
      length = 2408,
      title = "WardLandInfo",
    },
  },
  [0x00bb] = {
    [0] = {
      name = "ffxiv_ipc_object_spawn",
      length = 64,
      title = "ObjectSpawn",
    },
  },
  [0x00cc] = {
    [0] = {
      name = "ffxiv_ipc_company_airship_status",
      length = 0,
      title = "CompanyAirshipStatus",
    },
  },
  [0x00e7] = {
    [0] = {
      name = "ffxiv_ipc_actor_control",
      length = 24,
      title = "ActorControl",
    },
  },
  [0x011a] = {
    [0] = {
      name = "ffxiv_ipc_inventory_transaction",
      length = 36,
      title = "InventoryTransaction",
    },
  },
  [0x0141] = {
    [0] = {
      name = "ffxiv_ipc_update_hp_mp_tp",
      length = 8,
      title = "UpdateHpMpTp",
    },
  },
  [0x016d] = {
    [0] = {
      name = "ffxiv_ipc_player_setup",
      length = 1938,
      title = "PlayerSetup",
    },
  },
  [0x0171] = {
    [0] = {
      name = "ffxiv_ipc_actor_control_target",
      length = 32,
      title = "ActorControlTarget",
    },
  },
  [0x0180] = {
    [0] = {
      name = "ffxiv_ipc_boss_status_effect_list",
      length = 740,
      title = "BossStatusEffectList",
    },
  },
  [0x0199] = {
    [0] = {
      name = "ffxiv_ipc_currency_crystal_info",
      length = 32,
      title = "CurrencyCrystalInfo",
    },
  },
  [0x01a8] = {
    [0] = {
      name = "ffxiv_ipc_item_info",
      length = 64,
      title = "ItemInfo",
    },
  },
  [0x01c0] = {
    [0] = {
      name = "ffxiv_ipc_inventory_transaction_finish",
      length = 16,
      title = "InventoryTransactionFinish",
    },
  },
  [0x01c8] = {
    [0] = {
      name = "ffxiv_ipc_actor_set_pos",
      length = 20,
      title = "ActorSetPos",
    },
  },
  [0x01d8] = {
    [0] = {
      name = "ffxiv_ipc_client_trigger",
      length = 32,
      title = "ClientTrigger",
    },
  },
  [0x01df] = {
    [0] = {
      name = "ffxiv_ipc_status_effect_list",
      length = 380,
      title = "StatusEffectList",
    },
  },
  [0x01f0] = {
    [0] = {
      name = "ffxiv_ipc_submarine_status_list",
      length = 240,
      title = "SubmarineStatusList",
    },
  },
  [0x01fa] = {
    [0] = {
      name = "ffxiv_ipc_retainer_information",
      length = 73,
      title = "RetainerInformation",
    },
  },
  [0x0205] = {
    [0] = {
      name = "ffxiv_ipc_inventory_action_ack",
      length = 16,
      title = "InventoryActionAck",
    },
  },
  [0x0217] = {
    [0] = {
      name = "ffxiv_ipc_actor_control_self",
      length = 32,
      title = "ActorControlSelf",
    },
  },
  [0x023e] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect8",
      length = 632,
      title = "AoeEffect8",
    },
  },
  [0x0246] = {
    [0] = {
      name = "ffxiv_ipc_init_zone",
      length = 96,
      title = "InitZone",
    },
  },
  [0x0260] = {
    [0] = {
      name = "ffxiv_ipc_actor_cast",
      length = 30,
      title = "ActorCast",
    },
  },
  [0x0264] = {
    [0] = {
      name = "ffxiv_ipc_update_class_info",
      length = 16,
      title = "UpdateClassInfo",
    },
  },
  [0x0284] = {
    [0] = {
      name = "ffxiv_ipc_effect_result",
      length = 26,
      title = "EffectResult",
    },
  },
  [0x0285] = {
    [0] = {
      name = "ffxiv_ipc_content_finder_notify_pop",
      length = 32,
      title = "ContentFinderNotifyPop",
    },
  },
  [0x02af] = {
    [0] = {
      name = "ffxiv_ipc_player_stats",
      length = 120,
      title = "PlayerStats",
    },
  },
  [0x02db] = {
    [0] = {
      name = "ffxiv_ipc_actor_free_spawn",
      length = 8,
      title = "ActorFreeSpawn",
    },
  },
  [0x02f5] = {
    [0] = {
      name = "ffxiv_ipc_ce_director",
      length = 16,
      title = "CEDirector",
    },
  },
  [0x02fa] = {
    [0] = {
      name = "ffxiv_ipc_fate_info",
      length = 24,
      title = "FateInfo",
    },
  },
  [0x032c] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect16",
      length = 1208,
      title = "AoeEffect16",
    },
  },
  [0x0356] = {
    [0] = {
      name = "ffxiv_ipc_container_info",
      length = 16,
      title = "ContainerInfo",
    },
  },
  [0x0362] = {
    [0] = {
      name = "ffxiv_ipc_actor_move",
      length = 12,
      title = "ActorMove",
    },
  },
  [0x037e] = {
    [0] = {
      name = "ffxiv_ipc_update_inventory_slot",
      length = 64,
      title = "UpdateInventorySlot",
    },
  },
  [0x03c3] = {
    [0] = {
      name = "ffxiv_ipc_npc_spawn",
      length = 624,
      title = "NpcSpawn",
    },
  },
  [0x03c4] = {
    [0] = {
      name = "ffxiv_ipc_examine",
      length = 656,
      title = "Examine",
    },
  },
  [0x03ca] = {
    [0] = {
      name = "ffxiv_ipc_player_spawn",
      length = 624,
      title = "PlayerSpawn",
    },
    [1] = {
      name = "ffxiv_ipc_update_position_instance",
      length = 40,
      title = "UpdatePositionInstance",
    },
  },
  [0x03d9] = {
    [0] = {
      name = "ffxiv_ipc_aoe_effect32",
      length = 2360,
      title = "AoeEffect32",
    },
  },
}

function M.getDissector(typeNum, length)
  local types = M.types[typeNum]
  if type(types) ~= "table" then
    return nil
  end

  for k, v in pairs(types) do
    if v.length == length then
      return Dissector.get(v.name), v.title
    end
  end

  for k, v in pairs(types) do
    if v.length < length then
      return Dissector.get(v.name), v.title
    end
  end

  return nil
end

return M
