-- This file is generated by network:generate

local db = require('ffxiv_db')
local enum = require('ffxiv_enum')

local ffxiv_ipc_inventory_transaction = Proto("ffxiv_ipc_inventory_transaction", "FFXIV-IPC InventoryTransaction")

local inventory_transaction_fields = {
  sequence          = ProtoField.uint32("ffxiv_ipc_inventory_transaction.sequence", "sequence", base.DEC),
  type              = ProtoField.uint32("ffxiv_ipc_inventory_transaction.type", "type", base.DEC, enum.reverse.inventory_transaction_type),
  owner_id          = ProtoField.uint32("ffxiv_ipc_inventory_transaction.owner_id", "ownerId", base.HEX),
  storage_id        = ProtoField.uint32("ffxiv_ipc_inventory_transaction.storage_id", "storageId", base.DEC, enum.reverse.item_location),
  slot_id           = ProtoField.int16("ffxiv_ipc_inventory_transaction.slot_id", "slotId", base.DEC),
  unknown18         = ProtoField.bytes("ffxiv_ipc_inventory_transaction.unknown18", "unknown18", base.NONE),
  stack_size        = ProtoField.uint32("ffxiv_ipc_inventory_transaction.stack_size", "stackSize", base.DEC),
  catalog_id        = ProtoField.uint32("ffxiv_ipc_inventory_transaction.catalog_id", "catalogId", base.DEC, db.Item),
  some_actor_id     = ProtoField.uint32("ffxiv_ipc_inventory_transaction.some_actor_id", "someActorId", base.HEX),
  target_storage_id = ProtoField.uint32("ffxiv_ipc_inventory_transaction.target_storage_id", "targetStorageId", base.DEC, enum.reverse.item_location),
  target_slot_id    = ProtoField.int16("ffxiv_ipc_inventory_transaction.target_slot_id", "targetSlotId", base.DEC),
  unknown38         = ProtoField.bytes("ffxiv_ipc_inventory_transaction.unknown38", "unknown38", base.NONE),
  target_stack_size = ProtoField.uint32("ffxiv_ipc_inventory_transaction.target_stack_size", "targetStackSize", base.DEC),
  target_catalog_id = ProtoField.uint32("ffxiv_ipc_inventory_transaction.target_catalog_id", "targetCatalogId", base.DEC, db.Item),
}

ffxiv_ipc_inventory_transaction.fields = inventory_transaction_fields

function ffxiv_ipc_inventory_transaction.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_inventory_transaction, tvbuf)
  local len = tvbuf:len()
  if len < 48 then
    tree:add_expert_info(PI_MALFORMED, PI_ERROR, "Truncated InventoryTransaction payload")
    return len
  end

  -- dissect the sequence field
  local sequence_tvbr = tvbuf:range(0, 4)
  local sequence_val  = sequence_tvbr:le_uint()
  tree:add_le(inventory_transaction_fields.sequence, sequence_tvbr, sequence_val)

  -- dissect the type field
  local type_tvbr = tvbuf:range(4, 4)
  local type_val  = type_tvbr:le_uint()
  tree:add_le(inventory_transaction_fields.type, type_tvbr, type_val)

  -- dissect the owner_id field
  local owner_id_tvbr = tvbuf:range(8, 4)
  local owner_id_val  = owner_id_tvbr:le_uint()
  tree:add_le(inventory_transaction_fields.owner_id, owner_id_tvbr, owner_id_val)

  -- dissect the storage_id field
  local storage_id_tvbr = tvbuf:range(12, 4)
  local storage_id_val  = storage_id_tvbr:le_uint()
  tree:add_le(inventory_transaction_fields.storage_id, storage_id_tvbr, storage_id_val)

  local storage_id_display = ", storageId: " .. (enum.reverse.item_location[storage_id_val] or "(unknown)")
  pktinfo.cols.info:append(storage_id_display)
  tree:append_text(storage_id_display)

  -- dissect the slot_id field
  local slot_id_tvbr = tvbuf:range(16, 2)
  local slot_id_val  = slot_id_tvbr:le_int()
  tree:add_le(inventory_transaction_fields.slot_id, slot_id_tvbr, slot_id_val)

  -- dissect the unknown18 field
  local unknown18_tvbr = tvbuf:range(18, 2)
  local unknown18_val  = unknown18_tvbr:raw()
  tree:add(inventory_transaction_fields.unknown18, unknown18_tvbr, unknown18_val)

  -- dissect the stack_size field
  local stack_size_tvbr = tvbuf:range(20, 4)
  local stack_size_val  = stack_size_tvbr:le_uint()
  tree:add_le(inventory_transaction_fields.stack_size, stack_size_tvbr, stack_size_val)

  local stack_size_display = ", stackSize: " .. stack_size_val
  pktinfo.cols.info:append(stack_size_display)
  tree:append_text(stack_size_display)

  -- dissect the catalog_id field
  local catalog_id_tvbr = tvbuf:range(24, 4)
  local catalog_id_val  = catalog_id_tvbr:le_uint()
  tree:add_le(inventory_transaction_fields.catalog_id, catalog_id_tvbr, catalog_id_val)

  local catalog_id_display = ", catalogId: " .. (db.Item[catalog_id_val] or "(unknown)")
  pktinfo.cols.info:append(catalog_id_display)
  tree:append_text(catalog_id_display)

  -- dissect the some_actor_id field
  local some_actor_id_tvbr = tvbuf:range(28, 4)
  local some_actor_id_val  = some_actor_id_tvbr:le_uint()
  tree:add_le(inventory_transaction_fields.some_actor_id, some_actor_id_tvbr, some_actor_id_val)

  -- dissect the target_storage_id field
  local target_storage_id_tvbr = tvbuf:range(32, 4)
  local target_storage_id_val  = target_storage_id_tvbr:le_uint()
  tree:add_le(inventory_transaction_fields.target_storage_id, target_storage_id_tvbr, target_storage_id_val)

  local target_storage_id_display = ", targetStorageId: " .. (enum.reverse.item_location[target_storage_id_val] or "(unknown)")
  pktinfo.cols.info:append(target_storage_id_display)
  tree:append_text(target_storage_id_display)

  -- dissect the target_slot_id field
  local target_slot_id_tvbr = tvbuf:range(36, 2)
  local target_slot_id_val  = target_slot_id_tvbr:le_int()
  tree:add_le(inventory_transaction_fields.target_slot_id, target_slot_id_tvbr, target_slot_id_val)

  -- dissect the unknown38 field
  local unknown38_tvbr = tvbuf:range(38, 2)
  local unknown38_val  = unknown38_tvbr:raw()
  tree:add(inventory_transaction_fields.unknown38, unknown38_tvbr, unknown38_val)

  -- dissect the target_stack_size field
  local target_stack_size_tvbr = tvbuf:range(40, 4)
  local target_stack_size_val  = target_stack_size_tvbr:le_uint()
  tree:add_le(inventory_transaction_fields.target_stack_size, target_stack_size_tvbr, target_stack_size_val)

  -- dissect the target_catalog_id field
  local target_catalog_id_tvbr = tvbuf:range(44, 4)
  local target_catalog_id_val  = target_catalog_id_tvbr:le_uint()
  tree:add_le(inventory_transaction_fields.target_catalog_id, target_catalog_id_tvbr, target_catalog_id_val)

  local target_catalog_id_display = ", targetCatalogId: " .. (db.Item[target_catalog_id_val] or "(unknown)")
  pktinfo.cols.info:append(target_catalog_id_display)
  tree:append_text(target_catalog_id_display)

  return len
end
