-- This file is generated by network:generate

local ffxiv_ipc_countdown_initiate = Proto("ffxiv_ipc_countdown_initiate", "FFXIV-IPC CountdownInitiate")

local countdown_initiate_fields = {
  sender_content_id = ProtoField.uint64("ffxiv_ipc_countdown_initiate.sender_content_id", "senderContentId", base.DEC),
  sender_account_id = ProtoField.uint64("ffxiv_ipc_countdown_initiate.sender_account_id", "senderAccountId", base.DEC),
  sender_actor_id   = ProtoField.uint32("ffxiv_ipc_countdown_initiate.sender_actor_id", "senderActorId", base.DEC),
  world_id          = ProtoField.uint16("ffxiv_ipc_countdown_initiate.world_id", "worldId", base.DEC),
  seconds           = ProtoField.uint16("ffxiv_ipc_countdown_initiate.seconds", "seconds", base.DEC),
  failed_in_combat  = ProtoField.uint8("ffxiv_ipc_countdown_initiate.failed_in_combat", "failedInCombat", base.DEC),
  unknown1          = ProtoField.uint8("ffxiv_ipc_countdown_initiate.unknown1", "unknown1", base.DEC),
  type              = ProtoField.uint8("ffxiv_ipc_countdown_initiate.type", "type", base.DEC),
  sender_name       = ProtoField.string("ffxiv_ipc_countdown_initiate.sender_name", "senderName", base.UNICODE),
}

ffxiv_ipc_countdown_initiate.fields = countdown_initiate_fields

function ffxiv_ipc_countdown_initiate.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_countdown_initiate, tvbuf)
  local len = tvbuf:len()
  if len < 64 then
    tree:add_expert_info(PI_MALFORMED, PI_ERROR, "Truncated CountdownInitiate payload")
    return len
  end

  -- dissect the sender_content_id field
  local sender_content_id_tvbr = tvbuf:range(0, 8)
  local sender_content_id_val  = sender_content_id_tvbr:le_uint64()
  tree:add_le(countdown_initiate_fields.sender_content_id, sender_content_id_tvbr, sender_content_id_val)

  -- dissect the sender_account_id field
  local sender_account_id_tvbr = tvbuf:range(8, 8)
  local sender_account_id_val  = sender_account_id_tvbr:le_uint64()
  tree:add_le(countdown_initiate_fields.sender_account_id, sender_account_id_tvbr, sender_account_id_val)

  -- dissect the sender_actor_id field
  local sender_actor_id_tvbr = tvbuf:range(16, 4)
  local sender_actor_id_val  = sender_actor_id_tvbr:le_uint()
  tree:add_le(countdown_initiate_fields.sender_actor_id, sender_actor_id_tvbr, sender_actor_id_val)

  -- dissect the world_id field
  local world_id_tvbr = tvbuf:range(20, 2)
  local world_id_val  = world_id_tvbr:le_uint()
  tree:add_le(countdown_initiate_fields.world_id, world_id_tvbr, world_id_val)

  -- dissect the seconds field
  local seconds_tvbr = tvbuf:range(22, 2)
  local seconds_val  = seconds_tvbr:le_uint()
  tree:add_le(countdown_initiate_fields.seconds, seconds_tvbr, seconds_val)

  -- dissect the failed_in_combat field
  local failed_in_combat_tvbr = tvbuf:range(24, 1)
  local failed_in_combat_val  = failed_in_combat_tvbr:le_uint()
  tree:add_le(countdown_initiate_fields.failed_in_combat, failed_in_combat_tvbr, failed_in_combat_val)

  -- dissect the unknown1 field
  local unknown1_tvbr = tvbuf:range(25, 1)
  local unknown1_val  = unknown1_tvbr:le_uint()
  tree:add_le(countdown_initiate_fields.unknown1, unknown1_tvbr, unknown1_val)

  -- dissect the type field
  local type_tvbr = tvbuf:range(26, 1)
  local type_val  = type_tvbr:le_uint()
  tree:add_le(countdown_initiate_fields.type, type_tvbr, type_val)

  -- dissect the sender_name field
  local sender_name_tvbr = tvbuf:range(27, 37)
  local sender_name_val  = sender_name_tvbr:string(ENC_UTF_8):match("^[^%z]*")
  tree:add(countdown_initiate_fields.sender_name, sender_name_tvbr, sender_name_val)

  return len
end
