-- This file is generated by network:generate

local ffxiv_ipc_status_effect = Proto("ffxiv_ipc_status_effect", "FFXIV-IPC StatusEffect")

local status_effect_fields = {
  id       = ProtoField.uint16("ffxiv_ipc_status_effect.id", "id", base.DEC),
  extra    = ProtoField.uint16("ffxiv_ipc_status_effect.extra", "extra", base.DEC),
  duration = ProtoField.float("ffxiv_ipc_status_effect.duration", "duration", base.DEC),
  actor_id = ProtoField.uint32("ffxiv_ipc_status_effect.actor_id", "actorId", base.DEC),
}

ffxiv_ipc_status_effect.fields = status_effect_fields

function ffxiv_ipc_status_effect.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_status_effect, tvbuf)
  local len = tvbuf:len()

  -- dissect the id field
  local id_tvbr = tvbuf:range(0, 2)
  local id_val  = id_tvbr:le_uint()
  tree:add_le(status_effect_fields.id, id_tvbr, id_val)

  -- dissect the extra field
  local extra_tvbr = tvbuf:range(2, 2)
  local extra_val  = extra_tvbr:le_uint()
  tree:add_le(status_effect_fields.extra, extra_tvbr, extra_val)

  -- dissect the duration field
  local duration_tvbr = tvbuf:range(4, 4)
  local duration_val  = duration_tvbr:le_float()
  tree:add_le(status_effect_fields.duration, duration_tvbr, duration_val)

  -- dissect the actor_id field
  local actor_id_tvbr = tvbuf:range(8, 4)
  local actor_id_val  = actor_id_tvbr:le_uint()
  tree:add_le(status_effect_fields.actor_id, actor_id_tvbr, actor_id_val)

  return len
end
