-- This file is generated by network:generate

local resolver = require("ffxiv_ipc_resolver")
local M = {}
M.types = {
  [0x006b] = {
    [0] = {
      type = "MarketBoardItemListingHistory",
    },
  },
  [0x008f] = {
    [0] = {
      type = "SystemLogMessage",
    },
  },
  [0x009e] = {
    [0] = {
      type = "PlayerStats",
    },
  },
  [0x00a6] = {
    [0] = {
      type = "PrepareZoning",
    },
  },
  [0x00b4] = {
    [0] = {
      type = "UpdatePositionInstance",
    },
  },
  [0x00b6] = {
    [0] = {
      type = "SubmarineExplorationResult",
    },
  },
  [0x00bd] = {
    [0] = {
      type = "ExamineSearchInfo",
    },
  },
  [0x00d2] = {
    [0] = {
      type = "ActorMove",
    },
  },
  [0x00d7] = {
    [0] = {
      type = "MarketBoardPurchaseHandler",
    },
  },
  [0x00d8] = {
    [0] = {
      type = "Playtime",
    },
  },
  [0x00db] = {
    [0] = {
      type = "ContainerInfo",
    },
  },
  [0x00ea] = {
    [0] = {
      type = "CEDirector",
    },
  },
  [0x00f3] = {
    [0] = {
      type = "CFPreferredRole",
    },
  },
  [0x0103] = {
    [0] = {
      type = "AoeEffect16",
    },
  },
  [0x0104] = {
    [0] = {
      type = "SubmarineStatusList",
    },
  },
  [0x0115] = {
    [0] = {
      type = "ItemInfo",
    },
  },
  [0x011a] = {
    [0] = {
      type = "BossStatusEffectList",
    },
  },
  [0x011e] = {
    [0] = {
      type = "ActorSetPos",
    },
  },
  [0x0137] = {
    [0] = {
      type = "NpcSpawn2",
    },
  },
  [0x0162] = {
    [0] = {
      type = "EventStart",
    },
  },
  [0x016d] = {
    [0] = {
      type = "CurrencyCrystalInfo",
    },
  },
  [0x0181] = {
    [0] = {
      type = "FreeCompanyDialog",
    },
  },
  [0x01a6] = {
    [0] = {
      type = "AoeEffect8",
    },
  },
  [0x01ab] = {
    [0] = {
      type = "InventoryTransactionFinish",
    },
  },
  [0x01c7] = {
    [0] = {
      type = "ResumeEventScene32",
    },
  },
  [0x01cd] = {
    [0] = {
      type = "CompanySubmersibleStatus",
    },
  },
  [0x01cf] = {
    [0] = {
      type = "StatusEffectList",
    },
  },
  [0x01e1] = {
    [0] = {
      type = "UpdateHpMpTp",
    },
  },
  [0x0201] = {
    [0] = {
      type = "UpdateClassInfo",
    },
  },
  [0x0203] = {
    [0] = {
      type = "UpdateInventorySlot",
    },
  },
  [0x0205] = {
    [0] = {
      type = "ActorControlSelf",
    },
  },
  [0x0207] = {
    [0] = {
      type = "EffectResult",
    },
  },
  [0x0208] = {
    [0] = {
      type = "WardLandInfo",
    },
  },
  [0x020e] = {
    [0] = {
      type = "SubmarineProgressionStatus",
    },
  },
  [0x0219] = {
    [0] = {
      type = "Logout",
    },
  },
  [0x021b] = {
    [0] = {
      type = "InventoryHandlerOffset",
    },
    [1] = {
      type = "InventoryModifyHandler",
    },
  },
  [0x021e] = {
    [0] = {
      type = "ClientTrigger",
    },
  },
  [0x0220] = {
    [0] = {
      type = "FreeCompanyInfo",
    },
  },
  [0x0227] = {
    [0] = {
      type = "ActorControlTarget",
    },
  },
  [0x0231] = {
    [0] = {
      type = "AoeEffect32",
    },
  },
  [0x0238] = {
    [0] = {
      type = "AoeEffect24",
    },
  },
  [0x0247] = {
    [0] = {
      type = "ObjectSpawn",
    },
  },
  [0x0255] = {
    [0] = {
      type = "MarketBoardItemListing",
    },
  },
  [0x0257] = {
    [0] = {
      type = "MarketBoardPurchase",
    },
  },
  [0x0258] = {
    [0] = {
      type = "Effect",
    },
  },
  [0x025c] = {
    [0] = {
      type = "ItemMarketBoardInfo",
    },
  },
  [0x0277] = {
    [0] = {
      type = "MarketBoardSearchResult",
    },
  },
  [0x0282] = {
    [0] = {
      type = "ActorControl",
    },
  },
  [0x0286] = {
    [0] = {
      type = "InitZone",
    },
  },
  [0x0299] = {
    [0] = {
      type = "Examine",
    },
  },
  [0x02a0] = {
    [0] = {
      type = "ContentFinderNotifyPop",
    },
  },
  [0x02b2] = {
    [0] = {
      type = "StatusEffectList3",
    },
  },
  [0x02b8] = {
    [0] = {
      type = "EventPlay4",
    },
  },
  [0x02bb] = {
    [0] = {
      type = "EventFinish",
    },
  },
  [0x02c9] = {
    [0] = {
      type = "CompanyAirshipStatus",
    },
  },
  [0x02d0] = {
    [0] = {
      type = "ChatHandler",
    },
  },
  [0x02fe] = {
    [0] = {
      type = "InventoryTransaction",
    },
  },
  [0x030e] = {
    [0] = {
      type = "UpdateSearchInfo",
    },
  },
  [0x030f] = {
    [0] = {
      type = "MarketBoardItemListingCount",
    },
  },
  [0x0310] = {
    [0] = {
      type = "EventPlay",
    },
  },
  [0x0315] = {
    [0] = {
      type = "AirshipExplorationResult",
    },
  },
  [0x0318] = {
    [0] = {
      type = "NpcSpawn",
    },
  },
  [0x0322] = {
    [0] = {
      type = "PlaceFieldMarker",
    },
  },
  [0x0323] = {
    [0] = {
      type = "UpdatePositionHandler",
    },
  },
  [0x0329] = {
    [0] = {
      type = "ActorCast",
    },
  },
  [0x033b] = {
    [0] = {
      type = "EffectResultBasic",
    },
  },
  [0x0341] = {
    [0] = {
      type = "StatusEffectList2",
    },
  },
  [0x034f] = {
    [0] = {
      type = "SetSearchInfoHandler",
    },
  },
  [0x0371] = {
    [0] = {
      type = "PlaceFieldMarkerPreset",
    },
  },
  [0x0390] = {
    [0] = {
      type = "AirshipStatus",
    },
  },
  [0x0399] = {
    [0] = {
      type = "InventoryActionAck",
    },
  },
  [0x039e] = {
    [0] = {
      type = "ActorGauge",
    },
  },
  [0x03a4] = {
    [0] = {
      type = "RetainerInformation",
    },
  },
  [0x03ab] = {
    [0] = {
      type = "FateInfo",
    },
  },
  [0x03b2] = {
    [0] = {
      type = "PlayerSetup",
    },
  },
  [0x03b3] = {
    [0] = {
      type = "PlayerSpawn",
    },
  },
  [0x03d0] = {
    [0] = {
      type = "AirshipStatusList",
    },
  },
  [0x03e4] = {
    [0] = {
      type = "ResumeEventScene16",
    },
  },
}

function M.getDissector(typeNum, length, direction)
  return resolver.getDissector(M.types[typeNum], length, direction)
end

return M
