-- This file is generated by network:generate

local ffxiv_ipc_aoe_effect16 = Proto("ffxiv_ipc_aoe_effect16", "FFXIV-IPC AoeEffect16")

local aoe_effect16_fields = {
  effect_target_ids = ProtoField.bytes("ffxiv_ipc_aoe_effect16.effect_target_ids", "effectTargetIds", base.NONE),
  effect_flags      = ProtoField.bytes("ffxiv_ipc_aoe_effect16.effect_flags", "effectFlags", base.NONE),
}

ffxiv_ipc_aoe_effect16.fields = aoe_effect16_fields

function ffxiv_ipc_aoe_effect16.dissector(tvbuf, pktinfo, root)
  local tree = root:add(ffxiv_ipc_aoe_effect16, tvbuf)
  pktinfo.cols.info:set("AoeEffect16")

  local len = tvbuf:len()

  -- dissect header
  local header_dissector = Dissector.get('ffxiv_ipc_effect_header')
  local header_pos = 0
  local header_len = 42
  local header_count = 1

  while header_pos + header_len <= len do
    local header_tvbr = tvbuf:range(header_pos, 42)
    header_dissector:call(header_tvbr:tvb(), pktinfo, root)
    header_pos = header_pos + header_len
    header_count = header_count - 1
    if header_count <= 0 then
      break
    end
  end

  -- dissect entities
  local entities_dissector = Dissector.get('ffxiv_ipc_effect_entity')
  local entities_pos = 42
  local entities_len = 8
  local entities_count = 128

  while entities_pos + entities_len <= len do
    local entities_tvbr = tvbuf:range(entities_pos, 8)
    entities_dissector:call(entities_tvbr:tvb(), pktinfo, root)
    entities_pos = entities_pos + entities_len
    entities_count = entities_count - 1
    if entities_count <= 0 then
      break
    end
  end

  -- dissect the effect_target_ids field
  local effect_target_ids_tvbr = tvbuf:range(1072, 128)
  local effect_target_ids_val  = effect_target_ids_tvbr:raw(1072)
  tree:add(aoe_effect16_fields.effect_target_ids, effect_target_ids_tvbr, effect_target_ids_val)

  -- dissect the effect_flags field
  local effect_flags_tvbr = tvbuf:range(1200, 8)
  local effect_flags_val  = effect_flags_tvbr:raw(1200)
  tree:add(aoe_effect16_fields.effect_flags, effect_flags_tvbr, effect_flags_val)

  return len
end
