-- This file is generated by network:generate

local resolver = require("ffxiv_ipc_resolver")
local M = {}
M.types = {
  [0x0065] = {
    [0] = {
      type = "StatusEffectList",
    },
  },
  [0x006e] = {
    [0] = {
      type = "ObjectSpawn",
    },
  },
  [0x007c] = {
    [0] = {
      type = "UpdatePositionHandler",
    },
  },
  [0x007e] = {
    [0] = {
      type = "ContentFinderNotifyPop",
    },
  },
  [0x0095] = {
    [0] = {
      type = "ActorMove",
    },
  },
  [0x00a1] = {
    [0] = {
      type = "NpcSpawn2",
    },
  },
  [0x00b3] = {
    [0] = {
      type = "CFPreferredRole",
    },
  },
  [0x00b4] = {
    [0] = {
      type = "SetSearchInfoHandler",
    },
  },
  [0x00c2] = {
    [0] = {
      type = "EffectResult",
    },
  },
  [0x00c5] = {
    [0] = {
      type = "UpdateSearchInfo",
    },
  },
  [0x00d4] = {
    [0] = {
      type = "EffectResult16",
    },
  },
  [0x00d6] = {
    [0] = {
      type = "ResumeEventScene32",
    },
  },
  [0x00e1] = {
    [0] = {
      type = "FateInfo",
    },
  },
  [0x00f5] = {
    [0] = {
      type = "SubmarineExplorationResult",
    },
  },
  [0x00f6] = {
    [0] = {
      type = "NpcSpawn",
    },
  },
  [0x00f7] = {
    [0] = {
      type = "ActorFreeSpawn",
    },
  },
  [0x00fb] = {
    [0] = {
      type = "PlayerStats",
    },
  },
  [0x010f] = {
    [0] = {
      type = "EventPlay",
    },
  },
  [0x0111] = {
    [0] = {
      type = "UpdateInventorySlot",
    },
  },
  [0x0115] = {
    [0] = {
      type = "AoeEffect24",
    },
  },
  [0x0128] = {
    [0] = {
      type = "ChatHandler",
    },
  },
  [0x0132] = {
    [0] = {
      type = "ActionRequestGroundTargeted",
    },
  },
  [0x013f] = {
    [0] = {
      type = "SystemLogMessage",
    },
  },
  [0x0142] = {
    [0] = {
      type = "StatusEffectListForay3",
    },
  },
  [0x014b] = {
    [0] = {
      type = "CurrencyCrystalInfo",
    },
  },
  [0x0163] = {
    [0] = {
      type = "CompanySubmersibleStatus",
    },
  },
  [0x016c] = {
    [0] = {
      type = "CEDirector",
    },
  },
  [0x017c] = {
    [0] = {
      type = "PrepareZoning",
    },
  },
  [0x0186] = {
    [0] = {
      type = "AirshipStatusList",
    },
  },
  [0x0199] = {
    [0] = {
      type = "Playtime",
    },
  },
  [0x01a0] = {
    [0] = {
      type = "ItemInfo",
    },
  },
  [0x01a3] = {
    [0] = {
      type = "MarketBoardRequestItemListingInfo",
    },
  },
  [0x01a5] = {
    [0] = {
      type = "PlaceFieldMarker",
    },
  },
  [0x01aa] = {
    [0] = {
      type = "StatusEffectList2",
    },
  },
  [0x01b8] = {
    [0] = {
      type = "Logout",
    },
  },
  [0x01bb] = {
    [0] = {
      type = "RSV",
    },
  },
  [0x01c0] = {
    [0] = {
      type = "ActorSetPos",
    },
  },
  [0x01cc] = {
    [0] = {
      type = "MarketBoardItemListingHistory",
    },
  },
  [0x01cf] = {
    [0] = {
      type = "ItemMarketBoardInfo",
    },
  },
  [0x01d6] = {
    [0] = {
      type = "PlayerSetup",
    },
  },
  [0x01ea] = {
    [0] = {
      type = "AirshipExplorationResult",
    },
  },
  [0x01f7] = {
    [0] = {
      type = "InventoryTransactionFinish",
    },
  },
  [0x01ff] = {
    [0] = {
      type = "Effect",
    },
  },
  [0x0201] = {
    [0] = {
      type = "MarketBoardPurchaseHandler",
    },
  },
  [0x020a] = {
    [0] = {
      type = "EventPlay32",
    },
  },
  [0x020b] = {
    [0] = {
      type = "SystemLogMessage80",
    },
  },
  [0x020e] = {
    [0] = {
      type = "ActorControlSelf",
    },
  },
  [0x0210] = {
    [0] = {
      type = "ActorGauge",
    },
  },
  [0x0217] = {
    [0] = {
      type = "InventoryActionAck",
    },
  },
  [0x021a] = {
    [0] = {
      type = "CompanyAirshipStatus",
    },
  },
  [0x021f] = {
    [0] = {
      type = "AirshipStatus",
    },
  },
  [0x0237] = {
    [0] = {
      type = "InitZone",
    },
  },
  [0x0247] = {
    [0] = {
      type = "SubmarineStatusList",
    },
  },
  [0x0249] = {
    [0] = {
      type = "StatusEffectList3",
    },
  },
  [0x025c] = {
    [0] = {
      type = "ActorCast",
    },
  },
  [0x0264] = {
    [0] = {
      type = "EventPlay4",
    },
  },
  [0x0277] = {
    [0] = {
      type = "ResumeEventScene16",
    },
  },
  [0x0279] = {
    [0] = {
      type = "SubmarineProgressionStatus",
    },
  },
  [0x027a] = {
    [0] = {
      type = "UpdateClassInfo",
    },
  },
  [0x0280] = {
    [0] = {
      type = "EffectResult4",
    },
  },
  [0x0283] = {
    [0] = {
      type = "AoeEffect8",
    },
  },
  [0x0288] = {
    [0] = {
      type = "UpdateHpMpTp",
    },
  },
  [0x0289] = {
    [0] = {
      type = "SystemLogMessage32",
    },
  },
  [0x028c] = {
    [0] = {
      type = "BattleTalk2",
    },
  },
  [0x028f] = {
    [0] = {
      type = "InventoryHandlerOffset",
    },
    [1] = {
      type = "InventoryModifyHandler",
    },
  },
  [0x0290] = {
    [0] = {
      type = "ExamineSearchInfo",
    },
  },
  [0x0292] = {
    [0] = {
      type = "ClientTrigger",
    },
    [1] = {
      type = "FreeCompanyDialog",
    },
  },
  [0x029a] = {
    [0] = {
      type = "AoeEffect32",
    },
  },
  [0x029c] = {
    [0] = {
      type = "IslandWorkshopSupplyDemand",
    },
  },
  [0x02a5] = {
    [0] = {
      type = "EffectResult8",
    },
  },
  [0x02a7] = {
    [0] = {
      type = "NpcYell",
    },
  },
  [0x02aa] = {
    [0] = {
      type = "PlayerSpawn",
    },
  },
  [0x02c4] = {
    [0] = {
      type = "Examine",
    },
  },
  [0x02c6] = {
    [0] = {
      type = "MarketBoardPurchase",
    },
  },
  [0x02cd] = {
    [0] = {
      type = "MarketBoardSearchResult",
    },
  },
  [0x02d8] = {
    [0] = {
      type = "MapEffect12",
    },
  },
  [0x02e8] = {
    [0] = {
      type = "MarketBoardItemListingCount",
    },
  },
  [0x02f9] = {
    [0] = {
      type = "UpdatePositionInstance",
    },
  },
  [0x02ff] = {
    [0] = {
      type = "ActionRequest",
    },
  },
  [0x0300] = {
    [0] = {
      type = "CountdownCancel",
    },
  },
  [0x0307] = {
    [0] = {
      type = "RetainerInformation",
    },
  },
  [0x0309] = {
    [0] = {
      type = "AoeEffect16",
    },
  },
  [0x0315] = {
    [0] = {
      type = "SystemLogMessage48",
    },
  },
  [0x0318] = {
    [0] = {
      type = "InventoryTransaction",
    },
  },
  [0x031a] = {
    [0] = {
      type = "ContainerInfo",
    },
  },
  [0x032d] = {
    [0] = {
      type = "MarketBoardItemListing",
    },
  },
  [0x0338] = {
    [0] = {
      type = "EnvironmentControl",
    },
  },
  [0x033f] = {
    [0] = {
      type = "CountdownInitiate",
    },
  },
  [0x0343] = {
    [0] = {
      type = "ActorControl",
    },
  },
  [0x0347] = {
    [0] = {
      type = "PlaceFieldMarkerPreset",
    },
  },
  [0x034c] = {
    [0] = {
      type = "EventStart",
    },
  },
  [0x035c] = {
    [0] = {
      type = "WorldVisitQueue",
    },
  },
  [0x0360] = {
    [0] = {
      type = "MapEffect8",
    },
  },
  [0x0364] = {
    [0] = {
      type = "FreeCompanyInfo",
    },
  },
  [0x036e] = {
    [0] = {
      type = "WardLandInfo",
    },
  },
  [0x0371] = {
    [0] = {
      type = "UpdateParty",
    },
  },
  [0x03a2] = {
    [0] = {
      type = "RSF",
    },
  },
  [0x03a6] = {
    [0] = {
      type = "MapEffect4",
    },
  },
  [0x03a7] = {
    [0] = {
      type = "EventFinish",
    },
  },
  [0x03ac] = {
    [0] = {
      type = "BossStatusEffectList",
    },
  },
  [0x03bb] = {
    [0] = {
      type = "WeatherChange",
    },
  },
  [0x03d5] = {
    [0] = {
      type = "EurekaStatusEffectList",
    },
  },
  [0x03db] = {
    [0] = {
      type = "ActorControlTarget",
    },
  },
  [0x03dc] = {
    [0] = {
      type = "SystemLogMessage144",
    },
  },
  [0x03e3] = {
    [0] = {
      type = "EffectResultBasic",
    },
  },
}

function M.getDissector(typeNum, length, direction)
  return resolver.getDissector(M.types[typeNum], length, direction)
end

return M
