-- This file is generated by network:generate

local resolver = require("ffxiv_ipc_resolver")
local M = {}
M.types = {
  [0x0069] = {
    [0] = {
      type = "MarketBoardItemListingCount",
    },
  },
  [0x0085] = {
    [0] = {
      type = "UpdatePositionHandler",
    },
  },
  [0x0087] = {
    [0] = {
      type = "InventoryTransaction",
    },
  },
  [0x0094] = {
    [0] = {
      type = "BossStatusEffectList",
    },
  },
  [0x0097] = {
    [0] = {
      type = "ActorCast",
    },
  },
  [0x00aa] = {
    [0] = {
      type = "SubmarineProgressionStatus",
    },
  },
  [0x00ae] = {
    [0] = {
      type = "EventPlay",
    },
  },
  [0x00bc] = {
    [0] = {
      type = "InitZone",
    },
  },
  [0x00e6] = {
    [0] = {
      type = "Logout",
    },
  },
  [0x00eb] = {
    [0] = {
      type = "AoeEffect32",
    },
  },
  [0x00ec] = {
    [0] = {
      type = "ActorSetPos",
    },
  },
  [0x00ef] = {
    [0] = {
      type = "ContentFinderNotifyPop",
    },
  },
  [0x00ff] = {
    [0] = {
      type = "FreeCompanyInfo",
    },
  },
  [0x0135] = {
    [0] = {
      type = "RetainerInformation",
    },
  },
  [0x0146] = {
    [0] = {
      type = "CompanySubmersibleStatus",
    },
  },
  [0x0147] = {
    [0] = {
      type = "AoeEffect8",
    },
  },
  [0x014c] = {
    [0] = {
      type = "SubmarineStatusList",
    },
  },
  [0x014e] = {
    [0] = {
      type = "Examine",
    },
  },
  [0x016f] = {
    [0] = {
      type = "UpdateHpMpTp",
    },
  },
  [0x0171] = {
    [0] = {
      type = "AirshipStatus",
    },
  },
  [0x017c] = {
    [0] = {
      type = "EffectResult",
    },
  },
  [0x01ab] = {
    [0] = {
      type = "SubmarineExplorationResult",
    },
  },
  [0x01ac] = {
    [0] = {
      type = "FateInfo",
    },
  },
  [0x01bf] = {
    [0] = {
      type = "StatusEffectList",
    },
  },
  [0x01c8] = {
    [0] = {
      type = "CFPreferredRole",
    },
  },
  [0x01ca] = {
    [0] = {
      type = "NpcSpawn",
    },
  },
  [0x01cb] = {
    [0] = {
      type = "InventoryActionAck",
    },
  },
  [0x01d5] = {
    [0] = {
      type = "InventoryTransactionFinish",
    },
  },
  [0x01d9] = {
    [0] = {
      type = "ObjectSpawn",
    },
  },
  [0x01e2] = {
    [0] = {
      type = "AoeEffect24",
    },
  },
  [0x01e3] = {
    [0] = {
      type = "ResumeEventScene32",
    },
  },
  [0x01e9] = {
    [0] = {
      type = "WardLandInfo",
    },
  },
  [0x01f3] = {
    [0] = {
      type = "SystemLogMessage",
    },
  },
  [0x01fd] = {
    [0] = {
      type = "MarketBoardItemListingHistory",
    },
  },
  [0x020e] = {
    [0] = {
      type = "UpdateSearchInfo",
    },
  },
  [0x0213] = {
    [0] = {
      type = "EffectResultBasic",
    },
  },
  [0x021b] = {
    [0] = {
      type = "EnvironmentControl",
    },
  },
  [0x0227] = {
    [0] = {
      type = "Effect",
    },
  },
  [0x022b] = {
    [0] = {
      type = "InventoryHandlerOffset",
    },
    [1] = {
      type = "InventoryModifyHandler",
    },
  },
  [0x022c] = {
    [0] = {
      type = "MarketBoardPurchaseHandler",
    },
  },
  [0x0237] = {
    [0] = {
      type = "MarketBoardPurchase",
    },
  },
  [0x023c] = {
    [0] = {
      type = "SetSearchInfoHandler",
    },
  },
  [0x0243] = {
    [0] = {
      type = "PlaceFieldMarkerPreset",
    },
  },
  [0x0260] = {
    [0] = {
      type = "ActorFreeSpawn",
    },
  },
  [0x0265] = {
    [0] = {
      type = "ItemInfo",
    },
  },
  [0x0269] = {
    [0] = {
      type = "ClientTrigger",
    },
  },
  [0x026f] = {
    [0] = {
      type = "ExamineSearchInfo",
    },
  },
  [0x0276] = {
    [0] = {
      type = "NpcSpawn2",
    },
  },
  [0x0288] = {
    [0] = {
      type = "UpdatePositionInstance",
    },
  },
  [0x028b] = {
    [0] = {
      type = "RSV",
    },
  },
  [0x0294] = {
    [0] = {
      type = "StatusEffectList3",
    },
  },
  [0x02a7] = {
    [0] = {
      type = "CompanyAirshipStatus",
    },
  },
  [0x02c2] = {
    [0] = {
      type = "ActorGauge",
    },
  },
  [0x02d9] = {
    [0] = {
      type = "ActorMove",
    },
  },
  [0x02df] = {
    [0] = {
      type = "ContainerInfo",
    },
  },
  [0x02ed] = {
    [0] = {
      type = "Playtime",
    },
  },
  [0x02f7] = {
    [0] = {
      type = "PlayerStats",
    },
  },
  [0x0319] = {
    [0] = {
      type = "ResumeEventScene16",
    },
  },
  [0x0321] = {
    [0] = {
      type = "ItemMarketBoardInfo",
    },
  },
  [0x0322] = {
    [0] = {
      type = "PlayerSetup",
    },
  },
  [0x0326] = {
    [0] = {
      type = "AirshipStatusList",
    },
  },
  [0x032e] = {
    [0] = {
      type = "AoeEffect16",
    },
  },
  [0x0331] = {
    [0] = {
      type = "PrepareZoning",
    },
  },
  [0x0342] = {
    [0] = {
      type = "ActorControl",
    },
  },
  [0x0344] = {
    [0] = {
      type = "AirshipExplorationResult",
    },
  },
  [0x0345] = {
    [0] = {
      type = "MarketBoardItemListing",
    },
  },
  [0x0346] = {
    [0] = {
      type = "PlaceFieldMarker",
    },
  },
  [0x0356] = {
    [0] = {
      type = "StatusEffectList2",
    },
  },
  [0x0359] = {
    [0] = {
      type = "ActorControlTarget",
    },
  },
  [0x035c] = {
    [0] = {
      type = "FreeCompanyDialog",
    },
  },
  [0x0373] = {
    [0] = {
      type = "ChatHandler",
    },
  },
  [0x0376] = {
    [0] = {
      type = "MarketBoardSearchResult",
    },
  },
  [0x037e] = {
    [0] = {
      type = "UpdateClassInfo",
    },
  },
  [0x0391] = {
    [0] = {
      type = "PlayerSpawn",
    },
  },
  [0x03a7] = {
    [0] = {
      type = "CurrencyCrystalInfo",
    },
  },
  [0x03b8] = {
    [0] = {
      type = "EventFinish",
    },
  },
  [0x03bd] = {
    [0] = {
      type = "EventPlay4",
    },
  },
  [0x03cb] = {
    [0] = {
      type = "EventStart",
    },
  },
  [0x03ce] = {
    [0] = {
      type = "CEDirector",
    },
  },
  [0x03d5] = {
    [0] = {
      type = "ActorControlSelf",
    },
  },
  [0x03da] = {
    [0] = {
      type = "IslandWorkshopSupplyDemand",
    },
  },
  [0x03e2] = {
    [0] = {
      type = "UpdateInventorySlot",
    },
  },
}

function M.getDissector(typeNum, length, direction)
  return resolver.getDissector(M.types[typeNum], length, direction)
end

return M
